### ISSUE TITLE
configure gets stuck at "checking types of args and return type for recvfrom"

### ISSUE THREAD

**Issue by lazka** [c-ares/c-ares#129]
Trying to build using mingw on msys2.

**Comment by gjasny** [comment]
To unblock you: have you tried configuring with CMake?

**Comment by lazka** [comment]
Thanks. I don't see any CMake related files in the release tarball. Is it supported?

**Comment by gjasny** [comment]
Seems like the CMakeLists.txt files are not packaged by `make dist`. Please checkout the git repo on the `cares-1_13_0` tag.

**Comment by gjasny** [comment]
And yes, it is supported.

**Comment by gjasny** [comment]
How long did you wait for the recvfrom test to finish? Even on Linux the check takes ages.

**Comment by lazka** [comment]
A minute or two. I'll try waiting longer and try using CMake it that fails. Thanks for your help.

**Comment by gjasny** [comment]
CMake files distribution will be fixed with #130.

**Comment by lazka** [comment]
Waiting a few more minutes helped :)

Thanks!
