### ISSUE TITLE
dns suffix issue in 1.13.0

### ISSUE THREAD

**Issue by tudu123** [c-ares/c-ares#136]
The dns suffix support in c-ares 1.13.0 is still unstable, Input the single-label unqualified server name, e.g. abc
1. some client hosts joined domain and append dns suffix suchas xyz.com 
2. C:\temp\1.13.0>curl -v https://abc
* Rebuilt URL to: https://abc/
* Could not resolve: abc (Domain name not found)
* Closing connection 0
curl: (6) Could not resolve: abc (Domain name not found)
MS ping/nslookup or IE doesn't have the issue in the hosts.

**Comment by bradh352** [comment]
And abc.xyz.com does resolve with ares?  I just want to make sure you're not talking about a WINS/NetBIOS name or similar.   Do you have a screenshot showing this xyz.com is a suffix configured somewhere on the system?

Including @ChristianAmmer who provided the Windows DNS Suffix support.

**Comment by ChristianAmmer** [comment]
I have nothing to append, this is basically what would help to analyze the problem in the first step (the suffix list can be retrieved through "ipconfig /all").

**Comment by tudu123** [comment]
I attached the screenshots, please review, thanks.
![ipconfig](https://user-images.githubusercontent.com/6697251/28860450-4755b48c-778f-11e7-821c-ea6f5f8214fe.PNG)
![pingvscurl](https://user-images.githubusercontent.com/6697251/28860452-4759da08-778f-11e7-8abd-ac5afe1a6a22.PNG)
![dns-setting](https://user-images.githubusercontent.com/6697251/28860451-4759c220-778f-11e7-99ea-81eeb6235123.PNG)
![computer](https://user-images.githubusercontent.com/6697251/28860453-475aacb2-778f-11e7-84dc-624fbe0dd3a1.PNG)

**Comment by gvanem** [comment]
You always use (or build) curl without C-ares. Using the Windows built-in resolver should work in your case. Add `-DUSE_THREADS_WIN32` to your `CFLAGS` and make sure `-DUSE_ARES` is *not* in `CFLAGS`.

**Comment by bradh352** [comment]
Interesting that the error you received was "Could not contact DNS servers" rather than some other error.  Can you verify that abc.xyz.com actually works with your build of curl?

**Comment by tudu123** [comment]
The FQDN works with the curl/c-ares.
![fqdn](https://user-images.githubusercontent.com/6697251/28872979-1e8c0856-77be-11e7-8a95-ea48fc92fb04.PNG)

**Comment by ChristianAmmer** [comment]
@tudu123 can you check what is stored in the registry entry:
- `PrimaryDnsSuffix` from `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\System\DNSClient`
and also if the registry key
- `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\Interfaces`
exists.

**Comment by bradh352** [comment]
@tudu123 can you provide @ChristianAmmer the information requested?  If not, I'll probably need to close this issue.

**Comment by bradh352** [comment]
closing due to lack of feedback from submitter
