### ISSUE TITLE
outdated ares_sock_state_cb doc

### ISSUE THREAD

**Issue by wongsyrone** [c-ares/c-ares#140]
It should be 
```
typedef void (*ares_sock_state_cb)(void *data,
                                   ares_socket_t socket_fd,
                                   int readable,
                                   int writable)
```
but the doc says
```
void (*\fIsock_state_cb\fP)(void *data, int s, int read, int write)
```

ref:
https://github.com/c-ares/c-ares/blob/bcfbad93b8128634b72072a9ffcabb94c52183ef/ares.h#L227

https://github.com/c-ares/c-ares/blob/3aead6a988b9685b6ad484fa2798f81e2a76f2d8/ares_init_options.3#L142

**Comment by daviddrysdale** [comment]
Fixed, thanks for spotting.

**Comment by wongsyrone** [comment]
Thanks for the fix. It would be better if someone can scan all the docs and make sure they match source code. ;)
