### ISSUE TITLE
c-ares doesn't use NRPT/DNSSEC configuration

### ISSUE THREAD

**Issue by tudu123** [c-ares/c-ares#147]
c-ares 1.13.0 in Windows doesn't use Name Resolution Policy Table https://technet.microsoft.com/en-us/library/ee649207(v=ws.10).aspx

Configured DNSSEC in Domain/DNS server, push the nrpt group policy to client host as below 
c-ares doesn't query OPT to require DNS validation, and it also doesn't read the GenericDNSServers setting if configured the genericDNSServers.

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig\{9913d84a-bb46-48e2-bacb-3dc8fcf62ab8}]
"ConfigOptions"=dword:0000000a
"Name"=hex(7):2e,00,73,00,65,00,63,00,2e,00,64,00,65,00,66,00,2e,00,63,00,6f,\
  00,6d,00,00,00,00,00
"IPSECCARestriction"=""
"DNSSECValidationRequired"=dword:00000001
"DNSSECQueryIPSECRequired"=dword:00000000
"DNSSECQueryIPSECEncryption"=dword:00000000
"GenericDNSServers"="10.117.46.1"
"Version"=dword:00000001

**Comment by bradh352** [comment]
DNSSec is done by the nameserver used.  I know in versions after 1.13 there were significant windows changes that fixed many issues in choosing the right DNS servers.
