### ISSUE TITLE
Configuring build on Linux does not fill pkg-config version

### ISSUE THREAD

**Issue by mroland91** [c-ares/c-ares#149]
Hi,

https://github.com/c-ares/c-ares/blob/b4f1ff7b5125223dcd2a1b7178ff5927bf1252d7/libcares.pc.in#L15

The version is not filled when I configure the build. Maybe I am missing something but it was working on a previous version.

Best Regards,
Roland

**Comment by gjasny** [comment]
Did you build from git or from a tarball. If tarball, where did you get it from?

**Comment by mroland91** [comment]
Previously I've downloaded the tarball from GitHub but I can see #137 is about the same issue.
Using the tarball from official website it is working as it should. Thanks.
