### ISSUE TITLE
DNS Resolve issue after set multiple DNS servers

### ISSUE THREAD

**Issue by tudu123** [c-ares/c-ares#150]
OS: Windows
c-ares version: 1.13.0
Steps:
1. Untick ipv6 setting.
2. Configure Preferred and Alternative DNS servers in windows network setting.
3. Launch curl/c-ares to connect to a FQDN which only preferred DNS server can resolve.
Result:
 * Rebuilt URL to: https://xxx.com
* Could not resolve: xxx.com (Domain name not found)
* Closing connection 0
curl: (6) Could not resolve: xxx.com (Domain name not found)

**Comment by tudu123** [comment]
This is a regresson issue since c-ares version 1.12.0 is fine.

**Comment by bradh352** [comment]
This was fixed in 33bf5ba, please try the latest master

**Comment by tudu123** [comment]
Thanks for your quickly response! May I ask if the next c-ares version release date is scheduled or no plan yet?
