### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [c-ares/c-ares#159]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by Croydon** [comment]
https://github.com/conan-io/wishlist/issues/99

**Comment by bagder** [comment]
I don't think it is the c-ares project's job to package it up for different package systems or distributions. But feel free to do it, it is fully open source, free and available.
