### ISSUE TITLE
cmake macro CARES_TYPE_EXISTS and -Werror

### ISSUE THREAD

**Issue by noahdesu** [c-ares/c-ares#162]
Users of c-ares that use cmake add_subdirectory have to be careful to not call add_subdirectory(c-ares) after adding common compile flags -Werror.

The compile test used by the macro doesn't use its test variable, so it throws -Wunused-variable.

This results in c-ares not detecting things like struct timeval.

**Comment by bradh352** [comment]
Does e5a3529 fix it for you?
