### ISSUE TITLE
[Question] Is it possible to use different DNS nameservers for different queries?

### ISSUE THREAD

**Issue by MasterGroosha** [c-ares/c-ares#165]
Sorry for this dumb question, but is it possible somehow to use custom DNS servers (entered programmatically and not defined in OS) for queries?
For example, I'd like to resolve `example.com` using DNS nameserver `8.8.8.8` and `example.org` using DNS nameserver `5.5.5.5`.

**Comment by gvanem** [comment]
Yes, sure. See `adig.c` and option `-s` for how it's done.

**Comment by bradh352** [comment]
For questions, we'd suggest using the mailing list.
