### ISSUE TITLE
assert in ares_destroy.c

### ISSUE THREAD

**Issue by yandreiy** [c-ares/c-ares#172]
There's the following assert happening when using libcurl built with c-ares:
c-ares-1.13.0/ares_destroy.c:66: ares_destroy: Assertion `ares__is_list_empty(&(channel->queries_by_qid[i]))' failed.

Any hints about the possible reasons for this ?

**Comment by daviddrysdale** [comment]
The comment above describes what's going on: "Freeing the query should remove it from all the lists in which it sits, so all query lists should be empty now".  

A pending query is held in multiple lists at the same, so it can be looked up via different criteria; when a query is freed, it should get removed from all of the different lists at once.   So if the code goes through removing everything in the `all_queries` list, by the time it's finished all the other lists should be empty too.

If this assert is firing, it implies some of the internal book-keeping between these different lists has gone wrong (maybe something is freeing queries without using `ares__free_query` or somesuch?)

**Comment by yandreiy** [comment]
Ok, so something went wrong internally and the assert is triggered. This looks like a bug in c-ares, no ?

**Comment by daviddrysdale** [comment]
It could well be a c-ares bug, or there could be another cause (e.g. memory corruption, invalid/incorrect use of the c-ares API).  Without more information there's not really a way to tell.

**Comment by bradh352** [comment]
thread appears dead, closing
