### ISSUE TITLE
Unknown value for _NMAKE_VER macro: "14.12.25835.0"

### ISSUE THREAD

**Issue by Croydon** [c-ares/c-ares#178]
>Microsoft (R) Program Maintenance Utility, Version 14.12.25835.0
Copyright (C) Microsoft Corporation. All rights reserved.

> Unknown value for _NMAKE_VER macro: "14.12.25835.0"
Please, report this condition on the c-ares development
mailing list: http://cool.haxx.se/mailman/listinfo/c-ares/
.\msvc_ver.inc(76) : fatal error U1050: See previous message.
Stop.

Why do you strictly limit the version in the first place?

**Comment by Croydon** [comment]
This is fixed by https://github.com/c-ares/c-ares/commit/7e1a8fcd04b517e6f886aa372650ec8426851dfd in master.

Not yet in any release unfortunately.

**Comment by toast12** [comment]
Hi, I am using the cares-1_14_0 tag to get this fixed in my build. But still have the same issue. Verified that 7e1a8fc is my tag. Wondering if you have verified that the patch fixes the NMAKE error reported above?

**Comment by Croydon** [comment]
@toast12 Seems so, yes https://ci.appveyor.com/project/lasote/conan-c-ares/build/1.0.16
