### ISSUE TITLE
Coverage is broken

### ISSUE THREAD

**Issue by dimbleby** [c-ares/c-ares#194]
a255081f arranged that `covupload.sh` only runs when `"$BUILD_TYPE" = "normal"`.  

But that script only does anything when `"$BUILD_TYPE" = "coverage"`!  As a result, coverage figures are not being updated for this project.

So far as I can see, a255081f simply wants reverting.  But that probably shows that I've misunderstood what it was trying to do... @daviddrysdale?

**Comment by daviddrysdale** [comment]
Good spot, but I think the change needs splitting rather than reverting (IIRC there were problems with `make distcheck` on some platforms)
