### ISSUE TITLE
Drop DNS request for ".onion" special-use domain name

### ISSUE THREAD

**Issue by MarkTiedemann** [c-ares/c-ares#196]
See: [https://tools.ietf.org/html/rfc7686](https://tools.ietf.org/html/rfc7686)

> Name Resolution APIs and Libraries (...) MUST either respond to requests for .onion names by resolving them according to [tor-rendezvous] or by responding with NXDOMAIN.

> A legacy client may inadvertently attempt to resolve a .onion name through the DNS. This causes a disclosure that the client is attempting to use Tor to reach a specific service. Malicious resolvers could be engineered to capture and record such leaks, which might have very adverse consequences for the well-being of the user. This issue is mitigated if the client's software is updated to not leak such queries or updated to support [tor-rendezvous], or if the client's DNS software is updated to drop any request to the .onion special-use domain name.

**Comment by bradh352** [comment]
Seems like a reasonable request, if you happen to have a patch, we'll review it.  Otherwise it may take a little time for a developer to make this change.

**Comment by MarkTiedemann** [comment]
@bradh352 I have no patch yet, as well as no experience in writing C++, but I might give it a shot.

**Comment by bradh352** [comment]
fixed per #228
