### ISSUE TITLE
c-ares ignores domain search suffix on windows

### ISSUE THREAD

**Issue by p** [c-ares/c-ares#197]
I am testing pycurl built against libcurl built against c-ares on windows, with the following environment variable set:

<pre>
export http_proxy=http://gwr:3128
</pre>

`gwr` is the name of the gateway machine on the local network. This machine provides DHCP, DNS and proxy services and specifies the following settings in `resolv.conf` on a Linux machine on the same network:

<pre>
domain here
search here
</pre>

Hence, the full name of the gateway is `gwr.here`.

Various other software operates correctly with the HTTP(S) proxy set to `http://gwr:3128`, including Firefox/Pale Moon, Git, Python.

But c-ares as used by libcurl, as far as I can tell, attempts to resolve `gwr` without trying `gwr.here` which fails.

The error I am getting is:

<pre>
Could not resolve: gwr (Domain name not found)
</pre>

None of the tests mention this proxy - it is only specified in the environment - thus this is not an issue with my tests as far as I can tell.

c-ares 1.14.0

**Comment by bradh352** [comment]
What version of Windows is being used?

The current logic for retrieving the search list/suffixes is here:
https://github.com/c-ares/c-ares/blob/master/ares_init.c#L1396
With some of the parameters referenced defined here:
https://github.com/c-ares/c-ares/blob/master/ares_private.h#L56

If you happen to know where in the registry windows stores that data, and its different than the current codepaths it shouldn't be terribly difficult to update.

**Comment by p** [comment]
Win 7, I will attempt to debug per those references.

**Comment by bradh352** [comment]
I'm going to close this as I believe PR #202 which was merged fixed this.
