### ISSUE TITLE
Unvalidated 'hostaliases' received from getenv

### ISSUE THREAD

**Issue by thongpv3** [c-ares/c-ares#199]
I checked c-ares with klockwork then it show me this issues:

> Unvalidated string `hostaliases` is received from external function through call to `getenv` at line 251 can be used for path traversal through call to `fopen` at line 254. This can lead to access to undesired resource outside of restricted directory. Check the content of string used for access to files and directory

https://github.com/c-ares/c-ares/blob/b93997b67816874a5ebd77998fe32226fddbe817/ares_search.c#L254

**Comment by bradh352** [comment]
This is intentional behavior as per   man hostname(7):
http://man7.org/linux/man-pages/man7/hostname.7.html

Looks like a false-positive to me.
