### ISSUE TITLE
ares_set_socket_functions API assumes HAVE_WRITEV=1

### ISSUE THREAD

**Issue by apolcyn** [c-ares/c-ares#206]
The `ares_set_socket_functions` API uses, as one of the customized functions, [a sendv method](https://github.com/c-ares/c-ares/blob/master/ares.h#L384). This takes a `struct iovec` as a param. If `struct iovec` is not defined on the native platform (windows), then c-ares internally defines this struct in its [ares_writev.h](https://github.com/c-ares/c-ares/blob/master/ares_writev.h#L23) file. However, `ares_writev.h` is not, in general, [treated as a public header](https://github.com/c-ares/c-ares/blob/master/CMakeLists.txt#L640), and this makes it problematic to use `ares_set_socket_functions` API on platforms which don't provide the  `struct iovec` definition natively.

a) Can the `ares_writev.h` header be publicized?
b) Is there a different suggested way to deal with this?

**Comment by gvanem** [comment]
Would not be a big deal IMHO to *always* use `ares_writev()` and `ares_iovec`. And make those public.
I doubt a system `writev()` would be so much faster than the C-ares' version.

Just my € 0.02.

**Comment by apolcyn** [comment]
^ +1

I can't speak for everywhere, but my intended usage is not particularly performance concerned with the writev call.

**Comment by arrtchiu** [comment]
Any drawback to making it public?

Another idea: Allow ares to keep this private by adding a method which can fill in a `struct ares_socket_functions` with the private methods.. e.g.:

```c
void ares_setup_default_socket_functions(struct ares_socket_functions* funcs) {
  funcs->asendv = &ares_writev;
  //.. etc
}
```

**Comment by bradh352** [comment]
Unfortunately this is an historic public api issue, I'm not exactly sure the best way to resolve.  As of PR #552, c-ares doesn't internally use writev at all.

**Comment by bradh352** [comment]
I just made a change to allow passing NULL for any of the callbacks to delegate to the system call.  Not sure if that's sufficient, but really, not much else we can do.  If this callback is registered, the iovec size passed will always be 1 since we no longer do scatter/gather operations.
