### ISSUE TITLE
ares_* are not thread safe with respect to the same channel

### ISSUE THREAD

**Issue by Seraphime** [c-ares/c-ares#208]
Problem:

When using ares_gethostbyname (and others) from multiple threads to the same channel, functions manipulating the builtin linked-lists and hash tables race with each other which causes various corruptions.

Why [is this an issue] ?

Ares channels are pretty powerful and can handle a large amount of requests. Currently I'm able to do 10 000+ parallel resolutions with just one channel. One of the bottle necks I've found is that I have to synchronize `process_fd` and `get_hostbyname` very brutally by grabbing a big mutex around them, which is a waste as in some cases execution never gets to the critical sections.

Example:
```

    /* Keep track of queries bucketed by timeout, so we can process
     * timeout events quickly.
     */
    ares__remove_from_list(&(query->queries_by_timeout));
    ares__insert_in_list(
        &(query->queries_by_timeout),
        &(channel->queries_by_timeout[query->timeout.tv_sec %
                                      ARES_TIMEOUT_TABLE_SIZE]));

    /* Keep track of queries bucketed by server, so we can process server
     * errors quickly.
     */
    ares__remove_from_list(&(query->queries_to_server));
    ares__insert_in_list(&(query->queries_to_server),
                                  &(server->queries_to_server));
```

I'm volunteering to implement a fix for Linux and Windows, if the community acknowledges the issue.

**Comment by Seraphime** [comment]
A  nice example of a race would be

Assuming a "timer thread" and *one* processing thread:

ares_timeout()
   -> iterate on channel->all_queries
ares_send()
   -> ares__insert_in_list(..., &channel->all_queries)

Or

ares_timeout()
    -> iterate on channel->all_queries
ares_process_fd 
    -> ares__free_query
        -> ares__remove_from_list


If we assume two or more processing threads, the we get even more tight races.

I propose to use read-writer locks around the llist manipulation places, and make that an opt-in compile-time option for now.

**Comment by bradh352** [comment]
I'm not sure I'd consider this an "issue".  Its just inherently not designed to handle multi-threading itself, that's fully up to the implementor which is ok.  Due to its design, its unlikely you'd be able to truly implement such support into c-ares without some major caveats. You'd still have to "wake" your poll(),epoll(),kqueue(),select() or whatever otherwise your timeouts won't be updated with your event system.  Therein lies your real solution:

1. Enqueue new request in your own queue system that is threadsafe
2. Send a wake signal to your event loop that c-ares is running in (e.g. on linux a pipe could be used for this)
3. When a signal the c-ares event loop wakes up, and as part of that process, it dequeues new requests from your threadsafe queue system an puts them on the wire with c-ares.

**Comment by yangboyd** [comment]
> Problem:
> 
> When using ares_gethostbyname (and others) from multiple threads to the same channel, functions manipulating the builtin linked-lists and hash tables race with each other which causes various corruptions.
> 
> Why [is this an issue] ?
> 
> Ares channels are pretty powerful and can handle a large amount of requests. Currently I'm able to do 10 000+ parallel resolutions with just one channel. One of the bottle necks I've found is that I have to synchronize `process_fd` and `get_hostbyname` very brutally by grabbing a big mutex around them, which is a waste as in some cases execution never gets to the critical sections.
> 
> Example:
> 
> ```
> 
>     /* Keep track of queries bucketed by timeout, so we can process
>      * timeout events quickly.
>      */
>     ares__remove_from_list(&(query->queries_by_timeout));
>     ares__insert_in_list(
>         &(query->queries_by_timeout),
>         &(channel->queries_by_timeout[query->timeout.tv_sec %
>                                       ARES_TIMEOUT_TABLE_SIZE]));
> 
>     /* Keep track of queries bucketed by server, so we can process server
>      * errors quickly.
>      */
>     ares__remove_from_list(&(query->queries_to_server));
>     ares__insert_in_list(&(query->queries_to_server),
>                                   &(server->queries_to_server));
> ```
> 
> I'm volunteering to implement a fix for Linux and Windows, if the community acknowledges the issue.
Hi Seraphime,
Have you implemented this fix?
