### ISSUE TITLE
Unknown value for _NMAKE_VER macro: "14.12.25835.0"

### ISSUE THREAD

**Issue by upadhyaym** [c-ares/c-ares#212]
Hi,

I am trying to build with VS 2017 in my environment. Noticed a similar issue reported here: https://github.com/c-ares/c-ares/issues/178

And upgraded to c-ares 1.14.0 to apply the fixes in commit 7e1a8fc as mentioned there. But I am still getting the same error. What could be going wrong here?

**Comment by upadhyaym** [comment]
Modified Makefile.msvc to add NMAKE Version check and this fixed the issue:

!ELSEIF "$(_NMAKE_VER)" == "14.10.25017.0"
CC_VERS_NUM = 140
!ELSEIF "$(_NMAKE_VER)" == "14.10.25019.0"
CC_VERS_NUM = 140
**!ELSEIF "$(_NMAKE_VER)" == "14.12.25835.0"
CC_VERS_NUM = 140**
!ELSE
!  MESSAGE Unknown value for _NMAKE_VER macro: "$(_NMAKE_VER)"
!  MESSAGE Please, report this condition on the c-ares development
!  MESSAGE mailing list: http://cool.haxx.se/mailman/listinfo/c-ares/
!  ERROR   See previous message.
!ENDIF

**Comment by bradh352** [comment]
The current master branch does not have this issue as it no longer needs to know the exact version for modern MSVC versions.

**Comment by upadhyaym** [comment]
Hi, I am using the tagged release for 1.14.0 and it does have this issue.

**Comment by dimbleby** [comment]
No it doesn't: see [here](https://github.com/c-ares/c-ares/blob/cares-1_14_0/msvc_ver.inc#L23).

**Comment by upadhyaym** [comment]
Thanks! Looks like one of our previous internal patches was adding the entire NMAKE_VER check back in when you have removed it completely from your Makefile.msvc. I have reversed that patch. All good now.
