### ISSUE TITLE
build shared libraries  for ANDROID  failed

### ISSUE THREAD

**Issue by darkterrorooo** [c-ares/c-ares#217]
hi,  when try to create shared lib for android.  error:

clang: error: no such file or directory: './.libs/libcares.so'

can some one help?

this is  my  configure.

export PATH="/Users/ljg/android/mytoolchain":$PATH
./configure --prefix=/Users/ljg/opensource/c-ares-cares1.4/abuild \
--enable-debug \
--enable-shared \
--host=arm-linux-androideabi
make

**Comment by darkterrorooo** [comment]
fix title

**Comment by darkterrorooo** [comment]
i had  solved by fix my  config file:

----build.sh------
export PATH=/Users/ljg/android/mytoolchain/bin:$PATH
export SYSROOT=/Users/ljg/android/mytoolchain/sysroot
export CC="arm-linux-androideabi-gcc --sysroot $SYSROOT"

./configure --prefix=/Users/ljg/opensource/c-ares-cares1.4/abuild \
--enable-shared \
--enable-debug \
--host=arm-linux-androideabi
CFLAGS="-march=armv7-a"

make & make install

**Comment by gjasny** [comment]
You could also use CMake:
```
cmake \
-DCARES_STATIC=ON -DCARES_SHARED=OFF \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_SYSTEM_NAME=Android \
-DCMAKE_ANDROID_NDK=${ANDROID_NDK_HOME} \
-DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
-DCMAKE_SYSTEM_VERSION=14 \
-DCMAKE_ANDROID_STL_TYPE=gnustl_static \
-DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=4.9 \
..
```
