### ISSUE TITLE
third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]  sizeof(src->local_dev_name));

### ISSUE THREAD

**Issue by marcoippolito** [c-ares/c-ares#222]
in my Ubuntu 18.04.1 LTS I'm just trying to install and build gRPC, but in the "make" step, as you can see, there is a stopping error:

![grpcbuildingerror01](https://user-images.githubusercontent.com/3073209/45833009-c9068780-bd03-11e8-862f-24dfb8d666bb.jpg)
![grpcbuildingerror02](https://user-images.githubusercontent.com/3073209/45833020-d02d9580-bd03-11e8-9aa2-03a0bbf294ce.jpg)

What do I have to do to solve the problem? Looking forward to your kind hints and help.
Marco

**Comment by dimbleby** [comment]
duplicate #210

**Comment by bradh352** [comment]
I'm assuming this is resolved since the linked ticket is
