### ISSUE TITLE
error compiling on c-ares AIX

### ISSUE THREAD

**Issue by amandeepgautam** [c-ares/c-ares#224]
When trying to compile on AIX, I see the following error:

```
In file included from /tmp/aix_softwares/cares-1.14.0/ares_parse_a_reply.c:34:
/usr/include/arpa/nameser_compat.h:244:3: error: conflicting types for 'HEADER'
 } HEADER;
   ^~~~~~
In file included from /usr/include/arpa/nameser.h:645,
                 from /tmp/aix_softwares/cares-1.14.0/ares_parse_a_reply.c:29:
/usr/include/arpa/onameser_compat.h:265:3: note: previous declaration of 'HEADER' was here
 } HEADER;
   ^~~~~~
```

To compile, I did the following:
```
cd /path/to/cmake/source
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/cares ..

```

Any suggestions on how to solve the problem? I would be willing to send a PR for this, if suggestion is given. Problem seems to be that on AIX both these HEADER is defined in both .h files. Please let me know.

**Comment by amandeepgautam** [comment]
I am using AIX 7200-01-03-1720 and official release 1.14.0 release.
Following is how the two files look on this versions of AIX:
https://pastebin.com/c9VZPwGn
https://pastebin.com/WcjMnffk

**Comment by bradh352** [comment]
basically looks the same, not sure why I'm not seeing that same issue on AIX 5.  I really think the solution is to set _USE_IRS on AIX.  I wonder if autotools doesn't already set that flag and its just something we ned to add to cmake.

**Comment by amandeepgautam** [comment]
@bradh352 I am very unfamiliar with the code base but if you could explain in more detail, i could give it a try and test it.

**Comment by amandeepgautam** [comment]
@bradh352 yes that compiles. Thanks for fixing this.
However, it only generates 32-bit lib? How could we generate 64-bit libs?

**Comment by bradh352** [comment]
That's just whatever your compiler and tools default to.  No build system ever builds both 32bit and 64bit.

From what I recall though, on AIX, pretty much everything honors the OBJECT_MODE environment variable and the valid values are/were 32 or 64.

**Comment by anshul-j** [comment]
Hi 
I am using the c-ares 1.14.0 library on AIX and using the below command to build the libcares.a
./configure --prefix=/usr
make)
Now i am trying to use this library with my application executable but While linking i am getting the below errors

[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_inet_pton
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_init_options
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_strerror
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_query
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_cancel
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_destroy
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_fds
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_process
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_expand_name
[00:49:11]W:				 [install] ld: 0711-317 ERROR: Undefined symbol: .ares_free_string
[00:49:11]W:				 [install] ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
[00:49:11]W:				 [install] collect2: error: ld returned 8 exit status

Please help here.

Thanks
Anshul Jain

**Comment by dfandrich** [comment]
This issue and that version are several years old by now. Please try the latest
version and open a new issue if it still doesn't work.

**Comment by anshul-j** [comment]
c-ares 1.14.0 version was released on 16-feb-2018.This is working fine for windows and linux but for aix i am getting above mentioned errors. According to you, it is c-ares verison related issue or AIX version related issue ?
Please confirm.

**Comment by dfandrich** [comment]
I don't use AIX so I can't confirm. But, it should be easy for you to confirm
yourself.

**Comment by anshul-j** [comment]
I tried with c-ares 1.15.0 version.Getting the below errors after running the make command

$ make
        make  all-recursive
  CC       ahost-ahost.o
  CC       ahost-ares_getopt.o
  CC       ahost-ares_nowarn.o
  CC       ahost-ares_strcasecmp.o
make: Cannot find a rule to create target ./libcares.la from dependencies.
Stop.
make: The error code from the last command is 1.

Stop.
make: The error code from the last command is 2.

**Comment by bagder** [comment]
@anshul-j why 1.15.0? The latest release is 1.16.1!

**Comment by anshul-j** [comment]
I have tried compiling c-ares 1.16.1 also. getting the similar errors as c-ares 1.15.0 

$ make
        make  all-recursive
  CC       ahost-ahost.o
  CC       ahost-ares_getopt.o
  CC       ahost-ares_nowarn.o
  CC       ahost-ares_strcasecmp.o
make: Cannot find a rule to create target ./libcares.la from dependencies.
Stop.
make: The error code from the last command is 1.
Stop.
make: The error code from the last command is 2.

**Comment by dfandrich** [comment]
Please open a new bug for a new issue.

**Comment by anshul-j** [comment]
i have opened a new bug 369
