### ISSUE TITLE
Cannot parse TTL of a CNAME query

### ISSUE THREAD

**Issue by saghul** [c-ares/c-ares#238]
I'm unable to parse the TTL for a CNAME query, while using `ares_parse_a_reply`. I'm passing all fields: `host`, `addrttls` and `naddrttls`, but `naddrttls` always comes up as 0.

I **think** the issue is because when parsing CNAME queries, `naddrs` is not incremented. That's only done here, for A queries: https://github.com/c-ares/c-ares/blob/b68880542360484368b49eca9dc6145318eb6b28/ares_parse_a_reply.c#L172 Thus here, when filling the `addrttls` structure, `n` will always be zero: https://github.com/c-ares/c-ares/blob/b68880542360484368b49eca9dc6145318eb6b28/ares_parse_a_reply.c#L217

Is this analysis correct? If so, I'd say the code needs to branch out again further down, and fill just the first addrttls structure's ttl field in the CNAME case. Does this make sense? I can try to cook up a patch if this is the correct way forward.

**Comment by ki11roy** [comment]
I am not a maintainer, but I think it is by design, because
```
struct ares_addrttl {
  struct in_addr ipaddr;
  int            ttl;
};
```
for some reason contains **ipaddr** and CNAME doesn't have it.

There is a test on the case:
```
TEST_F(LibraryTest, ParseAReplyJustCname) {
  DNSPacket pkt;
  pkt.set_qid(6366).set_rd().set_ra()
    .add_question(new DNSQuestion("mit.edu", ns_t_a))
    .add_answer(new DNSCnameRR("mit.edu", 52, "other.mit.edu"));
  struct hostent *host = nullptr;
  struct ares_addrttl info[2];
  int count = 2;
  std::vector<byte> data = pkt.data();
  EXPECT_EQ(ARES_SUCCESS, ares_parse_a_reply(data.data(), data.size(),
                                             &host, info, &count));
  EXPECT_EQ(0, count);
  ASSERT_NE(nullptr, host);
  std::stringstream ss;
  ss << HostEnt(host);
  EXPECT_EQ("{'other.mit.edu' aliases=[mit.edu] addrs=[]}", ss.str());
  ares_free_hostent(host);
}
```

**Comment by ki11roy** [comment]
@saghul or combine ares_addrttl and ares_addr6ttl into something like ares_ttl and mix in canonname:
```
struct ares_ttl {
  int            ttl;
  union {
    struct in_addr       addr4;
    struct ares_in6_addr addr6;
  } addr;
  char *canonname;  /* you will need ares_free canonname after use */
};
```
and then patch ares_parse_a/aaaa to populate the ttls. This will break compatibility with previous versions, regretfully.

I'd personally for adding ttl into ares_addrinfo and a separate function like ares__parse_into_addrinfo instead of ares_parse_a/aaaa as they are almost identical.

**Comment by saghul** [comment]
IIRC c-ares takes ABI compatibility very strictly, hence my suggestion to go with something which wouldn't break that.

Thanks for the advice though!

**Comment by bradh352** [comment]
Should be supported as of #257 with the ares_addrinfo supporting ttls for cnames
