### ISSUE TITLE
ares_getaddrinfo - infinite loop in case of NXDOMAIN

### ISSUE THREAD

**Issue by aergistal** [c-ares/c-ares#240]
Hello,
I'm aware this is still in development but I noticed there's a problem with queries involving invalid domain names which result in the same request being re-sent in a loop. The problem seems to be in [host_callback](https://github.com/c-ares/c-ares/blob/b68880542360484368b49eca9dc6145318eb6b28/ares_getaddrinfo.c#L362).

**Comment by kedixa** [comment]
I think the problem may be in [next_dns_lookup](https://github.com/c-ares/c-ares/blob/c7ab5f9149ea8c589dd4c768dc990eca66dd5ab8/ares_getaddrinfo.c#L283)
```cpp
  if (( as_is_first(hquery) && hquery->next_domain == 0) ||
      (!as_is_first(hquery) && hquery->next_domain ==
       hquery->channel->ndomains)) {
    s = hquery->name;
  }
```

Suppose the query meet `as_is_first` but not found, the `if` condition is always true but it don't know when to stop; or if it is not `as_is_first`, it will try each domain and then the `if` condition still always be true.

**Comment by bradh352** [comment]
thanks! should be merged
