### ISSUE TITLE
CMake build system - generate and install PDBs on Windows

### ISSUE THREAD

**Issue by ppietrasa** [c-ares/c-ares#245]
Hi, 

It would be nice if you produced and installed the debug symbols (*.pdb) on Windows builds. At least for CMAKE_BUILD_TYPE "Debug" and "RelWithDebInfo". 
This helps to avoid warnings like  "warning LNK4099: PDB 'vc140.pdb' was not found"  when linking to c_ares from an own project.

To produce the debug symbols for the shared library I did this:
```patch
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -569,6 +569,8 @@ IF (CARES_SHARED)
 »······SET_TARGET_PROPERTIES (${PROJECT_NAME} PROPERTIES
 »······»·······EXPORT_NAME cares
 »······»·······OUTPUT_NAME cares
+»······»·······COMPILE_PDB_NAME cares
+»······»·······COMPILE_PDB_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
 »······»·······VERSION     "${CARES_LIB_VERSION_MAJOR}.${CARES_LIB_VERSION_MINOR}.${CARES_LIB_VERSION_RELEASE}"
 »······»·······SOVERSION   "${CARES_LIB_VERSION_MAJOR}"
 »······)
@@ -584,6 +586,9 @@ IF (CARES_SHARED)
 »······»·······INSTALL (TARGETS ${PROJECT_NAME} EXPORT ${PROJECT_NAME}-targets
 »······»·······»·······${TARGETS_INST_DEST}
 »······»·······)
+»······»·······INSTALL(FILES ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/cares.pdb
+»······»·······»·······DESTINATION ${CMAKE_INSTALL_BINDIR} OPTIONAL
+»······»·······)
 »······ENDIF ()
 »······SET (STATIC_SUFFIX "_static")
```

One could proceed similarly for the static library.

Regards,
Piotr

**Comment by wrowe** [comment]
Piotr, are you using a very recent flavor of CMake? It was my impression that it has gained some self-awareness of .pdb files for .dll's, even if .pdb files still aren't carried for static .lib's.

**Comment by ppietrasa** [comment]
Hello William,

At the time of creating this ticket I used CMake v3.12.3.

Piotr
