### ISSUE TITLE
ares_getaddrinfo does not callback when domain name is bad

### ISSUE THREAD

**Issue by kedixa** [c-ares/c-ares#248]
- Problem
  When query a bad domain name such as ".com", "a.onion", or very long names, `ares_getaddrinfo` does not callback. This does not seem to be harmful, but if we put a context pointer to `ares_getaddrinfo`'s `void *arg`, there maybe memory leak.

- Possible solution
In file `ares_getaddrinfo.c` function `next_dns_lookup`
```c
ares_query(hquery->channel, s, C_IN, T_A, host_callback, hquery);
hquery->remaining++;
```
the `remaining++` is after `ares_query`, but if ares_query failed and call `host_callback`, `remaining` will be decrement by 1 and in an invalid state, cause no one to call `end_hquery`. I think change the order of the two lines will solve this problem, but I'm not sure.

**Comment by bradh352** [comment]
Fixed by #249
