### ISSUE TITLE
Application Verifier exception due to not calling WSAStartup

### ISSUE THREAD

**Issue by geraldcombs** [c-ares/c-ares#250]
We recently encountered an Application Verifier exception in Wireshark that appears to be caused by c-ares not calling WSAStartup() and WSACleanup(): https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=15711

I can reproduce this in a c-ares build directory by doing the following:

* Build c-ares in Visual Studio.
* In Application Verifier:
  * Add ahost.exe
  * Check the "Networking" checkbox
* In Visual Studio:
  * Right-click on the "ahost" project
  * Select "Properties"
  * Go to "Configuration Properties" → "Debugging" → "Command Arguments"
  * Add "-t a www.google.com" to "Command Arguments"
  * Press "OK"
  * Right-click on the "ahost" project
  * Select "Debug" → "Start new instance"

I get an exception at the toolong() call at ares_init.c:1918. 

See also: #157

**Comment by bradh352** [comment]
What does your ares_config.h have USE_WINSOCK set to?

If you look at the code for ahost.c, it requires USE_WINSOCK be set to call WSAStartup().

Also, there are 3 build systems and multiple compilers that can be used on windows, you'll have to tell us what you're using to look into if the build system isn't setting something right.

**Comment by bradh352** [comment]
sorry, ares_setup.h defines USE_WINSOCK, need to know what HAVE_WINSOCK_H and HAVE_WINSOCK2_H are set to.

**Comment by geraldcombs** [comment]
I'm building using `cmake -G "Visual Studio 16 2019" -A x64`. ares_config.h contains:

```
/* Define to 1 if you have the windows.h header file. */
#define HAVE_WINDOWS_H

/* Define to 1 if you have the winsock2.h header file. */
#define HAVE_WINSOCK2_H

/* Define to 1 if you have the winsock.h header file. */
#define HAVE_WINSOCK_H

/* Define to 1 if you have the writev function. */
/* #undef HAVE_WRITEV */

/* Define to 1 if you have the ws2tcpip.h header file. */
#define HAVE_WS2TCPIP_H
```
After adding ahost.exe in Application Verifier and running ahost under a debugger, the Application Verifier log contains the following:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<avrf:logfile xmlns:avrf="Application Verifier">
	<avrf:logSession TimeStarted="2019-04-30 : 14:58:44" PID="9676" Version="2">
		<avrf:logEntry Time="2019-04-30 : 14:58:44" LayerName="Networking" StopCode="0xE107" Severity="Error">
			<avrf:message>A Winsock API was called before a successful WSAStartup() or after a balancing successful WSACleanup() call was made</avrf:message>
			<avrf:parameter1>0 - Last sucessfull WSAStartup call by this caller. Use dps to dump the stack if not NULL</avrf:parameter1>
			<avrf:parameter2>0 - Last sucessfull WSACleanup call by this caller. Use dps to dump the stack if not NULL</avrf:parameter2>
			<avrf:parameter3>1b9483435b0 - Last successful WSAStartup call in this process. Use dps to dump the stack if not NULL</avrf:parameter3>
			<avrf:parameter4>0 - Last sucessfull WSACleanup call in this process. Use dps to dump the stack if not NULL</avrf:parameter4>
			<avrf:stackTrace>
				<avrf:trace>vfnet!+7fff5e681553 ( @ 0)</avrf:trace>
				<avrf:trace>vfnet!+7fff5e689798 ( @ 0)</avrf:trace>
				<avrf:trace>cares!init_by_defaults+13b (C:\Development\c-ares\ares_init.c @ 1918)</avrf:trace>
				<avrf:trace>cares!ares_init_options+1a2 (C:\Development\c-ares\ares_init.c @ 218)</avrf:trace>
				<avrf:trace>ahost!main+1b4 (C:\Development\c-ares\ahost.c @ 118)</avrf:trace>
				<avrf:trace>ahost!__scrt_common_main_seh+10c (d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288)</avrf:trace>
				<avrf:trace>KERNEL32!BaseThreadInitThunk+14 ( @ 0)</avrf:trace>
				<avrf:trace>ntdll!RtlUserThreadStart+21 ( @ 0)</avrf:trace>
			</avrf:stackTrace>
		</avrf:logEntry>
	</avrf:logSession>
</avrf:logfile>
```

**Comment by bradh352** [comment]
Either this is a false positive, or at the least, misleading.

WSACleanup() is only ever called at the end of a successful run of ahost.c ... the c-ares library never calls WSAStartup() nor WSACleanup().

ahost.c calls WSAStartup() immediately upon start, its literally the first function executed in main().  WSACleanup() is the last function called in main() before returning 0. 

If there are issues with initializing c-ares or parsing command line options, WSACleanup() is never called.

I've never used Application Verifier, but auditing the code shows the code is correct.

**Comment by zhihaoy** [comment]
Figured out the root cause: AppVerifier believes that every process or DLL should load Winsock libraries into their own address spaces. In this case, if cares.dll wants to start using Winsock, it can either call `WSAStartup()` by itself, or export an init function that lets `ahost`'s `main` function to call. I think this is more or less AppVerifier's limitation.
