### ISSUE TITLE
Please supply linux `poll` integrated API instead of `select`

### ISSUE THREAD

**Issue by fooofei** [c-ares/c-ares#254]
Please supply linux `poll` integrated API instead of `select`.

As the select/fd_set has FD_SETSIZE limit,

the socket value of c-ares used maybe >1024, then 

the `select` will write array out of bounds, and cause stack corruption.

A blog list this `select` situation
https://sigquit.wordpress.com/2009/12/24/stack-corruption-improper-use-of-fd_set/ 

Appendix: The `select` integrated API group:
```
CARES_EXTERN int ares_fds(ares_channel channel,
                          fd_set *read_fds,
                          fd_set *write_fds);
CARES_EXTERN struct timeval *ares_timeout(ares_channel channel,
                                          struct timeval *maxtv,
                                          struct timeval *tv);
CARES_EXTERN void ares_process(ares_channel channel,
                               fd_set *read_fds,
                               fd_set *write_fds);
```

**Comment by dimbleby** [comment]
See `ares_getsock()` and `ares_process_fd()`

**Comment by bradh352** [comment]
Correct, what @dimbleby said, you'll find a bunch of implementations that extract the fds to use with things like epoll() and kqueue() as well using that method. Plus on some OS's (like Windows, oddly enough), you can use any file descriptor.  Its just the way most posix systems have implemented it that limits both the number of file descriptors and max value.
