### ISSUE TITLE
[Proposal] - Support to ALIAS/ ANAME

### ISSUE THREAD

**Issue by renanbastos93** [c-ares/c-ares#255]
I guess interesting to give us support in a resolver recursive to query types `ALIAS/ ANAME`.

ISSUE of reference in NodeJS -> https://github.com/nodejs/node/issues/27724

Do you agree with my suggestion?

**Comment by bradh352** [comment]
Reading the RFC, it seems that DNS servers that support this will do the resolution on the behalf of resolvers which do not support ANAME.  It seems like the only downside to not supporting this client-side is inability to validate DNSSEC which c-ares doesn't support anyhow.

Am I missing something?

So basically until c-ares supports DNSSEC

**Comment by renanbastos93** [comment]
@bradh352, Sorry I'll to try to explain again to you.

Based on [RFC](https://tools.ietf.org/html/draft-ietf-dnsop-aname-01), I believe that we need to implement in this lib support the ANAME/ ALIAS so we can implement this on NodeJS later. There is already a thread for nodejs.. link [#27724](https://github.com/nodejs/node/issues/27724)

How can I help you to implement this feature?

Also look
 > https://github.com/nodejs/node/issues/14713

see ya

**Comment by bradh352** [comment]
I understand you requested support for NodeJS, but I don't see a reason for *why* this is being requested or what functionality is being requested.  The recursive DNS server you're querying will re-lookup the ANAME record as per section 4 of of the RFC, so there are no Geotargeting issues already.

What is the *advantage* of this support in c-ares, or what are you trying to accomplish?  Are you just wanting to know if there was an ANAME in the chain like you can see via h_aliases for CNAME records?  Or are you expecting c-ares to automatically re-query when an ANAME is received?  Or something else all-together.

**Comment by bradh352** [comment]
By the way, I also see you linked this: https://ns1.com/knowledgebase/comparing-alias-and-cname-records

Its kind of funny, its just wrong.  It doesn't properly describe how a cname lookup works when you request it from your recursive dns server (I think they need to read RFC1034 3.6.2), and it doesn't take into account section 4 of the RFC you mentioned for ANAME resolution.  So if your request is derived based on reading that page, unfortunately, they have mislead you.

**Comment by renanbastos93** [comment]
Hey,
I understood wrong, sorry. A DNS resolver to qType ALIAS/ANAME has to be made in the server when is requested a qType A, AAAA.
