### ISSUE TITLE
Add TTL in ares_gethostbyname callback

### ISSUE THREAD

**Issue by crazyxy** [c-ares/c-ares#259]
We are using `ares_gethostbyname` to resolve host names to IP addresses and it works fine. Recently, we want to use record TTL to set DNS query interval in our client side. It looks like there are several options: `ares_query`, `ares_search`. We can use `ares_parse_a_reply` to get the TTL information from the DNS query response. 

But when using `ares_query` and `ares_search`, some optimizations in `ares_gethostbyname` are lost. For example, `fake_hostent` check.

Does the community consider adding TTL in `ares_gethostbyname` callback or adding a new API?

**Comment by ki11roy** [comment]
There is an idea of adding TTLs into ares_addrinfo, see discussion in #257 #238 and #232

**Comment by crazyxy** [comment]
> There is an idea of adding TTLs into ares_addrinfo, see discussion in #257 #238 and #232

What's the ETA of this feature?

**Comment by bradh352** [comment]
hopefully we can get it wrapped up this week, @k11roy has been a trooper :)

**Comment by crazyxy** [comment]
Hi @ki11roy @bradh352, happy weekend! 😄 Is there any update on this issue?

**Comment by ki11roy** [comment]
@crazyxy I have updated the code in #257, the idea is to use ares_getaddrinfo to get all the IPv4/IPv6 info (with TTLs) in one function.

**Comment by crazyxy** [comment]
@ki11roy Thanks for updating!

**Comment by bradh352** [comment]
gethostbyname() will never add this support.  Please use ares_getaddrinfo() support as of #257 that adds this functionality.
