### ISSUE TITLE
Access denied finding property "net.dns1" when running VPN connection on Android

### ISSUE THREAD

**Issue by jhonnyking** [c-ares/c-ares#276]
I am debugging a client application that has reported a DNS issue when using 'tPacketCapture' in capture mode, that sets up a VPN connection to monitor the network traffic. In this mode, I get -1 on the udp socket in read_udp_packets in ares_process.c and if I run without the VPN connection, everything works fine. By comparing the logs between a good and a bad run, I see this line at a few places:

E/libc: Access denied finding property "net.dns1"

I have tried on three devices now, and it seems to fail on the two devices with android v8+. Older Android versions work as expected. I am building ares from 602aaec984f862a5d59c9eb022f4317954c53917.

The "access denied" may obviously not even come from ares itself, but it's the only thing from the log that I can see. Any help is greatly appreciated!

**Comment by beachcitiessoftware** [comment]
`net.dns1` is a system property, reading system properties from the NDK became deprecated and unsupported at 8 (possibly deprecated before that).  The newest version of c-ares has a workaround to get the search domain, and dns servers, from the proper supported location, using JNI, see https://github.com/c-ares/c-ares/blob/master/ares_android.h/c.

**Comment by bradh352** [comment]
manpage here https://c-ares.haxx.se/ares_library_init_android.html
