### ISSUE TITLE
Cut new release with ares_getaddrinfo?

### ISSUE THREAD

**Issue by mrostecki** [c-ares/c-ares#282]
Hi,

Envoy (https://github.com/envoyproxy/envoy) is using c-ares as a dependency and it relies in the `ares_getaddrinfo` functionality. Envoy already sticks to the latest commit which has the initial implementation and files, not to the release which don't have those changes:

https://github.com/envoyproxy/envoy/blob/master/bazel/repository_locations.bzl#L58

It seems like the following commits need to be included:

- f8cca0878de756b53445aca8d7e67c39cfcbcfb8
- 98857e30b702d76222f667f42027258b13c3f219
- 42fc7fa1cd078a4b772c977399feb8d7a7e8de79
- a9c2068e25a107bf535b1fc988eec47384b86dc6
- 602aaec984f862a5d59c9eb022f4317954c53917
- 4160535a2390e4305b385b6569eb75dca0753f90
- 7d3591ee8a1a63e7748e68e6d880bd1763a32885
- 33ed2aa6d13721b395d14cfdaafdb1f80bb05242

I'm packaging Envoy in openSUSE. We have a package with c-ares too and unlike Envoy upstream, we would like to link c-ares dynamically and use the released version instead of git snapshot.

(We might backport mentioned commits as a quick "fix", but for long term, we would prefer to stick just to upstream version. :) )

Would it be possible to cut of a release with `ares_getaddrinfo` now?

**Comment by bagder** [comment]
Also discussed on the mailing list a month ago: https://c-ares.haxx.se/mail/c-ares-archive-2019-09/0000.shtml

**Comment by mrostecki** [comment]
Good. I'm waiting for the next release. For now we just made a backport of `getaddrinfo` commits.

**Comment by bradh352** [comment]
The latest additions for getaddrinfo have just been committed, so we can probably start considering release prep soon.

**Comment by bagder** [comment]
We should make sure `RELEASE-NOTES` gets populated with the relevant updates and then set a date (to allow for people to do a final check) and then I can do the necessary key presses to actually get it out the door.

**Comment by bradh352** [comment]
I'm thinking its probably time.  We have an open PR on reworking getaddrinfo() but I think the current implementation is better

**Comment by bradh352** [comment]
looks like the release is imminent at this point.  Just getting a final review to make sure all is good :)

**Comment by bradh352** [comment]
released!
