### ISSUE TITLE
"ld: cannot find -lnsl" on Linux with Release configuration

### ISSUE THREAD

**Issue by hdnn** [c-ares/c-ares#284]
I built c-ares on Linux(WSL). It have generated c-ares-targets.cmake that have a little difference between Debug and Release build:
```
#Debug build:
set_target_properties(c-ares::cares PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CARES_STATICLIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "rt"
)
```
```
#Release build:
set_target_properties(c-ares::cares PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CARES_STATICLIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "nsl;rt"
)
```
As result, my project successfully built in Debug and with error on Link step in Release configuration:
**ld: cannot find -lnsl**
From the root CMakeLists.txt I can't understand what leads to a difference in behavior of generating c-ares-targets.cmake

**Comment by mellery451** [comment]
also related, what if I don't want to depend on `nsl` at all? If I link c-ares statically, I really don't want `-lnsl` at all. Would be nice to disable this library completely (even if installed).

**Comment by bradh352** [comment]
Closing to track under #307 which appears to be the underlying cause.
