### ISSUE TITLE
try_compile()s in CMakeLists.txt take a long time

### ISSUE THREAD

**Issue by KyleFromKitware** [c-ares/c-ares#287]
During discussion of grpc/grpc#21060, we found that c-ares is performing a lot of `try_compile()`s, which is slowing down the configure time. Some of these results aren't even being used at all (for example, a grep for `HAVE_MEMORY_H` shows that it isn't used anywhere except in the config header.) Others can probably be optimized out - for example, if `_WIN32` is `#define`d, it's probably safe to assume that `windows.h` and `winsock2.h` exist.

**Comment by KyleFromKitware** [comment]
Cc: @mathstuf @jtattermusch

**Comment by mathstuf** [comment]
Autotools should get the same removals as CMake.

**Comment by bradh352** [comment]
If you submit a PR for legacy unused tests in the autotools or CMakeLists we'll definitely look at it.  That said, on our testing, CMake only takes a couple of seconds to run through on Windows the way it is (autotools is a different story), so it would seem like there is something wrong with your build system.  I wouldn't consider this an issue...

**Comment by mathstuf** [comment]
> CMake only takes a couple of seconds to run through on Windows the way it is

How are you running it? Is it a reconfigure or a from-scratch configure that takes a few seconds?

**Comment by bradh352** [comment]
From-scratch

cmake -G "Ninja"

**Comment by mathstuf** [comment]
Ah, that could explain a lot of the difference. I believe the GRPC timings are using Visual Studio. @KyleFromKitware has timings from a run he did for grpc; could you upload them @KyleFromKitware?

**Comment by KyleFromKitware** [comment]
Visual Studio only: 2:33
Ninja + Visual Studio: 0:56
Ninja + MinGW: 0:45

The vast majority of this time in all cases is spent in the c-ares subdirectory. Even with Ninja + MinGW, it still takes longer than it should.

What version of Windows are you guys using? I am using 10 and seeing these slow configure times.

**Comment by bradh352** [comment]
That timing doesn't sound unreasonable, mine is about half that but I'm on a brand new EPYC Rome system with NVMe disks, and testing using Windows Server 2019 with MinGW and Ninja.  I don't believe we are willing to do any sort of tuning for what you are seeing, especially since the risk of breaking things could be high and very unlikely that you'd see a large benefit.  Windows is just slow when it comes to spawning processes, it is what it is.

**Comment by KyleFromKitware** [comment]
> the risk of breaking things could be high

Sure, but there are some checks that are not used *anywhere* in the code that could be safely removed. For example, a grep for `HAVE_MEMORY_H` reveals that the result of the check is not used anywhere in the code - it is only present in `CMakeLists.txt`, `acinclude.m4`, and `ares_config.h.cmake`. There are a number of others as well. Would you be willing to accept a patch that removed these?

**Comment by bradh352** [comment]
yes
