### ISSUE TITLE
service cannot be 0 in ares_getaddrinfo

### ISSUE THREAD

**Issue by yangboyd** [c-ares/c-ares#295]
Linux getaddrinfo can have 0 service

**Comment by bradh352** [comment]
are you talking the servname parameter?  And by 0 do you mean NULL?  As that is definitely tested and working. If you mean something else, please elaborate.

**Comment by yangboyd** [comment]
> are you talking the servname parameter? And by 0 do you mean NULL? As that is definitely tested and working. If you mean something else, please elaborate.

Sorry, I mean "0" char.
This line : port = (unsigned short)strtoul(service, NULL, 0);
return zero port.
Thanks!

**Comment by bradh352** [comment]
That should work if the hints.ai_flags = ARES_AI_NUMERICSERV
