### ISSUE TITLE
Any lock need for the list insert/remove to avoid crash ?

### ISSUE THREAD

**Issue by yangboyd** [c-ares/c-ares#298]
Find crashes related to  queries_by_timeout  and queries_to_server.

    ares__remove_from_list(&(query->queries_by_timeout));
    ares__insert_in_list(
        &(query->queries_by_timeout),
        &(channel->queries_by_timeout[query->timeout.tv_sec %
                                      ARES_TIMEOUT_TABLE_SIZE]));

    /* Keep track of queries bucketed by server, so we can process server
     * errors quickly.
     */
    ares__remove_from_list(&(query->queries_to_server));
    ares__insert_in_list(&(query->queries_to_server),
                         &(server->queries_to_server));

**Comment by dimbleby** [comment]
https://github.com/c-ares/c-ares/issues/208
