### ISSUE TITLE
channel: re-resolved servers under certain circumstances

### ISSUE THREAD

**Issue by junr03** [c-ares/c-ares#301]
Right now a channel's servers do not get updated after initialization. There are certain circumstances under which it would be useful to have c-ares functions re-resolved the channel's servers. For example, https://github.com/envoyproxy/envoy/issues/4543#issuecomment-580915046. This PR started on the right track: https://github.com/c-ares/c-ares/pull/272.

**Comment by sterchelen** [comment]
Hey, 
I'm working on re-using the PR #272 to implement a `reinit` function.
The idea is on the `ares_gethostbyname` fct, call a new fct named `is_ares_reinit_necessary`. Based on the result, calling `ares_reinit`.

Basically, `is_ares_reinit_necessary` would allow to implement platform specific scenarios to trigger a reinit... 
- Is the resolv.conf file has changed?
-

**Comment by bradh352** [comment]
fixed in #614
