### ISSUE TITLE
cmake: do not link with nsl, socket, rt unconditionally

### ISSUE THREAD

**Issue by sergepetrenko** [c-ares/c-ares#307]
CMake behavior differs from the configure one. Some libraries, that are not actually needed, are still linked against. 

This happens because the cmake script adds resolv, nsl, socket and rt unconditionally,
if they're available.
https://github.com/c-ares/c-ares/blob/master/CMakeLists.txt#L198-L209

Let's compare c-ares default libs when compiling with the configure
script and CMake on my system (I have the new libnsl installed):

Configure:
>  $ ./buildconf && ./configure && make -j
>  $ ldd lib/libcares.so
>  	linux-vdso.so.1 (0x00007ffeaa77b000)
>  	libc.so.6 => /lib64/libc.so.6 (0x00007fc0ae12c000)
>  	/lib64/ld-linux-x86-64.so.2 (0x00007fc0ae34a000)

CMake:
>  $ cmake . && make -j
>  $ ldd lib/libcares.so
>  	linux-vdso.so.1 (0x00007ffceebd6000)
>  	libnsl.so.2 => /usr/lib64/libnsl.so.2 (0x00007f98321cf000)
>  	librt.so.1 => /lib64/librt.so.1 (0x00007f98321c5000)
>  	libc.so.6 => /lib64/libc.so.6 (0x00007f9831ff3000)
>  	libtirpc.so.3 => /lib64/libtirpc.so.3 (0x00007f9831dc8000)
>  	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9831da5000)
>  	/lib64/ld-linux-x86-64.so.2 (0x00007f983243a000)

Side notes:
 * -lnsl is not added by ./configure if gethostbyname() is available w/o it:
 * It looks like `-lrt` is added only for the sake of `clock_gettime()`. However, starting with glibc 2.17 `clock_gettime()` is available in libc.so.
(Judging by `man 2 clock_gettime`):
>  Link with -lrt (only for glibc versions before 2.17).
 * Same problem is reported [here](https://github.com/c-ares/c-ares/issues/284#issuecomment-573214200)

**Comment by bradh352** [comment]
It doesn't look unconditional to me as per 
https://github.com/c-ares/c-ares/blob/master/CMakeLists.txt#L126-L132

`libnsl` will be included only if 'gethostbyname()' is in there (though I'm not sure why gethostbyname existence would be relevant to c-ares).
`librt` will only be included if `clock_gettime()` is in there
`libsocket` will be included if `gethostbyname()` or `socket()` is in there

I could definitely see an argument that relying on `gethostbyname()` doesn't make sense to link in its supporting library, and I'm not sure why that check exists.  My guess is really that check should have been `inet_pton()` or something.  That said, it seems to be consistent with the autotools check:
https://github.com/c-ares/c-ares/blob/master/configure.ac#L214-L232

You stated autotools doesn't actually include those libraries (I haven't check myself), so I'm not sure why that may be unless the CMake `CHECK_LIBRARY_EXISTS()` doesn't check exclusively for existence of the function in the library but instead will return a false positive if its also in the main `libc`

**Comment by Totktonada** [comment]
The key point is that a build system should not add `-lfoo` if all necessary symbols from `foo` are provided by libc. For example, it should check `clock_gettime()` availability w/o librt first and only then try the same with librt.

> That said, it seems to be consistent with the autotools check:
> https://github.com/c-ares/c-ares/blob/master/configure.ac#L214-L232

It checks `gethostname()` w/o any libs first, then with `-lnsl`, then with other libraries. This logic is right. No, cmake behaves differently.

**Comment by bradh352** [comment]
Does #310 fix your issue ?

**Comment by Totktonada** [comment]
In short: mostly yes, but there is a difference with libresolv on Mac OS.

See below for results of testing.

### Linux

Gentoo Linux, glibc-2.30-r3, separated libnsl is installed.

`master` branch (e0517f97d98845e2f56a43ba6ae2bbf339b5a3b0):

```
$ git clean -xfd; git submodule foreach --recursive 'git clean -xfd'
$ ./buildconf && ./configure && make -j
$ ldd .libs/libcares.so
	linux-vdso.so.1 (0x00007ffea6da3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7d10999000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7d10bb7000)
$ git clean -xfd; git submodule foreach --recursive 'git clean -xfd'
$ cmake . && make -j
$ ldd lib64/libcares.so
	linux-vdso.so.1 (0x00007ffd633ee000)
	libnsl.so.2 => /usr/lib64/libnsl.so.2 (0x00007ff7b6c80000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff7b6c76000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff7b6aa4000)
	libtirpc.so.3 => /lib64/libtirpc.so.3 (0x00007ff7b6a7b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff7b6a58000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff7b6eeb000)
```

`bradh352:cmake-libcheck` branch (77d602a384f18887f47de45f917a5fd437f9fb10):

```
$ git clean -xfd; git submodule foreach --recursive 'git clean -xfd'
$ ./buildconf && ./configure && make -j
$ ldd .libs/libcares.so
	linux-vdso.so.1 (0x00007ffc94d7d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f37d71ed000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f37d740b000)
$ git clean -xfd; git submodule foreach --recursive 'git clean -xfd'
$ cmake . && make -j
$ ldd lib64/libcares.so
	linux-vdso.so.1 (0x00007ffe165dc000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8364c3c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8364e61000)
```

After the patch autotools and cmake builds links the same libraries on my Linux host.

### Mac OS

I don't know much about this Mac OS host, but it reports the following version:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

`master` branch (e0517f97d98845e2f56a43ba6ae2bbf339b5a3b0):

```
<autotools>
$ otool -L .libs/libcares.2.dylib 
.libs/libcares.2.dylib:
	/usr/local/lib/libcares.2.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
<cmake>
$ otool -L lib/libcares.2.dylib 
lib/libcares.2.dylib:
	@rpath/libcares.2.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```

`bradh352:cmake-libcheck` branch (77d602a384f18887f47de45f917a5fd437f9fb10):

```
<autotools>
$ otool -L .libs/libcares.2.dylib 
.libs/libcares.2.dylib:
	/usr/local/lib/libcares.2.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
<cmake>
$ otool -L lib/libcares.2.dylib 
lib/libcares.2.dylib:
	@rpath/libcares.2.dylib (compatibility version 2.0.0, current version 2.3.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
```

On Mac there is still difference between autotools and cmake build: the latter has libresolv. Based on affc63cba875df11daade6f6767cb06e013ac6c3 I would guess that it should not be so: we should enable linking and usage of libresolv only on iPhone target (or change configure.ac to use it when available). No consistency here.

### FreeBSD

I use the following Vagrant box: `freebsd/FreeBSD-12.1-PRERELEASE`.

`master` branch (e0517f97d98845e2f56a43ba6ae2bbf339b5a3b0):

```
<autotools>
% ldd .libs/libcares.so
.libs/libcares.so:
	libc.so.7 => /lib/libc.so.7 (0x80024a000)
<cmake>
% ldd lib/libcares.so
lib/libcares.so:
	librt.so.1 => /usr/lib/librt.so.1 (0x80068a000)
	libc.so.7 => /lib/libc.so.7 (0x80024a000)
	libthr.so.3 => /lib/libthr.so.3 (0x800692000)
```

`bradh352:cmake-libcheck` branch (77d602a384f18887f47de45f917a5fd437f9fb10):

```
<autotools>
% ldd .libs/libcares.so
.libs/libcares.so:
	libc.so.7 => /lib/libc.so.7 (0x80024a000)
% ldd lib/libcares.so
lib/libcares.so:
	libc.so.7 => /lib/libc.so.7 (0x80024a000)
```

So after the patch the difference in linked libraries is gone.

### Side notes

I see the following comment in configure.ac:

```
233 dnl At least one system has been identified to require BOTH nsl and socket
234 dnl libs at the same time to link properly.
```

I don't have such system (is it Solaris?), so cannot check this aspect. Maybe it should be handled in CMake too (this however would not affect our project -- tarantool).

**Comment by bradh352** [comment]
I'd actually venture to say cmake is now more correct considering `/etc/resolv.conf` on MacOS these days says:
`#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#`

So it might be better to fix autotools to not only do that check on iOS.
