### ISSUE TITLE
Will you accept adding iocp for windows

### ISSUE THREAD

**Issue by some-coder366** [c-ares/c-ares#308]
I wanted to integrate this library with my async library which uses io completion ports on windows, but here select is used instead .

the current model of this library fits very well for select, poll, epoll and similars (WSAPoll ?) but not for completion based notification like iocp and io_uring.

As it wasn't suitable to polling in iocp loop I had two choices :
1 - create a new thread which will poll for the dns resolver and post results to the main io loop
2 - hack the library in order to add iocp support

The first is very trivial and easy (probably better than the second), but I wanted to do it the other way .

I ended up with something like this for now : 

```
HANDLE hIocp = nullptr;
bool ExitLoop = false;

void state_cb(void* data, ares_socket_t sockfd, int readable, int writable)
{
	printf("state changed : %d read fds, %d write fds\n", readable, writable);
}

void resolve_callback(void* arg, int status, int timeouts, struct hostent* host)
{

	if (!host || status != ARES_SUCCESS) {
		printf("Failed to lookup %d : %s\n", status, ares_strerror(status));
		ExitLoop = true;
		return;
	}

	printf("Found address name %s\n", host->h_name);
	char ip[INET6_ADDRSTRLEN];
	int i = 0;

	for (i = 0; host->h_addr_list[i]; ++i) {
		inet_ntop(host->h_addrtype, host->h_addr_list[i], ip, sizeof(ip));
		printf("%s\n", ip);
	}
	ExitLoop = true;
}

void IocpLoop(ares_channel channel)
{

	ares_socket_t sockfd;
	ares_getsock(channel, &sockfd, 1);

	constexpr DWORD ovs_num = 100;
	OVERLAPPED_ENTRY ovs[ovs_num];
	
	while (!ExitLoop)
	{
		fd_set fds;
		DWORD num;
		if (!GetQueuedCompletionStatusEx(hIocp, ovs, ovs_num, &num, INFINITE, FALSE))
		{
			cout << "[!] GetQueuedCompletionStatusEx failed with error " << GetLastError() << endl;
			return;
		}

		if (num != 1)
		{
			cout << "[!] got more than one completion, although there is only one socket in the channel !";
			return;
		}

		cout << "[*] popped a completion entry" << endl;

		ares_process_fd_ov(channel, sockfd, ARES_SOCKET_BAD, ovs[0].lpOverlapped);
	}

}

int main()
{
	int iResult;
	WSADATA wsaData;
	iResult = WSAStartup(MAKEWORD(2, 2), &wsaData);
	if (iResult != 0) {
		std::cout << "WSAStartup failed: " << iResult << std::endl;
		return 0;
	}

	hIocp = CreateIoCompletionPort(INVALID_HANDLE_VALUE, nullptr, 0, 4);
	if (!hIocp)
	{
		printf_s("[test] CreateIoCompletionPort failed with error %d\n", GetLastError());
	}

	int rc = ares_library_init(ARES_LIB_INIT_ALL);
	if (rc != ARES_SUCCESS)
	{
		printf("[!] %s failed with error %d : %s", "ares_library_init", rc, ares_strerror(rc));
		return 0;
	}

	ares_channel channel;
	ares_options options;
	
	options.sock_state_cb = state_cb;
	options.sock_state_cb_data = &channel;
	options.iocp_handle = hIocp;

	int optmask = 0;
	optmask |= ARES_OPT_SOCK_STATE_CB | ARES_OPT_IOCP;

	rc = ares_init_options(&channel, &options, optmask);
	if (rc != ARES_SUCCESS)
	{
		printf("[!] %s failed with error %d : %s", "ares_init_options", rc, ares_strerror(rc));
		return 0;
	}

	OVERLAPPED ov;
	std::memset(&ov, 0, sizeof(ov));
	ares_gethostbyname_ov(channel, "www.google.com", AF_INET, resolve_callback, nullptr, &ov);
	IocpLoop(channel);

	getchar();
	return 0;
}
```

The changes were mainly in `ares_process.c` and aren't that huge .

Do you have any intention integrating this into the library or I'd rather create a fork with this patch ?

**Comment by bradh352** [comment]
If you can submit a PR that

1) Adds your desired functionality
2) Does not break ABI or API compatibility for existing integrations
3) Is generic enough so that it can be leveraged cross-platform (for those platforms that support concepts like io_uring and IOCP)
4) Includes man pages necessary for developers to implement said functionality
5) Adds test cases to test functionality to the test framework

Then I don't see why we wouldn't accept such patches.

**Comment by onanur993** [comment]
@some-coder366 Will you do it?

**Comment by bradh352** [comment]
I have a feeling #696 will alleviate the need for this since you wouldn't need to integrate this with your own even loop.  Technically on Windows, #696 uses IOCP (just maybe not in the way you'd think).

**Comment by bradh352** [comment]
I'm closing this as I think #696 might solve this, and if not, it at least shows how to integrate event based notifications on windows with IOCP using the undocumented AFD_POLL stuff.
