### ISSUE TITLE
DNS resolution fails in virtualbox with NAT adapter

### ISSUE THREAD

**Issue by IIFE** [c-ares/c-ares#318]
Hi,

I am using `gRPC` to create a C# server and C++ client. `gRPC` appears to use `c-ares` to carry out the DNS resolution. DNS resolution seems to fails with the following setup:
- Create VirtualBox Windows 10 VM.
- Use NAT for network adapter.
- Run server inside VM.
- Create C++ client inside VM.
- Connect to server **using machine name**. This is important. Not using `localhost` or an IP, just the machine name.

The observed behaviour is that I get DNS resolution failure. The gRPC logs have the following line:

```
I0330 16:12:52.559000000  2600 completion_queue.cc:706] cq_end_op_for_next(cq=0E848088, tag=0EA320E8, error={"created":"@1585581172.559000000","description":"Failed to pick subchannel","file":"vcpkg\buildtrees\grpc\src\v1.27.1-e5ac019672\src\core\ext\filters\client_channel\client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1585581172.558000000","description":"Resolver transient failure","file":"vcpkg\buildtrees\grpc\src\v1.27.1-e5ac019672\src\core\ext\filters\client_channel\resolving_lb_policy.cc","file_line":262,"referenced_errors":[{"created":"@1585581172.558000000","description":"DNS resolution failed","file":"vcpkg\buildtrees\grpc\src\v1.27.1-e5ac019672\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc","file_line":370,"grpc_status":14,"referenced_errors":[{"created":"@1585581172.558000000","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"vcpkg\buildtrees\grpc\src\v1.27.1-e5ac019672\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":244,"referenced_errors":[{"created":"@1585581172.557000000","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"vcpkg\buildtrees\grpc\src\v1.27.1-e5ac019672\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":244}]}]}]}]}, done=51831F20, done_arg=0EA32530, storage=0EA32554)
```

Which indicates that `c-ares` failed to resolve the provided host.

[This comment](https://github.com/grpc/grpc/issues/18290#issuecomment-480770740) in a gRPC issue appears to say that `c-ares` is not catering for DNS suffix. Any idea if that is the actual issue, or if something else is causing it? The issue does not occur if I switch VirtualBox network adapter to Bridged.

Thanks.

**Comment by IIFE** [comment]
@bradh352 Thanks for the reply, much appreciated.

How do I check if the machine name is registered with a DNS server?

If I run `nslookup <machine name>` when my VM is using a `NAT` adapter, then I get the following output format:

```
Server:  <domain controller name>.<suffix>
Address:  xx.xxx.xxx.xx

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to <domain controller name>.<suffix> timed-out
```

However, if I run the same command with `Bridged` adapter, then the following output format comes up:
```
Server:  dsldevice.lan
Address:  xxx.xxx.x.xxx

Name:    <machine name>.lan
Addresses:  xxx.xxx.x.xx
          xxx.xxx.x.xx
          xxx.xxx.x.xx
```

The interesting thing is if I tell `gRPC` to use the `native` DNS resolution, which on Windows it uses `getaddrinfo`, then DNS resolution does not fail even on `NAT` adapter.

Is `getaddrinfo` handling NetBIOS/WINS name lookups that `c-ares` does not support?

Thanks.

**Comment by bradh352** [comment]
If you try using <machine name>.lan  instead of just <machine name>, does it work with c-ares?  If so then it is a suffix issue.  What version of c-ares is being run?

Yes, Windows native DNS resolver does support NetBIOS/WINS lookups.

**Comment by IIFE** [comment]
@bradh352 If I understood you correctly I think you meant try connecting using <machine name>.lan? If that's the case, tried that and same error occurs.

Using version `2019-5-2-1` through `vcpkg`.

Are there any `c-ares` logs that can tell me the exact cause of the DNS resolution error, so that we can see if it's caused by NetBIOS/WINS lookups, or DNS suffix.

Thanks.

**Comment by bradh352** [comment]
I'm not familiar with what 2019-5-2-1 might refer to ... c-ares releases are like 1.15.0, 1.16.0 ... etc...

Hmm, looks like github removed my brackets ...

I had said
```
If you try using <machine name>.lan instead of just <machine name> does it work?
```

**Comment by IIFE** [comment]
@bradh352 Hmm for some reason that's what `vcpkg` uses for the version. Not sure how it's resolving the correct version to download the source. Will dig further.

Yes tried with `<machine name>.lan` while still on NAT adapter and still same issue.

**Comment by bradh352** [comment]
With c-ares does a bridge adapter work for this?  Are you saying that its only the NAT adapter?

**Comment by IIFE** [comment]
@bradh352 Yes only if the NAT adapter is used in VirtualBox, or if I use nested virtualization in Azure (i.e. Azure VM with Hyper-V image running inside). The VirtualBox is a simpler setup to replicate the issue.

**Comment by bradh352** [comment]
Oh, ok ... Yeah, this isn't a c-ares issue.  I just noticed you showed that the built-in Windows nslookup (which does not do WINS/NetBIOS) also has the same 'issue'.  C-ares just doesn't do WINS/NetBIOS so that explains it.  You should look into why your DNS in NAT isn't properly forwarding requests or whatever to your AD DNS server.  Once 'nslookup' works, c-ares should too...

**Comment by IIFE** [comment]
@bradh352 I wouldn't say it's not entirely a c-ares issue, especially because even with NAT the native DNS resolution works fine. So something different is happening if c-ares is used for DNS resolution instead of the native API.

I think it might be worth investigating the issue on a VirtualBox VM if possible.

**Comment by bradh352** [comment]
But you said the OS-provided nslookup command also failed ...

**Comment by IIFE** [comment]
The confusing part is the native DNS resolution (getaddrinfo) works.

So is it basically that in NAT NetBIOS/WINS is being used, which both c-ares and nslookup don't support, but getaddrinfo does?

**Comment by bradh352** [comment]
correct
