### ISSUE TITLE
c-ares not handling the dns server change properly

### ISSUE THREAD

**Issue by p-adhikari** [c-ares/c-ares#324]
I am facing an issue where after connecting to VPN, c-ares queries are not using the VPN DNS server and still using the local DNS server. My resolv.conf file is properly updated with VPN DNS but somehow c-ares is not picking that change.

I am using c-ares 1.11.0

**Comment by bradh352** [comment]
c-ares does not re-initialize on configuration changes.

You would need to run a new ares_init() on a new channel on such network changes and start using the new channel.

**Comment by p-adhikari** [comment]
Thanks for reply. 
I tried the fix but its not seems to be working. Here is what I have in pseudocode.

ares_channel    channel_;
ares_library_init(ARES_LIB_INIT_ALL);
ares_init_options(&channel_, &options, optmask); // options is set for timeout, lookups and retries


What I did to cleanup the channel based on config change event:

ares_destroy(channel_);
ares_library_cleanup();
ares_library_init(ARES_LIB_INIT_ALL);
ares_init_options(&channel_, &options, optmask); 


But this doesn't seems to be picking up the new dns server from resolv.conf.

Is something missing here or something I am doing wrong?

**Comment by bradh352** [comment]
You don't need to call library_cleanup and library_init for this.  But during ares_init is when resolv.conf is read.  There's no caching going on internally, I don't see how that wouldn't work.

**Comment by p-adhikari** [comment]
Is there is a difference between how resolv.conf is read by windows vs OSX?
I am seeing that the fix you proposed is working correctly on windows but not on OSX.

**Comment by bradh352** [comment]
Windows doesn't use resolv.conf, it uses a whole bunch of API lookups. 

Also, did you verify that /etc/resolv.conf is actually being updated on mac?  I think I remember hearing its considered a legacy way to get the nameservers on mac but I haven't looked into it.

**Comment by p-adhikari** [comment]
Yes, I can confirm that resolv.conf is getting updated correctly. I am not sure that is it a timing issue or what that probably when we are listening to the event and re-initing the new channel, it may not be updated.

About, "I think I remember hearing its considered a legacy way to get the nameservers on mac", is there is a solution to this ?

**Comment by bradh352** [comment]
Well MacOS still updates /etc/resolv.conf but I think the new way is to use the SystemConfiguration framework.  C-ares doesn't support this and relies on the legacy /etc/resolv.conf.  I don't know if there is any 'lag' in the OS updating /etc/resolv.conf vs what is visible via the SystemConfiguration.

**Comment by bradh352** [comment]
On closer look, on iOS we do not use /etc/resolv.conf but instead use res_ninit() / res_getservers() and friends from libresolv ... I've committed change baf6f4e to also use this on MacOS.  I don't see any downside.

I'm pretty sure these calls are wrappers for the SystemConfiguration framework.  Otherwise we'd have to do something like https://stackoverflow.com/a/34940848

**Comment by p-adhikari** [comment]
Thanks for the quick fix. 
So, as a test I will checkout master and build the lib.

Is there is an official release date in which we can expect the change to be included?

**Comment by bradh352** [comment]
No, unfortunately we just had a release ... and we seem to be doing them every 12 or so months at this point :/  We could do quicker if there was a real need but there hasn't been anything really major yet.

**Comment by p-adhikari** [comment]
Just to close on this, i picked the change in [baf6f4e](https://github.com/c-ares/c-ares/commit/baf6f4eb4240d6c8844f751570b3c151af263d93) but it didn't help.

I tried the solution mentioned in [envoyproxy/envoy#4543](https://github.com/envoyproxy/envoy/issues/4543#issuecomment-580915046) and it is working. I am still testing but initial tests are positive.

I also saw [c-ares/c-ares#272](https://github.com/c-ares/c-ares/pull/272) but as mentioned this is platform specific and not merged in master. @bradh352 Is there is any plan to fix the issue something like done in mentioned commit for all platforms?
