### ISSUE TITLE
cares asynchronous on dns server list

### ISSUE THREAD

**Issue by ZhuChasel** [c-ares/c-ares#340]
Dear, 
    when resolving more than one domain, cares support asynchronous query on all the domain.
    But as i known , the process for one domain on dns server list(for example 2 nservers) is  Synchronize， that is , 4s(my default timeout value) for the first node , then fail-over to the second server node. If I set tries to 2, then i need to spend 4s+4s+9s+9s almost. So, can cares support asynchronous query on all the dns sever node for one domain?

Thanks.

**Comment by bradh352** [comment]
I'd recommend ares_init_options() with ARES_OPT_TIMEOUTMS to reduce the timeouts.  It isn't recommended practice to run the same query in parallel as it puts unnecessary load on the upstream servers, so c-ares doesn't support this behavior.
