### ISSUE TITLE
Garbage in sin6_scope_id

### ISSUE THREAD

**Issue by SmorkalovG** [c-ares/c-ares#343]
Hello. I am using ares_getaddrinfo function to resolve google.com on Debian10.
The second node in result is IPv6 addres  and it sometimes contains random values in sin6_scope_id. Each resolve results with different values that cannot be real sin6_scope_id.  
If I understand c-ares code right, in function ares__readaddrinfo()  variable struct ares_sockaddr is not initialized and in case of AF_INET6 only two members are set: sin6_port and sin6_addr. But sin6_flowinfo and sin6_scope_id stays undefined. 
I added memset(&addr, 0, sizeof(addr)); to test and it helped. Now sin6_scope_id is always 0.  It does not pretend on full fix, because I do not know if there are other such places, but problem deffinetly exists.
There is same thing with AF_INET but with lesser problems. Padding array (called sin_zero in my version) in struct sockaddr_in stays undefined. I compared sockaddr_in structs whith simple memcmp and got diference for equal addresses. It is not a problem itself, nobody cares what is inside of padding, it is just the a result of same undefined state.

**Comment by bradh352** [comment]
your description makes sense, sounds like an easy fix

**Comment by bradh352** [comment]
fixed in bd215c4
