### ISSUE TITLE
Native support for libevent

### ISSUE THREAD

**Issue by mmehra** [c-ares/c-ares#347]
Is there any plan to add support for libevent, basically sockets returned can be added to event loop instead of select? Software which uses libevent / libev is forced to create a thread where select can run in parallel to event loop in the main thread. Can this thread creation be avoided?

There was some discussion back in 2006, however looks like the patch never made it to upstream.
https://c-ares.haxx.se/mail/c-ares-archive-2006-02/0003.shtml

**Comment by bagder** [comment]
Unless you use `ares_getsock`, which has allowed us to use c-ares with event based libraries since 2005.

**Comment by bradh352** [comment]
Right, ares_getsock along with ares_process_fd perfectly solve this issue.   You've just got to write the 'glue' code for the event library you are using.  I doubt we'd accept patches for specific event libraries.

**Comment by mmehra** [comment]
Thanks @bagder and @bradh352. Playing around with ares_process_fd.

In case of timeout, looks like application callback is invoked before freeing internal ares query structures

```
  /* Invoke the callback */
  query->callback(query->arg, status, query->timeouts, abuf, alen);
  ares__free_query(query);
```

If application `destroys` ares channel as a part of timeout callback, we run into `double free`. Looks like I need to start `zero` second timer and destroy ares channel as a part of that zero timer callback

**Comment by bradh352** [comment]
It is not supported to destroy the c-ares channel from within a callback, that is true.  However, why would you want to do this?  You should not be creating and destroying channels for each query ... the channel should be long-lived (typically the duration of your application ... or if you detected a network configuration change and need to reload configs).

**Comment by mmehra** [comment]
Sure. I went with creating/destroying channel whenever DNS query is fired/completed. ares_channel is anchored in application structure and is destroyed with object (when DNS succeeds/fails)

Let me rework on it as per your suggestion. Thanks
