### ISSUE TITLE
Makefile.netware broken with source tree reorganization

### ISSUE THREAD

**Issue by bradh352** [c-ares/c-ares#350]
I do not have access to a netware system to work on this.  It appears to have been originally maintained by @gknauf

If we do not have a maintainer for this, we'll simply remove it. I wouldn't be surprised if this target is no longer in active use.

The Makefile.m32 and Makefile.msvc changes might provide the best hints for modification.

**Comment by renodr** [comment]
I'm going to take a crack at this and see what I can come up with. If I manage to get something cooked up, I'll open a PR for it.

**Comment by renodr** [comment]
I have a working NetWare 6.5 SP8 system going, but can not find the Novell Development Kit. If anyone has a copy, please reach out to me and I can fix this one

**Comment by bradh352** [comment]
i'm going to go ahead and close this since netware has been eol for about a decade.  If someone really needs c-ares on an eol platform, they can use an older version :)
