### ISSUE TITLE
Makefile.dj (DJGPP, DOS) broken with source tree reorganization

### ISSUE THREAD

**Issue by bradh352** [c-ares/c-ares#351]
I do not have access to a DJGPP system to work on this. It appears to have been originally maintained by @gvanem

If we do not have a maintainer for this, we'll simply remove it.

The Makefile.m32 and Makefile.msvc changes might provide the best hints for modification.

**Comment by gvanem** [comment]
> If we do not have a maintainer for this, we'll simply remove it.

I'm working on a fix. Should be easy enough.

**Comment by bradh352** [comment]
Fixed in #355
