### ISSUE TITLE
Makefile.Watcom (WIN16?) broken with source tree reorganization

### ISSUE THREAD

**Issue by bradh352** [c-ares/c-ares#352]
I do not have access to a Watcom system to work on this. It appears to have been originally maintained by @gknauf

If we do not have a maintainer for this, we'll simply remove it.  I wouldn't be surprised if this target is no longer in active use.

The Makefile.m32 and Makefile.msvc changes might provide the best hints for modification.

**Comment by renodr** [comment]
I'm going to take a crack at this and see what I can come up with. If I manage to get something cooked up, I'll open a PR for it.

**Comment by renodr** [comment]
Over a year later, I finally got some time to take a look at this. With some minor modifications, I got the Makefile to build up to around 10 files in, but I'm having some problems with Winsock. I'll investigate further, might need to add #ifndef __WATCOMC__ in a couple places

**Comment by renodr** [comment]
Now that some more time has passed and things have changed a bit, it's time to take another look again.

Now that we exclusively support Windows Vista and higher, I'll start with a Windows Vista environment this time.
