### ISSUE TITLE
Resolving NS records against manual configured servers fails

### ISSUE THREAD

**Issue by iatpatelishan** [c-ares/c-ares#353]
Coming back from nodejs bug which seems like to be originated from usage of this library.

Please read https://github.com/nodejs/node/issues/33858 for the problem

**Comment by stjosh** [comment]
I think that's a no-bug. See my more detailed analysis of the original issue here: https://github.com/nodejs/node/issues/33858#issuecomment-759456635

**Comment by bradh352** [comment]
Please see my update on that ticket.  No bug here.
