### ISSUE TITLE
ares_getaddrinfo fails with ARES_EBADNAME when FQDN ends with dot '.'

### ISSUE THREAD

**Issue by lmarszal** [c-ares/c-ares#366]
Affected version: 1.16.1

When using `ares_getaddrinfo` in k8s app, when query `www.google.com.` I receive `ARES_EBADNAME` error. If I try `www.google.com` (no dot) it works fine.  
I believe the reason for that is incorrect handling of search domains in `ares_getaddrinfo` - I couldn't find any codepath in `ares_getaddrinfo` that would serve the same purpose as `ares__single_domain` from `ares_search.c`.

See reproduction of this bug here: https://github.com/lmarszal/getaddrinfo-repro/

This problem seems to be resolved by this commit: https://github.com/c-ares/c-ares/pull/345/commits/aebadb541fb4f0ecf12e9b9977e4417994b8b773 . My concern is, is that a sustainable fix or this issue requires more work?  
  
  
Side note about "what's special about resolv.conf of containers running in k8s" - it usually looks like this (see [this explanation](https://github.com/kubernetes/kubernetes/issues/33554#issuecomment-266251056) why):
```
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

**Comment by lmarszal** [comment]
Also - `ares_getaddrinfo` used to use `ares_search` under the hood, but it was replaced with custom implementation in this commit: https://github.com/c-ares/c-ares/commit/dbd4c441fb7babad5c56f455d720af38e20546bc

**Comment by bradh352** [comment]
ba59781 is the commit with a better description.  It *is* the fix for this exact case you're describing.

**Comment by lmarszal** [comment]
cool, thank you!
