### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by jbergstroem** [c-ares/c-ares#37]
Its been a good while since a version was released. Suggesting it'd be a good time to cut a new one? This allows nodejs to (optionally) link against it.

**Comment by bagder** [comment]
This is an issue tracker, I suggest taking subjects for a wider audience to the mailing list. And yeah, we've been discussing a new release since [January](http://c-ares.haxx.se/mail/c-ares-archive-2016-01/0001.shtml)...
