### ISSUE TITLE
c-ares 1.17.0 release package issues

### ISSUE THREAD

**Issue by brechtsanders** [c-ares/c-ares#373]
Building c-ares 1.17.0 from tarball c-ares-1.17.0.tar.gz fails because cmake can't find the following files:

- c-ares-config.cmake.in
- libcares.pc.cmake

I tried to build (with Ninja as build tool) with the following cmake command:
```
cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release -DCARES_SHARED:BOOL=ON -DCARES_STATIC:BOOL=ON
```

I have reproduced the issue both on Debian Linux as on Windows using MinGW-w64 GCC in MSYS2 shell.

This is the output:
```
CMake Error: File /home/brecht/_/c-ares-1.17.0/c-ares-config.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.13/Modules/CMakePackageConfigHelpers.cmake:316 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:606 (CONFIGURE_PACKAGE_CONFIG_FILE)


CMake Error: File /home/brecht/_/c-ares-1.17.0/libcares.pc.cmake does not exist.
CMake Error at CMakeLists.txt:623 (CONFIGURE_FILE):
  CONFIGURE_FILE Problem configuring file


-- Configuring incomplete, errors occurred!
```

**Comment by pghmcfc** [comment]
On the other hand, if I build with autotools I get an soname of libcares.so.0, whilst with CMake I get libcares.so.2, which is what I expected (this is on Fedora Linux).

**Comment by bradh352** [comment]
Looks like there were some issues related to packaging due to the code reorg.  We probably need to rethink the way the package is created as I don't see any reason to *exclude* anything that is in the github repo.  Regarding the soname for autotools, I'll need to look at that, probably also related to the code reorg.

**Comment by bradh352** [comment]
I have committed some changes to correct these issues.  I have also added an extra test for the travis distcheck build cycle to explicitly test the generated package for cmake (not just autotools).

Hopefully once travis finishes (which it is much slower the past couple of weeks), it will be good enough to quickly push out a 1.17.1

**Comment by bradh352** [comment]
@bagder FYI

**Comment by bagder** [comment]
Thanks Brad!

**Comment by bradh352** [comment]
The first build in Travis finished, which is the important one with the test of using the package with cmake.  So I think we're good.  No idea when Travis will be done however due to the way they've changed the build processes for free projects.

**Comment by bagder** [comment]
So we're all green and good for a patch release then @bradh352 ?

**Comment by bradh352** [comment]
Hah, not sure if you should leave that judgement to me, I thought we were fine last time :)
But as far as I know, yes.

**Comment by bradh352** [comment]
@bagder don't know if you want to handle #374 or not

**Comment by gjasny** [comment]
I also get bitten by the autotools soname change and would prefer a fast 1.17.1 release. For now I disable the tests which is no regression over 1.16. I could look into specifying a test filter in a later package revision.

**Comment by ffontaine** [comment]
There is an other packaging issue that is still present on master, c-ares does not  install ares_dns.h anymore resulting in the following build failure with resiprocate:

```
In file included from dns/DnsCnameRecord.cxx:7:
dns/AresCompat.hxx:5:10: fatal error: ares_dns.h: No such file or directory
 #include "ares_dns.h"
          ^~~~~~~~~~~~
```
Full build log: http://autobuild.buildroot.org/results/cbf/cbf158f0c037d44ef293a8804d18c84e3b731059/build-end.log

**Comment by ffontaine** [comment]
#376 fixes the issue with autotools, cmake should also be updated

**Comment by bradh352** [comment]
@ffontaine I'm not sure ares_dns.h is supposed to be a public header.  Is the project you're referencing actually using any of the macros contained in that header?  Or did it include the header by mistake.

**Comment by gjasny** [comment]
Resiprocate uses various `DNS_HEADER` macros: https://github.com/resiprocate/resiprocate/blob/master/rutil/dns/DnsStub.cxx#L195

The Debian packages also ship that header in the `-dev` package: https://packages.debian.org/bullseye/amd64/libc-ares-dev/filelist

**Comment by bradh352** [comment]
resiprocate is the only usage i could find as well.  We've already made the change to distribute it in master.

**Comment by bradh352** [comment]
@bagder anything else before you're comfortable pushing out 1.17.1 ?  Btw, saw you made the news ...

**Comment by renodr** [comment]
Greetings @bradh352 and @bagder ,

Are there any updates on this? At Linux From Scratch, we've been waiting for the new c-ares release to come out to fix the four security issues mentioned in [https://c-ares.haxx.se/changelog.html](url). The new version of Node.JS that we have should be done at the same time that we update c-ares since it's focus is fixing a c-ares issue and we use the system library for that package instead of the one bundled with node.js.

I hope you're both doing well today, and @bagder I saw you made the news and your tweet and I'm glad you got your twitter account back as fast as you did!

**Comment by bagder** [comment]
I aim to put together the 1.17.1 package in a few hours. I'll mention it here as well when done.

**Comment by bagder** [comment]
Okay, it's now packaged, signed, uploaded and emailed about. This issue is closed!

**Comment by karlp** [comment]
maybe I'm crazy, but where can I find the public key used to create the signatures? trying to verify this 1.17.1 download

**Comment by gjasny** [comment]
You could take that one as it is used by Debian:
https://salsa.debian.org/debian/c-ares/-/blob/master/debian/upstream/signing-key.asc

**Comment by bradh352** [comment]
great question.  @bagder does the signing, so I'd assume its his GPG key: https://daniel.haxx.se/mykey.asc  :)

**Comment by karlp** [comment]
Would be nice to get that linked somewhere obviously under c-ares.haxx.se please :)  it's not obviously linked on daniel.haxx.se either, even if you know to look there.  best I could find was keybase.
