### ISSUE TITLE
1.17.1:test suite is failing

### ISSUE THREAD

**Issue by kloczek** [c-ares/c-ares#379]
Looks like test suite is not ready to be build off the source tree.
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 -C x86_64-redhat-linux-gnu test ARGS=--output-on-failure
make: Entering directory '/home/tkloczko/rpmbuild/BUILD/c-ares-1.17.1/x86_64-redhat-linux-gnu'
Running tests...
/usr/bin/ctest --force-new-ctest-process --output-on-failure
Test project /home/tkloczko/rpmbuild/BUILD/c-ares-1.17.1/x86_64-redhat-linux-gnu
    Start 1: arestest
1/3 Test #1: arestest .........................   Passed   40.87 sec
    Start 2: aresfuzz
Failed to change working directory to /home/tkloczko/rpmbuild/BUILD/c-ares-1.17.1/test/fuzzinput : No such file or directory
2/3 Test #2: aresfuzz .........................***Not Run   0.00 sec
    Start 3: aresfuzzname
Failed to change working directory to /home/tkloczko/rpmbuild/BUILD/c-ares-1.17.1/test/fuzznames : No such file or directory
3/3 Test #3: aresfuzzname .....................***Not Run   0.00 sec

33% tests passed, 2 tests failed out of 3

Total Test time (real) =  40.87 sec

The following tests FAILED:
          2 - aresfuzz (Not Run)
          3 - aresfuzzname (Not Run)
Errors while running CTest
make: *** [Makefile:119: test] Error 8
make: Leaving directory '/home/tkloczko/rpmbuild/BUILD/c-ares-1.17.1/x86_64-redhat-linux-gnu'
error: Bad exit status from /var/tmp/rpm-tmp.X1grwQ (%check)
```

**Comment by bradh352** [comment]
Our auto-builds run the tests manually instead of via ctest it appears:

https://github.com/c-ares/c-ares/blob/master/travis/test.sh

I just tried to build on master and it worked.  So I'll try the release tarballs and see what may be going on.

**Comment by kloczek** [comment]
Try to add "-B build" to cmake params and you will see that test suite has hardcided paths.

**Comment by bradh352** [comment]
The issue is the fuzzinput and fuzznames directories aren't included in the distribution tarball.  I also verified back on 1.16.1 and they are also not included there so this isn't a regression, but appears something never supported in the release tarball.  I should have a fix for the release tarball building shortly ... but they won't be included until a future c-ares release.

**Comment by kloczek** [comment]
Tested 1.19.0 and all looks good.
Thank you 👍
