### ISSUE TITLE
1.17.1:  despite static libraries settimngs static library is installed

### ISSUE THREAD

**Issue by kloczek** [c-ares/c-ares#380]
```
CARES_STATIC:BOOL=OFF
CARES_STATIC_PIC:BOOL=OFF
```
and despite above libcares_static.a is installed.

**Comment by bradh352** [comment]
Are you building with tests enabled?  If so, that would explain it as the testing framework requires the static library.

**Comment by kloczek** [comment]
Yes.
Why test suite is not testibng shared libraries which builkd only was ordered?

**Comment by bradh352** [comment]
I believe this is due to the fact that internal symbols are referenced, which may not be exported to shared libraries.  That said, this may really only impact Windows.  I'll see if I can loosen this a bit.
