### ISSUE TITLE
ares_set_servers - Assertion failed: ares__is_list_empty

### ISSUE THREAD

**Issue by silverwind** [c-ares/c-ares#41]
[change_servers.txt](https://github.com/c-ares/c-ares/files/127560/change_servers.txt)

This crash has been plaguing Node.js for a while. It happens when calling `ares_set_servers` with another query in progress. The original issue is https://github.com/nodejs/node/issues/894 and @emotional-engineering also submitted a patch on [the mailing list](http://c-ares.haxx.se/mail/c-ares-archive-2015-04/0002.shtml) in April. I've also attached this patch here.

Here's the message before the crash:
```
Assertion failed: (ares__is_list_empty(&server->queries_to_server)), function ares__destroy_servers_state, file ../deps/cares/src/ares_destroy.c, line 102.
```

cc: @indutny

**Comment by daviddrysdale** [comment]
I don't know the history of `ares_set_servers`, but I guess it's not intended for use on an active channel.

This seems like a big change though;  wouldn't it be easier for the application to just open up a new channel with the new servers, rather than changing the existing channel?

**Comment by bagder** [comment]
I agree with @daviddrysdale here that this is a scarily large change so having more understanding for the use case would help here.

**Comment by bagder** [comment]
Died.
