### ISSUE TITLE
c-ares/include/ares_version.h still showing version 1.17.0

### ISSUE THREAD

**Issue by xypiie** [c-ares/c-ares#413]
Hi,

why does c-ares/include/ares_version.h still show version 1.17.0 in git, but in official tarball it says 1.17.2?

Thanks and best regards
--peter;

**Comment by bradh352** [comment]
This gets updated automatically by the maketgz.sh script that generates the official tarball.  I've gone ahead and updated the version in main ... though maybe the version there should really be some dummy version...

**Comment by xypiie** [comment]
I'd prefer to have the version updated in the git accordingly.
