### ISSUE TITLE
Provide ares_nameser.h as a public interface

### ISSUE THREAD

**Issue by felixonmars** [c-ares/c-ares#415]
Node.js has a wrapper for c-ares that depends on this header. Is it possible to provide the file as a public interface and install by default?

It is used here: https://github.com/nodejs/node/blob/master/src/cares_wrap.h

See also discussions here: https://github.com/nodejs/node/pull/39739#issuecomment-898405127

**Comment by bradh352** [comment]
sure, I don't have a problem with that, it would be a fairly minor change in c-ares.  The main thing is we'd need to add a couple of new defines to ares_build.h for the HAVE_ARPA_NAMESER.H and friends, but namespace them with CARES_ to prevent clashes.
