### ISSUE TITLE
Pass compiler options when building with cmake/ninja

### ISSUE THREAD

**Issue by gaborcsardi** [c-ares/c-ares#425]
Is there a way to pass flags to the compiler when building with cmake? I possibly missed it, but if there isn't, would you consider such an option?

My motivation is that on macOS (via homebrew) I need to build a library that supports older macOS versions as well, and for this I need to pass `-mmacosx-version-min=10.13` to the compiler. E.g. if I put this in `CMakeLists.txt`, that works:

```
set( CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG -mmacosx-version-min=10.13" )
```

**Comment by bradh352** [comment]
You would do it the same way you do with any project that uses CMake, there is nothing c-ares specific that needs to be done.

https://cmake.org/cmake/help/latest/envvar/CFLAGS.html

**Comment by gaborcsardi** [comment]
Unfortunately that does not go through homebrew, i.e. this does not work:
```
CFLAGS=-mmacosx-version-min=10.13 brew install c-ares -v -s
```

But then maybe this is a homebrew issue.

**Comment by bradh352** [comment]
Correct, you'd have to reach out to homebrew on if they overwrite CFLAGS and if there is some way to inject custom ones.

**Comment by gaborcsardi** [comment]
For the record, adding this line to the formula, at the beginning of the `install` function solves my issue:

```
    ENV.append_to_cflags "-mmacosx-version-min=10.13"
```
