### ISSUE TITLE
Classless PTR delegation leads to EBADRESP

### ISSUE THREAD

**Issue by leftshift** [c-ares/c-ares#427]
When resolving the PTR record for IPs for which Classless IN-ADDR.ARPA delegation is used as specified in [RFC2317](https://datatracker.ietf.org/doc/html/rfc2317), the lookup fails with `EBADRESP`.

This is because the `/` in the CNAME record doesn't pass the [`is_hostnamech`](https://github.com/c-ares/c-ares/blob/2227f6982beb915406f17638d0cd054f8d7295bf/src/lib/ares_expand_name.c#L69) check.

As an example, the result for looking up the PTR of `93.122.82.36`:
```
$ dig -t PTR 36.82.122.93.in-addr.arpa
[...]
;; ANSWER SECTION:
36.82.122.93.in-addr.arpa. 28800 IN	CNAME	36.0/25.82.122.93.in-addr.arpa.
36.0/25.82.122.93.in-addr.arpa.	600 IN	PTR	mtx01a.wirtgen-group.com.
[...]
```

This is a regression introduced in version 1.17.2 as it is now impossible to resolve PTR records where this delegation is in use with the suggested `/` character, and this was working before.

I understand the desire of protecting users of this library from XSS and similar issues and can understand that allowing the `/` character in results may not be correctly handled by users of the library in some specific cases, but I feel quite a legitimate use case that is specified in an RFC is broken in a fairly unexpected manner.

**Comment by bradh352** [comment]
adig() uses very low-level calls and does manual parsing, it only impacted users of higher level functions like ares_parse_ptr_reply()
