### ISSUE TITLE
version of cares-1_17_2 tag is wrong.

### ISSUE THREAD

**Issue by sanyuefeiyu** [c-ares/c-ares#437]
download code from https://codeload.github.com/c-ares/c-ares/zip/refs/tags/cares-1_17_2,  and find wrong version string.
it should be 1.17.2.

#define ARES_VERSION_MAJOR 1
#define ARES_VERSION_MINOR 17
**#define ARES_VERSION_PATCH 0**
#define ARES_VERSION ((ARES_VERSION_MAJOR<<16)|\
                       (ARES_VERSION_MINOR<<8)|\
                       (ARES_VERSION_PATCH))
**#define ARES_VERSION_STR "1.17.0"**

**Comment by bradh352** [comment]
I don't think there is anyway to modify a tag in git.  Basically, it is what it is as far as I know, looks like it was a mess up during packaging the release.  Plus this is an historic release, current release is 1.18.1, and the version in the tag appears proper for that one.
