### ISSUE TITLE
gethostbyaddr() tries 4 times when reply is 'ARES_ENOTFOUND'

### ISSUE THREAD

**Issue by apmattil** [c-ares/c-ares#442]
at host_callback() when status is ARES_ENOTFOUND we do the request again.
```
          if (status == ARES_ENODATA || addinfostatus == ARES_ENODATA)
            hquery->nodata_cnt++;
          next_lookup(hquery, hquery->nodata_cnt?ARES_ENODATA:status);
        }
```
should there be check if status is ARES_ENOTFOUND and call end_hquery() ?
or am I missing something ?

**Comment by bradh352** [comment]
The lines of code you pasted don't indicate that it is retrying the same query 4 times.  Can you elaborate on how you've come to this conclusion?

A DNS resolver does use the search domains configured in the system to search for a different possible name if the name you specified isn't found (order of attempts depends on the ndots configuration).

Are you sure you're just not seeing it do the full domain search ?

**Comment by apmattil** [comment]
Hi

yes.. you are most probably right, I just used debugger and printf's and assumed 4 comes from default tries (DEFAULT_TRIES).
I need check what it is actually sending.
Thank you.
