### ISSUE TITLE
how about using epoll instead of select

### ISSUE THREAD

**Issue by ZhuChasel** [c-ares/c-ares#443]
It seems i can not use epoll instead of select. As known, select IO has max fd limits.Thanks.

**Comment by bagder** [comment]
Yes you can, if you use [ares_getsock](https://c-ares.org/ares_getsock.html)

**Comment by ZhuChasel** [comment]
ares_getsock is a good idea. And then all fd_set should be modified like ares_process.

**Comment by bradh352** [comment]
I personally use the ARES_OPT_SOCK_STATE_CB and register a callback...

**Comment by ZhuChasel** [comment]
> I personally use the ARES_OPT_SOCK_STATE_CB and register a callback...
So any patch can be access about your realization.Expectantly and best regards.
