### ISSUE TITLE
Need ability to limit maximum queries per UDP port

### ISSUE THREAD

**Issue by crrodriguez** [c-ares/c-ares#444]
at least when using
 adig foo.com bar.com 

it appears c-ares uses the same socket twice to send the queries out.. at least for UDP it shouldn't, as the little security DNS has left depends on each query coming from a different source port, hopefully with a good randomization provided by the OS.

This is more like a suggestion to change the default beahviour to use one socket per query and close agressively.

**Comment by bradh352** [comment]
The problem with this request is you could quickly eat up all file descriptors available to the process and would be a denial of service attack.  Its not uncommon for a server to have hundreds of outstanding DNS requests under high load depending on what they're doing.  I could see closing after X requests or similar, but not every request.

**Comment by crrodriguez** [comment]
Wel.. yeah. and those people have almost certainly changed the RLIMIT_FILE of their systems .. avoided select.. avoided ares_getsock() .. a middle ground would be starting reuse after $ARBITRAYNUMBER of outstanding DNS requests,,

**Comment by TXTT2016** [comment]
I have met the same problem.In some special network env, when the v4 and v6 udp requires packages were sent from the same port, the firewall sometimes will block one of them. This make remote only receive the v4 or v6 packages and only reply one, then the client dns resolve will timeout.

This happened on iOS platform, sometimes windows also. And when use system interface to do the dns resolve, this won't happened, the v4 and v6 dns packages will send from two different ports.

**Comment by bradh352** [comment]
What firewall/IDS is blocking that behavior?  I'd like to hear from the vendor.  By no means should multiple DNS queries on the same port be considered invalid.  Yes, having a maximum number of queries per port would make sense from a security standpoint, but limiting it to 1 query per port does not.

**Comment by TXTT2016** [comment]
> What firewall/IDS is blocking that behavior? I'd like to hear from the vendor. By no means should multiple DNS queries on the same port be considered invalid. Yes, having a maximum number of queries per port would make sense from a security standpoint, but limiting it to 1 query per port does not.

Maybe c-ares can provide an option to choose use one or two port to send the V4 and V6 UDP packages ?

**Comment by crrodriguez** [comment]
i am not buying the fd number argument really.. one can easily rise the number of fds except if we are going to hit the select-brick-wall. (macos users can avoid it by  _DARWIN_UNLIMITED_SELECT but that's it)

@TXTT2016 bind has an option like this but it actually shouldn't. there is no way to select the correct source port from userspace at least on linux, because only the kernel knows what is right.

**Comment by bradh352** [comment]
The fd argument is that you end up changing the behavior of an application that uses c-ares.  We're not just talking select() behavior here, but that too is a concern.

We can't just break applications.

Also, you need to consider ulimits.  If something is performing a thousand lookups at one time, and all of a sudden it uses a thousand file descriptors instead of 1, they just blew their system default ulimits resulting in a very potential denial of service.  Remember, the only thing that changed here was the c-ares version, which may be distributed independently from the application using it (such as the Linux distribution). No API or ABI breakage occurred, so no one is looking for this.  Yes, its fixable by setting ulimits, but you're going to end up with a lot of production issues that no one expects. 

There are tons of things that use async dns resolvers for high numbers of queries, think of something doing reverse dns for log entries containing ip addresses, that is often done in bulk.

We could add opt-in flags for a port per query, but most applications would probably not opt in ... so if you're looking for security, a max queries per port makes more sense and is less likely to cause unexpected production issues.

**Comment by bradh352** [comment]
from #539 linking issue from downstream usage https://github.com/envoyproxy/envoy/issues/7965

**Comment by rakeshdatta** [comment]
> from #539 linking issue from downstream usage [envoyproxy/envoy#7965](https://github.com/envoyproxy/envoy/issues/7965)

Hello @bradh352 Thanks for linking my issue with this. 
I believe you're suggesting
-  'max queries per port' config; if that config is not set at all, the value is practically infinite? 
-   And for https://github.com/envoyproxy/envoy/issues/7965 I could try configuring it to something non-zero but a lower number (Say 50) to reduce the probability of hitting this bug. Does that sound right?

Btw, is there an ETA when we can expect this fix? I am not sure of your release cycle.  Plz LMK. Thanks.

**Comment by crrodriguez** [comment]
reference to the "bind" features to do this that were disabled/deprecated https://gitlab.isc.org/isc-projects/bind9/-/issues/3781
it is highly discouraged to implement any similar thing, including "max queries per port" again.. because nobody can know for certain if a given ephemeral port is available.

**Comment by bradh352** [comment]
@rakeshdatta yes, exactly

i've got a fork i'm doing some datastructure work with that will help facilitate this: https://github.com/bradh352/c-ares/tree/llist

Once I merge that it should be much easier to implement that, as well as a few other long-standing tickets.

**Comment by rakeshdatta** [comment]
Hi @bradh352 One more Qs if I may.. 
I believe you're going to expose a feature flag as well as a runtime config, and in envoy I have to consume them. What is the standard mechanism to consume them?

**Comment by bradh352** [comment]
@rakeshdatta it will be a new option passed to ares_init_options() : https://c-ares.org/ares_init_options.html

Probably `ARES_OPT_UDP_MAX_QUERIES` with a new member in `struct ares_options` of `size_t max_queries`.

That PR #540 is just some data structures to help facilitate the implementation.  Once that gets merged (I'd like a review from @bagder first, but I might not wait), then I can start on this ticket as well as a couple of others that need those data structures.

**Comment by ssripadham** [comment]
> @rakeshdatta it will be a new option passed to ares_init_options() : https://c-ares.org/ares_init_options.html
> 
> Probably `ARES_OPT_UDP_MAX_QUERIES` with a new member in `struct ares_options` of `size_t max_queries`.
> 
> That PR #540 is just some data structures to help facilitate the implementation. Once that gets merged (I'd like a review from @bagder first, but I might not wait), then I can start on this ticket as well as a couple of others that need those data structures.

This means queries 0 to ARES_OPT_UDP_MAX_QUERIES -1 can still fail on the specific udp port correct?

**Comment by bradh352** [comment]
Not fully sure what you mean.

Certain types of failures will be retried on other servers which will obviously be a different ephemeral port.

But the count will enforce that no more than the specified number of queries will be attempted against the same server on the same ephemeral port, successful or otherwise.

**Comment by rakeshdatta** [comment]
Hi @bradh352 Any update on this? Thanks.

**Comment by bradh352** [comment]
@rakeshdatta I have a fork i'm slowly working on it.  Day job and whatnot is keeping number of hours I can spend on it pretty low.

**Comment by rakeshdatta** [comment]
Okay, Thanks @bradh352 for the update and appreciate your help here. 
Do u have an ETA in mind? Just helps me plan our side of things.

**Comment by bradh352** [comment]
probably a month or so, I have a lot going on right now.

**Comment by rakeshdatta** [comment]
HI @bradh352 Wondering if there is any update for us. Thanks

**Comment by bradh352** [comment]
@rakeshdatta See PR #549. I still need to try to add relevant test cases specific to this feature, but in my own manual testing it appears to work.  If you have a real-world scenario you can test that PR with, that would be helpful.

**Comment by bradh352** [comment]
merged #549
