### ISSUE TITLE
Static Build and link c-ares to the project

### ISSUE THREAD

**Issue by Latorius** [c-ares/c-ares#447]
Hello, 
Please tell me why c-ares cannot be build/compiled statically with the library - iphlpapi.lib ?
Why only through dll ?

**Comment by bradh352** [comment]
Can you provide more information / errors?  Does microsoft even provide a iphlpapi static library?  I thought that was an OS-provided library and not a compiler-provided library.

We do have a compile CI build that tests static building of c-ares.  An example here:
https://ci.appveyor.com/project/c-ares/c-ares/builds/41468289/job/we15byfhv7xrhuvs

**Comment by Latorius** [comment]
Yes, I beg your pardon, I was wrong. If possible, delete this issue.
Thank you.
