### ISSUE TITLE
CMake configuration is wrong on iOS

### ISSUE THREAD

**Issue by lagner** [c-ares/c-ares#451]
DNS resolving on iOS does not work without libresolv. But identifying dependency with Autotools and CMake are different. 

[Autotools checks that the function exists in resolv library](https://github.com/c-ares/c-ares/blob/cares-1_18_1/configure.ac#L380)
```
dnl resolv lib for Apple (MacOS and iOS)
AS_IF([test "x$host_vendor" = "xapple"], [
  AC_SEARCH_LIBS([res_servicename], [resolv], [
    AC_DEFINE([CARES_USE_LIBRESOLV], [1], [Use resolver library to configure cares])
  ], [
    AC_MSG_ERROR([Unable to find libresolv which is required for iPhone targets])
  ])
])
```

CMake, if I understand correctly, [checks if the function exists in the system scope and if so, it rejects the library.](https://github.com/c-ares/c-ares/blob/cares-1_18_1/CMakeLists.txt#L89)
```cmake
CARES_FUNCTION_IN_LIBRARY (res_servicename resolv HAVE_RES_SERVICENAME_IN_LIBRESOLV)
IF (HAVE_RES_SERVICENAME_IN_LIBRESOLV)
	SET (HAVE_LIBRESOLV 1)
ENDIF ()
```
Therefore we have 
```
-- Looking for res_servicename
-- Looking for res_servicename - found
```
But HAVE_LIBRESOLV is undefined

**How to reproduce**
Get the iOS toolchain file [here](https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake) and run
```
cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS64
```

**Comment by bradh352** [comment]
Can you explain the error you are receiving?  Both set CARES_USE_LIBRESOLV within ares_config.h.

And for cmake, it generates the c-ares-config.cmake file containing all the build instructions for any external project linking which should include the libresolv dep.  Likewise, for autotools, it generates a package config file that does the same purpose.

MacOS actually uses the exact same logic as iOS, I haven't tried the ios toolchain file.

We used to autobuild for ios when travis was working, but since they stopped supporting open source, it wasn't re-added for cirrus-ci, its still on the todo list so we may not have visibility into any issues there.

That said, in my day job, we use c-ares and build ios apps and I don't recall any issues...

**Comment by lagner** [comment]
First of all, there are no errors during the build. But name resolving does not work on iOS devices. We use C-Ares with Curl and get the following error in runtime

> Couldn't resolve host name

Let me show step by step. 
I've done the tiny commit to highlighting CMake logic [here](https://github.com/lagner/c-ares/commit/b9422a0197fd2523fbdb37e9639a90e00ac3b844). Then I run the build
```
✓ ~/Projects/c-ares % mkdir build && cd build
✓ ~/Projects/c-ares/build % curl https://raw.githubusercontent.com/leetal/ios-cmake/master/ios.toolchain.cmake -o ios.toolchain.cmake -s 
✓ ~/Projects/c-ares/build % cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DPLATFORM=OS64
```
I see the following log in console 
```
-- Looking for res_servicename
-- Looking for res_servicename - found
-- HAVE_LIBRESOLV is undefined
```
_CARES_USE_LIBRESOLV_ is undefined as well
```
✓ ~/Projects/c-ares/build % cat ares_config.h | grep CARES_USE_LIBRESOLV
/* #undef CARES_USE_LIBRESOLV */
```
**Why does it happen?** 
To check if we need libresolv we call CARES_FUNCTION_IN_LIBRARY.
```cmake
CARES_FUNCTION_IN_LIBRARY (res_servicename resolv HAVE_RES_SERVICENAME_IN_LIBRESOLV)
IF (HAVE_RES_SERVICENAME_IN_LIBRESOLV)
	SET (HAVE_LIBRESOLV 1)
```
let's look closer to the CARES_FUNCTION_IN_LIBRARY macro
```cmake
MACRO (CARES_FUNCTION_IN_LIBRARY func lib var)
	CHECK_FUNCTION_EXISTS ("${func}" "_CARES_FUNC_IN_LIB_GLOBAL_${func}")
	IF ("${_CARES_FUNC_IN_LIB_GLOBAL_${func}}")
→               # in case of iOS we come here!
→               # it because libresolv is a system library on iOS I guess. 
→               # as a result, nobody defines HAVE_LIBRESOLV
→		SET (${var} FALSE)
	ELSE ()
		CHECK_LIBRARY_EXISTS ("${lib}" "${func}" "" ${var})
	ENDIF ()
ENDMACRO ()
```

PS: there is a piece of magic that I can't explain. The library without libresolv does work on iOS Simulator. But it doesn't on iOS devices

**Comment by bradh352** [comment]
My guess is something on your system is causing CMAKE_REQUIRED_LIBRARIES to include libresolv already.  I haven't looked at that toolchain to see what it does, but I've never used it.  In theory libresolv should NOT be in CMAKE_REQUIRED_LIBRARIES ... I'm attempting to add the build to cirrus-ci autobuilds to see what it does there, but I'm not using that toolchain file.

**Comment by bradh352** [comment]
https://cirrus-ci.com/task/5130141339746304
```
-- Looking for res_servicename
-- Looking for res_servicename - not found
-- Looking for res_servicename in resolv
-- Looking for res_servicename in resolv - found
-- Performing Test IOS
-- Performing Test IOS - Success
-- Performing Test IOS_V10
-- Performing Test IOS_V10 - Success
-- Performing Test MACOS_V1012
-- Performing Test MACOS_V1012 - Failed
```

**Comment by Zliu404** [comment]
1、set ENABLE_STRICT_TRY_COMPILE_INT=ON for leetal‘s ios.toolchain.cmake to make sure CMAKE_TRY_COMPILE_TARGET_TYPE is not changed to STATIC_LIBRARY.
2、use newer cmake version （eg. 3.22.1） to disable xcode code signing when try_coplile called by   CHECK_xxx_EXISTS.
