### ISSUE TITLE
c-ares 1.18.1 install is failing

### ISSUE THREAD

**Issue by Pradeep-RG** [c-ares/c-ares#453]
**We are using below steps to configure, build and install c-ares 1.18.1.  The below process was working with c-ares1.16.1** 
mkdir -p debug
cd debug
CPPFLAGS="-DDEBUG -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/src/openssl-1.1.1l/include/openssl -I/src/zlib-1.2.11 -I/src/c-ares-1.18.1 -mno-sse2 -pthread -g"
CFLAGS="-mno-sse2 -pthread -g"
LDFLAGS="-L/src/openssl-1.1.1l/lib/Red_Hat_Enterprise_Linux_Server_release_6.1_Santiago_x86_64_g++_4.4.5/debug -L/src/zlib-1.2.11/Red_Hat_Enterprise_Linux_Server_release_6.1_Santiago_x86_64_g++_4.4.5/lib/debug -pthread"
LIBS="-lpthread"
export CPPFLAGS CFLAGS LDFLAGS LIBS

**../configure --enable-shared=no --enable-debug=no --prefix=`pwd` --enable-debug
gmake
gmake install**

**'gmake install'  step is failing with below error.**

Making install in include
gmake[1]: Entering directory `/src/c-ares-1.18.1/debug/include'
gmake[2]: Entering directory `/src/c-ares-1.18.1/debug/include'
gmake[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/src/c-ares-1.18.1/debug/include'
 /usr/bin/install -c -m 644 ../../include/ares.h ../../include/ares_version.h ares_build.h ../../include/ares_rules.h ../../include/ares_dns.h ../../include/ares_nameser.h '/src/c-ares-1.18.1/debug/include'
/usr/bin/install: `ares_build.h' and `/src/c-ares-1.18.1/debug/include/ares_build.h' are the same file
gmake[2]: *** [install-includeHEADERS] Error 1
gmake[2]: Leaving directory `/src/c-ares-1.18.1/debug/include'
gmake[1]: *** [install-am] Error 2
gmake[1]: Leaving directory `/src/c-ares-1.18.1/debug/include'
gmake: *** [install-recursive] Error 1

**Comment by bradh352** [comment]
Your --prefix=`pwd` is invalid.  You can't install to the build directory like that.  I can't say why 1.16 allowed that (it shouldn't have), but we did have to make substantial changes to the autotools build for compatibility with the latest tools.
