### ISSUE TITLE
c-ares.org has AAAA dns record but does not listen on ipv6

### ISSUE THREAD

**Issue by georgthegreat** [c-ares/c-ares#456]
```
$ host c-ares.org
c-ares.org has address 159.253.31.95
c-ares.org has IPv6 address 2a02:750:7:3305::2aa
```

```
$ telnet c-ares.org 443
Trying 2a02:750:7:3305::2aa...
telnet: Unable to connect to remote host: Connection refused
```

This drives ipv6-only hosts crazy.
Even when they ipv4-connectable, this fallback is not enabled when AAAA record is available.

Could you, please, resolve this either by removing AAAA record, or by enable ipv6 listening?

**Comment by georgthegreat** [comment]
NB: same applies to libssh2.org, as all these hostnames are handled by the same host

```
$ host www.libssh2.org
www.libssh2.org is an alias for libssh2.haxx.se.
libssh2.haxx.se is an alias for silly.haxx.se.
silly.haxx.se has address 159.253.31.95
silly.haxx.se has IPv6 address 2a02:750:7:3305::2aa
```
```
$ telnet www.libssh2.org 443
Trying 2a02:750:7:3305::2aa...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by bagder** [comment]
This really isn't a c-ares problem, it is an issue with the site hosting the c-ares.org website. I'm aware of it (as the person running the host).

**Comment by georgthegreat** [comment]
Is there any workaround?

We are using NixOS to build c-ares / libssh2 / libcurl.
While github-based releases should work well, they lack necessary files (such as configure) and porting is not an easy task.

**Comment by bagder** [comment]
The actual, official, release packages are available on GitHub as well. See https://github.com/c-ares/c-ares/releases/tag/cares-1_18_1 and the "assets" listed first.

**Comment by georgthegreat** [comment]
Thanks, these links works as intended.

You can either close this issue, or keep it open until the initial problem will be fixed.

**Comment by bagder** [comment]
Fixed

**Comment by georgthegreat** [comment]
Thanks!
