### ISSUE TITLE
[regression] CNAME with * is parsed as invalid response

### ISSUE THREAD

**Issue by rb-cohen** [c-ares/c-ares#457]
With a CNAME setup `test -> *.test`, ares is rejecting the response as invalid. 

e.g.

```
dig test.tld

; <<>> DiG 9.10.6 <<>> test.tld
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3826
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;test.tld.		IN	A

;; ANSWER SECTION:
test.tld.	6529	IN	CNAME	*.test.tld.cdn.cloudflare.net.
*.test.tld.cdn.cloudflare.net. 300 IN A	1.1.1.1
*.test.tld.cdn.cloudflare.net. 300 IN A	1.1.1.1

;; Query time: 67 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Mar 01 18:54:45 GMT 2022
;; MSG SIZE  rcvd: 128
```

Seems related to https://github.com/c-ares/c-ares/issues/424
Posted in node too: https://github.com/nodejs/node/issues/42171

**Comment by bradh352** [comment]
fixed in cc79624

**Comment by nitinmohan87** [comment]
Should there be a new release tag created with this regression bug fix? I don't see this being included in the latest v1.8.1 release. Thanks!

**Comment by bradh352** [comment]
This is on me.  I've been slammed at work and haven't done the release prep for the new release.  I'm on "vacation" this week, so I'll probably get a chance to do it :)

**Comment by nitinmohan87** [comment]
Hello... Any chances a new version will be released soon-ish? Thanks!
