### ISSUE TITLE
On greater than iOS14, c-ares not work

### ISSUE THREAD

**Issue by yifzone** [c-ares/c-ares#466]
I use c-ares with libcurl in ios, i allways get resolve host failed when reject **local network permission**(system version greater than ios14, because local network permission is an new permission after ios14).
I did a lot of test, finally, found in wifi and **dns is 192.168.x.x**, this error happend 100%.
I guess the reason was c-ares can't communication with dns servers like 192.168.x.x when reject local network permission???
Does any one have solution？？
Similar to： #412

**Comment by bradh352** [comment]
hardcode public dns servers like 1.1.1.1 or 8.8.8.8 instead of using local dns servers if you can guarantee you have no need to look up something locally ... that is the only workaround.
