### ISSUE TITLE
ares-test-mock-ai.cc Failure

### ISSUE THREAD

**Issue by navinagaraj** [c-ares/c-ares#476]
Facing the issue while testing a " ./arestest " can anyone help !!

c-ares-1.18.1/test/ares-test-mock-ai.cc:741: Failure
Expected equality of these values:
  "{addr=[1.1.1.1:80], addr=[2.2.2.2:80]}"
  ss.str()
    Which is: "{nullptr}"
[  FAILED  ] AddressFamiliesAI/MockChannelTestAI.FamilyV4ServiceName/0, where GetParam() = (2, false) (13 ms)
[ RUN      ] AddressFamiliesAI/MockChannelTestAI.FamilyV4ServiceName/1

----------------------------------------------------------------------------------------------
TEST-FAILE RESULT 

[----------] Global test environment tear-down
[==========] 388 tests from 22 test suites ran. (52713 ms total)
[  PASSED  ] 384 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] AddressFamiliesAI/MockChannelTestAI.FamilyV4ServiceName/0, where GetParam() = (2, false)
[  FAILED  ] AddressFamiliesAI/MockChannelTestAI.FamilyV4ServiceName/1, where GetParam() = (2, true)
[  FAILED  ] AddressFamiliesAI/MockChannelTestAI.FamilyV4ServiceName/2, where GetParam() = (10, false)
[  FAILED  ] AddressFamiliesAI/MockChannelTestAI.FamilyV4ServiceName/3, where GetParam() = (10, true)

 4 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS

**Comment by navinagaraj** [comment]
I tried to cross-compile a c-ares package to the imx6ul-evk board. In my device, there is no /etc/services file. I that test case failing to cause any issue?.

**Comment by bradh352** [comment]
it means that if you use ares_getaddrinfo() and pass a service name rather than a port, it won't resolve the service name.

**Comment by navinagaraj** [comment]
Thanks for the information & quick response @bradh352.
