### ISSUE TITLE
Resolve foo.localhost as localhost

### ISSUE THREAD

**Issue by mcollina** [c-ares/c-ares#477]
From https://github.com/nodejs/undici/issues/1571:

## Bug Description

In my local development env I got Hasura running and responding on `hasura.localhost`. This works fine in Chrome, I can open the web UI and do stuff from there. However this does not seem to work when trying to query the api using `undici` (see `reproducible by` below).

This seems to break [RFC-6761](https://www.rfc-editor.org/rfc/rfc6761#section-6.3):

>Name resolution APIs and libraries SHOULD recognize localhost names as special and SHOULD always return the IP loopback address for address queries and negative responses for all other query types. Name resolution APIs SHOULD NOT send queries for localhost names to their configured caching DNS server(s).

So it seems that Chrome resolves `hasura.localhost` as the localhost loopback, while Node.js and in in turn c-ares do not.

From a quick look at it, https://github.com/c-ares/c-ares/blob/e20215ab931eaf91a89b9fe3441dac18c4305979/src/lib/ares_getaddrinfo.c#L490-L499 does not handle this case.

**Comment by bradh352** [comment]
The part of the RFC you are referencing is talking about just "localhost". I've seen no standard stating there is such a thing as a subdomain of localhost or how to treat those.

If you drop to a command line and run   `ping hasura.localhost`  what happens?

On my own system:
```
$ ping hasura.localhost
ping: cannot resolve hasura.localhost: Unknown host
```

If I edit /etc/hosts and add it as an alias, it works.

So either my system resolver (which is not c-ares, this happens to be MacOS at this time) is also broken, or Chrome is doing something special.

**Comment by bradh352** [comment]
Upon further research, you may actually be encountering non-standard extensions introduced by systemd: [https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Synthetic%20Records](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Synthetic%20Records)

**Comment by dimbleby** [comment]
> The part of the RFC you are referencing is talking about just "localhost".

but what it says is

> The domain "localhost." and any names falling within ".localhost." ...

?

**Comment by bradh352** [comment]
Interesting, missed the falling within ".localhost.", wonder why this isn't universally supported then.

**Comment by mcollina** [comment]
I was extremely surprised when reading that RFC, which seems pretty clear and points at Chrome implementing the correct behavior.

**Comment by mcollina** [comment]
> Upon further research, you may actually be encountering non-standard extensions introduced by systemd: https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Synthetic%20Records

Chrome implements this on Mac too, it's not Systemd specific.
