### ISSUE TITLE
[suggestion]Find a way to optimize out the OS calls in find_src_addr

### ISSUE THREAD

**Issue by ffproxy** [c-ares/c-ares#483]
Hi, 

I'm using c-ares recently, I noticed that there are a heavy OS calls in find_src_addr function , Do we have any way to optimize these OS calls out ?

**Comment by bradh352** [comment]
This is part of getaddrinfo()'s sort logic, and it was taken from Android Bionic's code.  Its likely most other getaddrinfo implementations need to do this same logic.

I doubt you're going to be able to optimize those calls out and still be able to do the sorting as required by getaddrinfo.

Perhaps you could look into caching the results up to the TTL if you're worried about the overhead, as our implementation does indeed return the TTL.

**Comment by ffproxy** [comment]
Refer to https://man7.org/linux/man-pages/man2/connect.2.html, 

```
      Some protocol sockets (e.g., datagram sockets in the UNIX and
       Internet domains) may use connect() multiple times to change
       their association.
```
Can we use this feature to share a fd to do connect/getsockname for each ares_channel, thus to reduce open/close OS calls。

**Comment by bradh352** [comment]
No, there is no means for us to preserve the file descriptors for you to reuse if that's even possible.  You'll note it uses UDP because it is connectionless meaning it only checks to see if there is a valid route to the endpoint, not actually send anything across the network.

**Comment by bradh352** [comment]
Should also mention that you can avoid sorting if in the hints var passed to ares_getaddrinfo() you set ai_flags to ARES_AI_NOSORT, it will avoid all those syscalls you're worried about, but technically becomes non-conformant.
