### ISSUE TITLE
DNS over TCP: write_tcp_data() does not check number of iovec entries

### ISSUE THREAD

**Issue by dreibh** [c-ares/c-ares#488]
write_tcp_data() does not check number of iovec entries is creates for queries. If the number exceeds __IOV_MAX (Linux: 1024), the following writev() will fail. In this case, the queries fail with ARES_ENOTFOUND although none of these queries have been sent to a DNS server.

The fix is simply to stop when the number of iovec entries has reached __IOV_MAX:
```
          for (sendreq = server->qhead; sendreq; sendreq = sendreq->next)
            {
              vec[n].iov_base = (char *) sendreq->data;
              vec[n].iov_len = sendreq->len;
              n++;
              if(n >= __IOV_MAX)
                break;
            }
```
The following call to advance_tcp_send_queue() is based on the actual number of bytes sent.

**Comment by dreibh** [comment]
Note that filling the queue with more than __IOV_MAX requests leads to a failure of sending any request, as long as the queue size is not reduced (timeout?). This may be used in a denial of service attack.

**Comment by bradh352** [comment]
Thanks, merged
