### ISSUE TITLE
how to get the timeout of channel

### ISSUE THREAD

**Issue by theanarkh** [c-ares/c-ares#493]
Hi, how can I get `timeout` of channel ? Can I use `ares_timeout` ? I call `ares_init_options` with `timeout = -1`, I want to know how long I should wait before calling `ares_process_fd` to tell `c-ares` that the socket has timed out. Thanks !

**Comment by bradh352** [comment]
yes, ares_timeout is meant to be used for the purpose of determining when to call ares_process/ares_process_fd if no events have occurred on the c-ares owned file descriptors.
