### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [c-ares/c-ares#498]
I would like to point out that identifiers like “[`ARES__H`](https://github.com/c-ares/c-ares/blob/810c2322f9eedf4a83c20859d17d5773fdc57943/include/ares.h#L18 "Update candidate")” and “[`ares__init_list_head`](https://github.com/c-ares/c-ares/blob/main/src/lib/ares_llist.h#L28 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by bradh352** [comment]
Since c-ares is a C project, internal symbols and naming conventions aren't intended to conform with any C++ standards.  This does not prevent this project from being compiled and linked into C++ projects in any way.

**Comment by elfring** [comment]
I would also like to point out that identifiers like “[`__ARES_PRIVATE_H`](https://github.com/c-ares/c-ares/blob/810c2322f9eedf4a83c20859d17d5773fdc57943/src/lib/ares_private.h#L1 "Update candidate")” and “[`__SETUP_ONCE_H`](https://github.com/c-ares/c-ares/blob/de042a65f492f8a8b0a10bf21494623b9ac345fd/src/lib/setup_once.h#L1 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to reconsider the selection for unique names accordingly?
