### ISSUE TITLE
C-ares issue with UDP query version 1.14.0 or 1.16.0

### ISSUE THREAD

**Issue by gairolapankaj** [c-ares/c-ares#499]
Hi Team,

We are using the C-ares library with our product  and previously, we were using version 1.6.0. and with that version we are getting proper response for UDP query.
Now we are using version 1.14.0 but we have seen errors with the UDP query's response. It always return either error 12(ARES_ETIMEOUT) or 24(ARES_ECANCELLED)
Please see below wireshark traces .
Please note that we are using **ares_query** function for UDP query and on version(1.6.0) we are getting success results but on version 1.14.0 we are getting errors for UDP.
Note: TCP is working fine with all the versions.
If any feedback or additional check we need to do please let us know. 

====
code snip:
	if (p->port && (p->typeport == TCP || p->typeport == UDP))
	{
		optmask |= (p->typeport == TCP) ? ARES_OPT_TCP_PORT : ARES_OPT_UDP_PORT;

		if (optmask & ARES_OPT_TCP_PORT)
			options.tcp_port = htons((unsigned short)p->port);
		else
			{
			options.udp_port = htons((unsigned short)p->port);
	}
	

	
	status = ares_init_options(&channel, &options, optmask);

	if (status != ARES_SUCCESS)
	{
		return NIME_ERROR;
	}
	
	
	p->query_status = ARES_SUCCESS;
	

	
	ares_query(channel, p->target_ares, iclass, itype, callback, (void*)p);
       rc = wait_ares(channel,p);
.....
===========================

![image (4)](https://user-images.githubusercontent.com/11970366/210880881-281f3404-cbb3-4d3a-8778-9da19cf0127d.png)

**Comment by bradh352** [comment]
can you try a current release of c-ares?

**Comment by bradh352** [comment]
we'd probably also need to see what wait_ares() is doing, its possible there is a flaw in there that happened to work in older versions.  1.6.0 is super old (2008).

**Comment by gairolapankaj** [comment]
We tried 1.18.1 also similar result we observed .i have added logs which have detail about wait_ares detail logs. 
[query_wait_logs.txt](https://github.com/c-ares/c-ares/files/10357426/query_wait_logs.txt)

**Comment by gairolapankaj** [comment]
We are using below code for wait_ares. let me know if we need to modify something
int wait_ares(ares_channel channel,PROFILE *p)
{
	int nfds = 0;
	int retry = 0;
	int rc = NIME_ERROR;
	fd_set read_fds, write_fds;
	struct timeval tv;
	time_t tstart,tnow;

	nimLog(5, "In wait_ares");
	tv.tv_sec = 0;
	tv.tv_usec = 1000; /* Check for data every 1 ms */
	retry = p->retries;
	
	nimLog(5, "Starting timer");
	nimTimerStart(&p->time_ms);

	nimLog(5, "Retries");
	while(retry >= 1)
	{
		nimLog(5, "Retries number %d", retry);
		tstart = tnow = time(NULL);

		nimLog(5, "Checking timeout");
		while(p->timeout >= (tnow - tstart))
		{
			FD_ZERO(&read_fds);
			FD_ZERO(&write_fds);
			nimLog(5, "Calling ares_fds");
			nfds = ares_fds(channel, &read_fds, &write_fds);
			nimLog(5, "ares_fds nfds %d", nfds);
			if (nfds == 0)
			{
				rc = NIME_OK;
				break;
			}

			nimLog(5, "Calling select");
			select(nfds, &read_fds, &write_fds, NULL, &tv);
			nimLog(5, "Calling ares_process");
			ares_process(channel, &read_fds, &write_fds);
			tnow = time(NULL);
			nimLog(5, "Current time captured");
		}
		retry--;
	}
	p->query_status = (rc == NIME_ERROR) ? ARES_ETIMEOUT : ARES_SUCCESS; /* timed out has occurred */
	nimLog(5, "p->query_status %d", p->query_status);
	return rc;
}

**Comment by gvanem** [comment]
You could reenter the outer loop if `rc = NIME_OK` and `retry >= 1`. Why not a `goto`?

**Comment by gairolapankaj** [comment]
Actually issue is , we are not getting response for ares_query and its keep on waiting. it seems it stuck somewhere in C-ares . we are getting only Status 24 and 12 in case of UDP. but in TCP it is success

**Comment by bradh352** [comment]
You need to not use your own timeval, use ares_timeout(channel, NULL, &tv); ... you're looping way too fast.

Also, as part of the c-ares build, there is an 'adig' utility, have you tried running that?  The equivalent query to what you're doing with your code would be:

adig -c IN -t ANY www.google.com

Finally, any particular reason you're not using ares_gethostbyname() or ares_getaddrinfo() for this type of query?  You miss out on whole sets of logic like using /etc/hosts and retries.

**Comment by bradh352** [comment]
also, it would be good to know what OS you are on.

**Comment by gairolapankaj** [comment]
OS is windows, Same code base is working with version 1.7.1 but now on latest version it is not working for UDP. 
If it causing due to timeout then it also failed for TCP. we also have attached logs in above comment. It seems like it stuck in between loop and getting Status 24 which is ARES_ECANCELLED.

Note:-
We also mailed on c-ares@lists.haxx.se but did not gpt any Answer.
Your help is much appreciated as lib upgrade is very critical for us

**Comment by bradh352** [comment]
Did you try adig like suggested?  It should be built with c-ares by default.  This is likely a code issue in your integration that just happened to work with old versions of c-ares.  Either that, or there is some build issue of c-ares depending on how you're building, which running 'adig' would confirm if there is some build-related issue vs an issue in your usage of c-ares.

Also, v1.6.0 that you were using predates ares_library_init() which became mandatory on Windows, are you calling this function?

**Comment by bradh352** [comment]
closing due to no reply
