### ISSUE TITLE
Under load, `ares_getaddrinfo` is 3x slower than libc `getaddrinfo` (w/ threadpool)

### ISSUE THREAD

**Issue by Jarred-Sumner** [c-ares/c-ares#500]
Here is a small load test comparing three implementations of getaddrinfo:
| backend | description|
|----------|------------|
| libc | `getaddrinfo` in a thread pool |
|system | macOS [`getaddrinfo_async_start`](https://opensource.apple.com/source/Libinfo/Libinfo-391/lookup.subproj/netdb_async.h.auto.html) |
|c-ares| `ares_getaddrinfo` |

```zig
cpu: Apple M1 Max
runtime: bun 0.4.1 (arm64-darwin)

benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
• dns.lookup remote x 50
------------------------------------------------- -----------------------------
libc       749.81 ms/iter (737.44 ms … 759.57 ms) 756.56 ms 759.57 ms 759.57 ms
c-ares        2.38 s/iter     (90.88 ms … 3.28 s)    3.17 s    3.28 s    3.28 s
system     176.99 ms/iter     (65.13 ms … 1.17 s)  94.39 ms    1.17 s    1.17 s

summary for dns.lookup remote x 50
  system
   4.24x faster than libc
   13.44x faster than c-ares
```

<details><summary><strong>Source code</strong></summary>

```js
import { dns } from "bun";
import { bench, run, group } from "mitata";

function forEachBackend(name, fn) {
  group(name, () => {
    for (let backend of [
      "libc",
      "c-ares",
      process.platform === "darwin" ? "system" : "",
    ].filter(Boolean)) {
      bench(backend, fn(backend));
    }
  });
}

forEachBackend("dns.lookup remote x 50", (backend) => async () => {
  const run = () =>
    dns
      .lookup(Math.random().toString(16) + ".tumblr.com", { backend })
      .catch(() => {});
  var remain = 50;
  var done;
  await new Promise((resolve) => {
    for (var i = 0; i < 50; i++)
      run().finally(() => {
        remain--;
        if (remain === 0) {
          done();
        }
      });
    done = resolve;
  });
});

```
</details>

Here is the system trace for a single batch of 50 simultaneous lookups.

For 50 lookups:
- `sendto` is called 106 times
- `recvfrom` is called 146 times

<img width="852" alt="image" src="https://user-images.githubusercontent.com/709451/211145050-5bec3ab3-2c41-458d-aa0b-7df209cc4346.png">

If we step in the debugger, we can see that for one `ares_getaddrinfo` call, there are two calls to `socket_write` with buffers under 50 bytes:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/709451/211145172-56f3a614-4f26-43ce-ac21-121c110bd1c1.png">

The culprit for writing twice appears to be here:

https://github.com/c-ares/c-ares/blob/0e7a5dee0fbb04080750cf6eabbe89d8bae87faa/src/lib/ares_getaddrinfo.c#L771-L776

Buffering the calls to `send_socket` and only flushing at the end of the outermost loop or when the length is near the max is likely to improve the performance somewhat.

For udp, it may be worth exploring `recvmmsg` to receive all the messages for the socket in one system call.

**Comment by bradh352** [comment]
I'm definitely not familiar with the language you're using there, can you tell me if these 50 requests are run synchronously or asynchronously?  Can you share any of the c-ares code you're using?  Obviously according to the call trace, the most time is spent in something called psynch_cvwait, googling that it seems to state its not cpu time but rather a dead wait ... this would suggest there could be an issue with your usage of c-ares since you're responsible for notifying c-ares of events and honoring the timers set.

Your mentioning of sendto and recvfrom shows a cumulative time of less than 2ms cumulatively, so that seems unlikely to affect performance at all to me.

**Comment by bradh352** [comment]
closing due to no reply, likely an error in the user code itself
