### ISSUE TITLE
undefined reference to 'static_assert'

### ISSUE THREAD

**Issue by ThomasDevoogdt** [c-ares/c-ares#504]
Apparently, `static_assert` is not guaranteed if no c++ toolchain is used under uClibc.
This is used by fluent-bit, which I'm trying to compile for uClibc toolchains in buildroot.

I found out that this patch is enough to fix it:
```patch
From 30eae49d70786e0726cc6c537e05e468a9411db3 Mon Sep 17 00:00:00 2001
From: Thomas Devoogdt <thomas.devoogdt@barco.com>
Date: Wed, 1 Feb 2023 11:26:56 +0100
Subject: [PATCH] lib: c-ares: fixup static_assert

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
---
 lib/c-ares-1.18.1/configure                      | 4 ++++
 lib/c-ares-1.18.1/m4/ax_cxx_compile_stdcxx_11.m4 | 3 +++
 2 files changed, 7 insertions(+)

diff --git a/lib/c-ares-1.18.1/configure b/lib/c-ares-1.18.1/configure
index 737f0a0dd..b99b7ed49 100755
--- a/lib/c-ares-1.18.1/configure
+++ b/lib/c-ares-1.18.1/configure
@@ -6316,6 +6316,8 @@ else $as_nop
   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 
+#define static_assert _Static_assert
+
   template <typename T>
     struct check
     {
@@ -6393,6 +6395,8 @@ else $as_nop
          cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 
+#define static_assert _Static_assert
+
   template <typename T>
     struct check
     {
diff --git a/lib/c-ares-1.18.1/m4/ax_cxx_compile_stdcxx_11.m4 b/lib/c-ares-1.18.1/m4/ax_cxx_compile_stdcxx_11.m4
index 229de3091..fe4a11c67 100644
--- a/lib/c-ares-1.18.1/m4/ax_cxx_compile_stdcxx_11.m4
+++ b/lib/c-ares-1.18.1/m4/ax_cxx_compile_stdcxx_11.m4
@@ -37,6 +37,9 @@
 #serial 9
 
 m4_define([_AX_CXX_COMPILE_STDCXX_11_testbody], [[
+
+#define static_assert _Static_assert
+
   template <typename T>
     struct check
     {
-- 
2.39.0


```

A similar fix was done in another project, used by fluent-bit: https://github.com/Cyan4973/xxHash/commit/6189ecd3d44a693460f86280ccf49d33cb4b18e1

**Comment by bradh352** [comment]
Can you tell me if #505 also resolves the issue?  I just synced the .m4 with upstream.  If it still has the issue, I think you should probably report the issue upstream and have them implement a fix there, then we can pull in the newer upstream version.

https://www.gnu.org/software/autoconf-archive/

Upstream repo here:
http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=tree;f=m4

**Comment by ThomasDevoogdt** [comment]
At first sight, it seems that the static_assert has been removed from ax_cxx_compile_stdcxx_11.m4 upstream.
So I guess it will be fixed by that (to be checked). But I'm a bit stuck with the configure file. I don't see it in this repo, but I can find it here: https://github.com/fluent/fluent-bit/blob/master/lib/c-ares-1.19.0/configure. Is that a generated file at bump time? If yes, where does that static_assert then come from? But I guess that this is part of that m4 + configure.ac framework?
(I'm just not that used to that autoconfigure stuff)

**Comment by bradh352** [comment]
configure gets generated from the configure.ac plus all the .m4 files.  With production releases we'll pregenerate this for you in case you don't have autoconf/automake/libtool installed.  You can generate it yourself by running  autoreconf -fi  in the source directory.
