### ISSUE TITLE
ares_getaddrinfo() of port 0 reports ARES_ESERVICE

### ISSUE THREAD

**Issue by bagder** [c-ares/c-ares#517]
... while using glibc's `getaddrinfo()` with the same port number works fine.

(I use `ARES_AI_NUMERICSERV` set in `ai_flags`)

Is there actually any good reason to refuse just using 0 as a dummy port?

**Comment by bradh352** [comment]
When you say zero, are you passing 0 (aka NULL) as the "service" argument, or are you passing the string "0"?

**Comment by bagder** [comment]
The string `"0"`, like this:

https://github.com/curl/curl/blob/a51f90ec0f74176776f5d14b99689f9241660eaa/lib/asyn-ares.c#L784

I modified the code to instead use the string `"80"` as a work-around, and then it succeeds (with both glibc and c-ares).

**Comment by bradh352** [comment]
Interesting use case.  Typically if you don't care about the service port in a dns lookup, you'll just pass NULL to that field.  But if other implementations support this, we definitely can too, its a trivial change.
