### ISSUE TITLE
c-ares should not override CFLAGS

### ISSUE THREAD

**Issue by 5533asdg** [c-ares/c-ares#518]
c-ares is overriding debug flags (e.g. -g, -g0, etc.) and optimization flags (e.g. -O -O0, etc.) depending on its own flags (--{en,dis}able-debug, --{en,dis}able-optimize).

If the user is already specifying these CFLAGS, c-ares should respect the flags.
This becomes a problem when distros want to specify certain CFLAGS to use irrespective of c-ares flags (e.g. when directly using c-ares from Gentoo while keeping the upstream config as-is).

**Comment by bradh352** [comment]
I assume you're talking about the autotools version.  Maybe switch to using the CMake build scripts?  We'll accept patches for autotools, but I consider the CMake build system the go-forward.
