### ISSUE TITLE
Query DNS Server from the disconnected adapter

### ISSUE THREAD

**Issue by peterlaser** [c-ares/c-ares#52]
Laptop has wireless and wired network cards.
The two cards can connected to two network connection and DNS servers can be reachable by the two different dhcp network type.

Steps
1.in the Lan network, go to DNS server 1 and then set web server DNS record to a server ip, such as 192.168.0.100

2. in the wireless network, go to DNS server2 and then set web server DNS record to a server ip, such as 192.168.0.200

3.Set Local Area Connection(wired connection) and Wireless Network connection both obtain and IP address/DNS server address automatically

4.Go to network connections->Advanced Settings->Adapters and Bindings, make sure Wireless Network connection at the top of local Area connection.

5.disconnect wireless connection, connected the local area connection(wired connection)

6.Launch app and try to connect to the web server

Result:
c-ares will query dns server2 and return the 192.168.0.200 for the web server. 

c-ares 1.10 

ares_init.c  Line 1026

static int get_DNS_AdaptersAddresses(char **outptr)
{
  …
  for (ipaaEntry = ipaa; ipaaEntry; ipaaEntry = ipaaEntry->Next)
  {
    // Need to Add code to check the status !!!
    /* Ignore the network interface if it is already down */
    if( ipaaEntry->OperStatus != IfOperStatusUp )
        continue;
    for (ipaDNSAddr = ipaaEntry->FirstDnsServerAddress;
         ipaDNSAddr;
         ipaDNSAddr = ipaDNSAddr->Next)
    {

**Comment by daviddrysdale** [comment]
I'm not sure I completely follow the problem, but could you confirm which version of the library you're using?   You say "c-ares 1.10" but the code fragment includes the `OperStatus` check which is only present in c-ares 1.11 (since commit 52ecef76df077b393d4108d5275e9b4f4622ddce).

**Comment by peterlaser** [comment]
Many Thanks for your information, c-ares1.11 do fix it, closing it. 
“OperStatus” check attached is a local change to fix the similar issue like 1.11 did. Sorry for any confusing.
