### ISSUE TITLE
include/ares_version.h not bumped for version 1.19.1

### ISSUE THREAD

**Issue by debohman** [c-ares/c-ares#523]
I noticed that the patch level was not updated for version 1.19.1.

**Comment by renodr** [comment]
I can confirm this as well, noticed when using the WATCOM compiler to build c-ares.

**Comment by bagder** [comment]
I suppose we can have this debate for every release:

The release is a tarball as provided on the website and on the release here on GitHub. The tarball is signed. The files in git repository at the tag are used to generate the release. You do not actually use the release if you do not build from the tarball. You use the files from the same moment in time though if you use the git tag.

I believe the patch level is correct in the release tarball. It gets generated by `maketgz` which creates the release.

**Comment by dimbleby** [comment]
https://github.com/c-ares/c-ares/blob/cares-1_19_1/include/ares_version.h#L10

**Comment by bradh352** [comment]
probably by pure chance, its not in the release procedure, so the release procedure needs to be updated to make sure things like this aren't skipped.

**Comment by debohman** [comment]
Okay.
