### ISSUE TITLE
DNS over TCP performance question

### ISSUE THREAD

**Issue by ohadvano** [c-ares/c-ares#536]
Couldn't understand from the docs if using DNS over TCP instead of UDP would utilize the same socket, instead of opening new connections for new requests. What would be the behavior if using TCP? Is there a general note on the performance of choosing TCP over UDP with c-ares?

**Comment by gvanem** [comment]
> DNS over TCP instead of UDP would utilize the same socket

Impossible AFAICS.

> Is there a general note on the performance of choosing TCP over UDP with c-ares?

If a response is "*known*" to be too large to fit in a UDP packet (approx. 512), choose TCP.

**Comment by ohadvano** [comment]
> If a response is "known" to be too large to fit in a UDP packet (approx. 512), choose TCP.

The reason I have to use TCP originates with a problem happening with c-ares in K8s environment. You can read about it in this GitHub issue: https://github.com/envoyproxy/envoy/issues/7965. Basically I'm forced to use TCP, but also trying to understand the implications of this in terms of performance, used ports, new connections opening, etc..

**Comment by bradh352** [comment]
From a c-ares standpoint, there isn't any additional TCP overhead in our own code/logic.  Any additional overhead will come from the fact that TCP is connection-based which mainly means the initial 3-way handshake, plus things like congestion control algorithms, retries, etc ... all handled at the OS level.  If you're talking about all this occurring over a local reliable network as that referenced github issue suggests, in theory the performance difference should be basically immeasurable.

That said, someone did open an Issue #266 saying there might be a bug in the USEVC option, but that hasn't been confirmed or researched.

**Comment by ohadvano** [comment]
Thanks
