### ISSUE TITLE
Fails to build using MSVC 2015: Unknown value for _NMAKE_VER macro: 14.00.23918.0

### ISSUE THREAD

**Issue by briansmith** [c-ares/c-ares#55]

**Comment by daviddrysdale** [comment]
What version are you using?  I think this should have been fixed with commit a788a1ac1caad4549aa7.

**Comment by briansmith** [comment]
Oh, awesome! I guess the problem is that https://github.com/dimbleby/rust-c-ares is using an older version. Thanks!
