### ISSUE TITLE
GetHostByNameParallelLookups test is failing

### ISSUE THREAD

**Issue by gjasny** [c-ares/c-ares#560]
Hello,

when building c-ares mainline (at 1.20.0) on Debian Sid (aarch64 running as a Paralles VM), the following tests fail:
```
[----------] 2 tests from AddressFamilies/MockUDPMaxQueriesTest
[ RUN      ] AddressFamilies/MockUDPMaxQueriesTest.GetHostByNameParallelLookups/0
ares-test-mock.cc:262: Failure
Expected equality of these values:
  256 / 16
    Which is: 16
  sock_cb_count
    Which is: 18
[  FAILED  ] AddressFamilies/MockUDPMaxQueriesTest.GetHostByNameParallelLookups/0, where GetParam() = 2 (1511 ms)
[ RUN      ] AddressFamilies/MockUDPMaxQueriesTest.GetHostByNameParallelLookups/1
ares-test-mock.cc:262: Failure
Expected equality of these values:
  256 / 16
    Which is: 16
  sock_cb_count
    Which is: 18
[  FAILED  ] AddressFamilies/MockUDPMaxQueriesTest.GetHostByNameParallelLookups/1, where GetParam() = 10 (1511 ms)
[----------] 2 tests from AddressFamilies/MockUDPMaxQueriesTest (3022 ms total)
```

Verbose test output and strace log is available here: https://gist.github.com/gjasny/2f67f56a3d83185c6d824c9a473280c4

There are indeed 18 occurrences of `SocketConnectCallback`. 16 of them in the beginning, and two a little bit later.

Do you have an idea what's going on? AFAIU the test itself does not depend on any "Live" environment.

Thanks,
Gregor

**Comment by bradh352** [comment]
That is a new test case in 1.20.0, and you can see the equivalent test here on aarch64 debian from our CI here:
https://cirrus-ci.com/task/5121439926321152?logs=main#L2156

It takes 43ms to complete there, but yours is taking 1511ms which implies there is a timeout occurring, meaning most likely the build system you have isn't handling the load properly and dropping packets for some reason which is causing the retry scenario.  We can probably lower the threshold here as 256 DNS queries might be aggressive, but I'm honestly not sure what else to suggest.

**Comment by bradh352** [comment]
I just saw you had an strace there, looks like your system is just too slow to run that many tests before generating a timeout. 
 I had assumed it was processing a bunch really quick and had a couple dropped packets, but no, it was processing for the entire duration and then hit a timeout so it re-queued a few requests to new connections and finished up.

**Comment by bradh352** [comment]
try 9e542a8

**Comment by gjasny** [comment]
Thanks, that helped locally. Let's see if the build failures here vanish as well: https://buildd.debian.org/status/package.php?p=c-ares&suite=experimental
(It will take some hours until `1.20.0-2` will appear there)

**Comment by gjasny** [comment]
Looks good!
