### ISSUE TITLE
Support for SVCB and HTTPS RRs

### ISSUE THREAD

**Issue by bagder** [c-ares/c-ares#566]
Browsers have already adopted the HTTPS RR and other "web" clients may want to as well. In the @curl project we hope to start toying with HTTPS records soon.

Spec: https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/12/

Higher level explanation: https://developer.mozilla.org/en-US/docs/Glossary/HTTPS_RR

**Comment by bradh352** [comment]
Looks like they just released an official RFC https://datatracker.ietf.org/doc/rfc9460/
