### ISSUE TITLE
ESERVICE is undocumented

### ISSUE THREAD

**Issue by dimbleby** [c-ares/c-ares#586]
missing from the man pages, code comment not too enlightening
```
    /* More ares_getaddrinfo error codes */
    ARES_ESERVICE = 25 /* introduced in 1.?.0 */
```
this was introduced at #257: the question mark presumably representing "I don't know what future release this will appear in", but the missing documentation being an omission all along.

**Comment by bradh352** [comment]
Addressed sort of in #616 ... there's actually no docs at all for the ares_status_t codes, but I at least put a comment next to entry in the header.

**Comment by dimbleby** [comment]
not really.  docs for all of the functions on the API eg in particular `ares_getaddrinfo` say what values the status might take and what the meaning of that is.

**Comment by bradh352** [comment]
I'd bet that the lists aren't exactly accurate either :/

**Comment by dimbleby** [comment]
sure, it might be easier to delete that part of the documentation than fix it.  either way, the status codes _are_ currently documented and that is not currently accurate: imo the bug report stands

**Comment by bradh352** [comment]
I just threw that in the getaddrinfo docs
