### ISSUE TITLE
Make ares_dns_parse public

### ISSUE THREAD

**Issue by danielnilsson9** [c-ares/c-ares#587]
Hi

Many thanks for the continued work on this project. We just updated c-ares to 1.21 since I saw there had been some work on the dns response parsing code.

We have a custom resolver solution base on c-ares for delayed parallel resolve over multiple redundant networks and prioritization of responsive servers. 

Anyway we rely heavily on SRV records in our systems and since most DNS server pass the host->ip mapping as an additional A record along with the response we prefer to use that if available to avoid sending another query for the host. This means we cannot use ares_parse_srv_reply since it does not consider the additional records.

It would be nice if the new ares_dns_parse related functions were made public so we could use them instead of the macro based stuff in ares_dns.h. Would it be a good idea?

**Comment by bradh352** [comment]
Yep, that's the plan. I was going to let it bake for a release to make sure the API doesn't need any tweaking, then in the next release it should become public.  I didn't want to risk releasing a new extensive API like that then need to break compatibility because of some silly oversight.

**Comment by danielnilsson9** [comment]
Perfect, sounds like a good plan!

**Comment by bradh352** [comment]
done in #604 ... followup incoming for man pages
