### ISSUE TITLE
github release notification emails always have broken link for the changelog

### ISSUE THREAD

**Issue by matthewjmiller1** [c-ares/c-ares#588]
Not sure if this is something fixable in how the c-ares releases are published or some artifact of github doing URL mangling in its notification emails.

While on the [releases](https://github.com/c-ares/c-ares/releases) page, the changelog link is correct, the release notification email from github always has a broken link for the changelog. E.g., for 1.21.0, the link in the notification email is:

https://c-ares.org/download/changelog.html#1_21_0

Instead of:

https://c-ares.org/changelog.html#1_21_0

Not sure what is adding the extra "download/" in the path for the emails. All the other links in the email are correct except the changelog one.

**Comment by bagder** [comment]
Fixed now. Thanks for reporting!
