### ISSUE TITLE
Question on 'ares_sysconfig_files.c'

### ISSUE THREAD

**Issue by gvanem** [c-ares/c-ares#597]
Besides the functions `ares__parse_sortlist()` and `ares__init_by_environment()`, the file
`src/lib/ares_sysconfig_files.c` has IMHO no meaning for `USE_WINSOCK` or Windows at all.
Indicated by this warning from clang-cl:
```c
src/lib/ares_sysconfig_files.c(535,60): warning: format specifies type 'char *' but the argument has type 'void *' [-Wformat]
  535 |         DEBUGF(fprintf(stderr, "Error opening file: %s\n", PATH_RESOLV_CONF));
      |                                                     ~~     ^~~~~~~~~~~~~~~~
src/lib/ares_private.h(82,32): note: expanded from macro 'PATH_RESOLV_CONF'
   82 | #  define PATH_RESOLV_CONF     NULL
      |                                ^~~~
```

And the use of `ERRNO` == `GetLastError()` in tests for a failed `fopen()`;  `GetLastError()` is never valid here (but `errno` is).

So AFAICS this could be cleaned up like:
```diff
--- a/src/lib/ares_sysconfig_files.c 2023-11-06 06:24:26
+++ b/src/lib/ares_sysconfig_files.c 2023-11-06 08:50:01
@@ -476,6 +476,7 @@
   return ARES_SUCCESS;
 }

+#if !defined(USE_WINSOCK)
 ares_status_t ares__init_sysconfig_files(const ares_channel_t *channel,
                                          ares_sysconfig_t     *sysconfig)
 {
@@ -524,7 +525,7 @@
       goto done;
     }
   } else {
-    error = ERRNO;
+    error = errno;
     switch (error) {
       case ENOENT:
       case ESRCH:
@@ -552,7 +553,7 @@
       goto done;
     }
   } else {
-    error = ERRNO;
+    error = errno;
     switch (error) {
       case ENOENT:
       case ESRCH:
@@ -582,7 +583,7 @@
       goto done;
     }
   } else {
-    error = ERRNO;
+    error = errno;
     switch (error) {
       case ENOENT:
       case ESRCH:
@@ -612,7 +613,7 @@
       goto done;
     }
   } else {
-    error = ERRNO;
+    error = errno;
     switch (error) {
       case ENOENT:
       case ESRCH:
@@ -633,3 +634,4 @@

   return status;
 }
+#endif  /* !USE_WINSOCK */
```

And remove these function-prototypes in `ares_private.h` perhaps?

**Comment by bradh352** [comment]
This function was originally embedded into `init_by_resolvconf()` in ares_init.c, I extracted it into its own function and file.  You can see in ares_sysconfig.c's `ares__init_by_sysconfig()` all the original components of that original `init_by_resolvconf()` file that I split out into individual functions.

I made a decision not to wrap all the file parsing in
```
#if !defined(_WIN32) && !defined(__MVS__) && !defined(__riscos__) && !defined(WATT32) && !defined(ANDROID) && !defined(__ANDROID__) && !defined(CARES_USE_LIBRESOLV)
```

Sure it means that we add a couple of KB to the overall generated code size due to the file parsing existing on systems where its never called, I just hate wrapping code like that in nasty ifdefs.  I'll just switch the PATH_RESOLV_CONF to be "" instead of NULL by default and it will at least kill the warning emitted by clang.  Interesting that gcc doesn't emit the same warning.

**Comment by bradh352** [comment]
Just to clarify, this isn't my code at all, I just modularized it a bit in preparation of #301.  Its all due to be rewritten to get away from the hand-made parsers it currently uses as those just scare me, just like I've done for DNS response parsing and /etc/hosts parsing already.

**Comment by gvanem** [comment]
> I'll just switch the PATH_RESOLV_CONF to be ""

Or perhaps `"no-such-file-for-this-target"`?

And BTW, some places where there is `#ifdef WIN32` should really be `#ifdef USE_WINSOCK`.
The Watt-32 has stopped working due to this. Another issue I know.

**Comment by bradh352** [comment]
WATT32 is DOS right?  Or at least that's the only legit use case anymore, and I guess that would be in FreeDOS.  That's not really something I have the ability to test.  It would be useful if we could come up with some CI/CD build target if its something people still use.

**Comment by gvanem** [comment]
> WATT32 is DOS right?

It's for both MSDOS and Windows. Hence the need to separate `WIN32` from `USE_WINSOCK`.

**Comment by bradh352** [comment]
For my own curiosity, you say its used on windows, under what kind of circumstance?  Is this specifically to support some legacy windows (NT, 3.1), or can it be used on modern windows, and if so, what is the benefit?

If you can provide some guidance on how you are building, such as if you're using a cross-compiler (hopefully via pre-built packages), I'd like to tie it into the CI/CD system so we can automate such builds.

**Comment by gvanem** [comment]
Sorry for late reply.

>  Is this specifically to support some legacy windows (NT, 3.1), or can it be used on modern windows

From Win-XP till Win-11 using SWSsocket, WinPcap or NPcap as the *"network driver"*.

>  and if so, what is the benefit?

It's much more POSIX compatible than Winsock. E.g. porting [Matts Traceroute](https://github.com/traviscross/mtr) to Watt-32 on Windows was easy due to support for `res_query()`, `dn_expand()` etc.

*PS*. It would be nice with a Mtr version using C-ares instead (since the old `resolv.h` stuff is horrible). 
Maybe I have a go at it. But I'll close this issue now.
