### ISSUE TITLE
Not able to get query using queries_by_qid in code

### ISSUE THREAD

**Issue by sachusachin622** [c-ares/c-ares#605]
Hi I have one doubt related query in code in this file src/lib/ares_getaddrinfo.c and function name is find_query

+static struct query* find_query(ares_channel channel, unsigned short id,unsigned char *abuf, int alen)
+{
+  unsigned short qid;
+  struct list_node* list_head;
+  struct list_node* list_node;
+  struct query *query;
+
+  /* Find the query corresponding to this packet. */
+  query = NULL;
+  **list_head = &(channel->queries_by_qid[id % ARES_QID_TABLE_SIZE]);**
+  for (list_node = list_head->next; list_node != list_head;
+       list_node = list_node->next)
+    {
+       struct query *q = list_node->data;
+       if ((q->qid == id) && same_questions(q->qbuf, q->qlen, abuf, alen))
+       {
+      	query = q;
+        break;
+       }
+    }
+  if (query)
+    return query;
+  else
+    return NULL;
+} 

Here we are trying to get list_head using this **list_head = &(channel->queries_by_qid[id % ARES_QID_TABLE_SIZE]);** but failed to get list_head .
So because of this we are using **list_head = &(channel->all_queries);** to get list_head, Is that correct ? why we are not able to get list_head using queries_by_qid ? Is anything miss here.

C-ares version is **c-ares 1.19.0** we applied your patch from returning ipv4 or ipv6 address if any one of the address class is available.

Thanks,
Sachin

**Comment by bradh352** [comment]
What are you trying to accomplish overall?  This way of looking up queries no longer exists in c-ares, it uses a real hashtable implementation these days, so I'm going to close this as we only maintain a single branch of c-ares.
