### ISSUE TITLE
README claims 'best practices' from some unrelated project

### ISSUE THREAD

**Issue by dimbleby** [c-ares/c-ares#63]
Link in README is to `https://best practices.coreinfrastructure.org/projects/289`.

Obviously the space is unwanted.  

I'd submit a pull request fixing, but the fixed link takes me to some other project altogether ("JSON for Modern C++").   So I guess c-ares is also displaying that project's badge, and not its own.

I don't know how to guess what the correct link is.

**Comment by dimbleby** [comment]
Cool, thanks - but you've still got that unwanted space so that the link doesn't work.

**Comment by bagder** [comment]
Sorry, I'm just too sloppy. Took me two commits to fix that. Thanks for reporting!
