### ISSUE TITLE
c-ares 1.22.1 (and newer) does not change servers on a request timeout

### ISSUE THREAD

**Issue by b-spencer** [c-ares/c-ares#650]
If I understand correctly, with the new dynamic server list behaviour of #594, the first server in the server list is always used by `ares__requeue_query()`.  But, when a query times out in `process_timeouts()`, there is no call to `server_increment_failure()`, so the server list always stays in the same order, and thus the retry is send to the same server.

This means that when a DNS server is not responding, c-ares gets stuck querying it forever, at least in all the cases I've seen.  Real users often have misconfigurations such as non-functional IPv6 DNS server entries, etc.  If a "bad" server is first in the list, no DNS lookups work at all.

All other (similar) calls to `ares__requeue_query()` are preceded by a call to `server_increment_failure()`.  Adding that call in `process_timeouts()` immediately before `ares__requeue_query()` locally fixed the behaviour in my testing so far.

**Comment by bradh352** [comment]
Hmm, that seems really bad if true.  I thought the test cases handled the retry scenarios and would switch servers.  Let me investigate.

**Comment by bradh352** [comment]
ok, confirmed.  Created PR #651 which also adds a test case for this.  Once all CI/CD tests complete I'll merge into main as well as the 1.23 branch.
