### ISSUE TITLE
Question about 1.23.0: Multiple nameservers specified, only first one is used.

### ISSUE THREAD

**Issue by Flow86** [c-ares/c-ares#656]
Hi,

in my /etc/resolv.conf I have 3 nameservers specified

```
nameserver 127.0.0.1 # (currently not running)
nameserver 8.8.8.8
nameserver w.x.y.z  # (some other internal one)
```

I do a query with ares_query and all my requests do timeout.

I digged into it, and it tries 3 times 127.0.0.1 (thats what I see in wireshark) and where it never gets a response (of course, no nameserver is running there atm)
and then it times out after 6 seconds (error 12). 

It never tries to use a different nameserver, even though the maximum timeout has not been reached yet?
Shouldnt it fallback to the next one if the first one fails/timeouts but the MAX timeout is not reached yet?
Or how is it suppose to work?

```
ares_channel channel;
ares_options options;
int optmask = 0;

options.flags = ARES_FLAG_NOCHECKRESP;

options.maxtimeout = 3000; // 30 seconds
optmask |= ARES_OPT_MAXTIMEOUTMS;

ares_init_options(&channel, &options, optmask)

ares_query(channel, "example.com", ns_c_in, ns_t_a, my_callback, nullptr);

//...
```

**Comment by bradh352** [comment]
What version of c-ares are you using?  Have you tried the current c-ares main?

**Comment by bradh352** [comment]
Btw, MAXTIMEOUTMS is the most that a timeout can escalate to on a per-attempt level (basically once its tried all servers once with the default timeout, the timeout increases on the next pass), there is no aggregate attempt maximum timeout which is what it appears you are suggesting with your comments.

**Comment by bradh352** [comment]
likely your issue was resolved with https://github.com/c-ares/c-ares/commit/f24d7c9 last week i should mention, so the fix isn't yet in an official release

**Comment by bradh352** [comment]
The current main work for you?

**Comment by Flow86** [comment]
I'm sorry, I had no time to try it out yet. I hope I can get to it next week.

**Comment by bradh352** [comment]
1.24 is released which should resolve this issue.

**Comment by Flow86** [comment]
yes, that solves the issue. thank you
