### ISSUE TITLE
getrandom never-ending busy-loop

### ISSUE THREAD

**Issue by bagder** [c-ares/c-ares#660]
In [this](https://github.com/curl/curl/issues/12517#issuecomment-1855401746) curl issue, someone uses c-ares in a system where getrandom returns -1 with errno set to `ENOSYS`. It makes c-ares get stuck in a never-ending loop here:

https://github.com/c-ares/c-ares/blob/290e9e951c7bc906e20b82817747b118c350c759/src/lib/ares_rand.c#L274-L282

**Comment by bradh352** [comment]
Interesting that the system would have getrandom but the kernel not support it.  We can implement a fallback for this case.

**Comment by bradh352** [comment]
fixed in #661
