### ISSUE TITLE
ares_addrinfo_callback won't be called when invoke ares_cancel/ares_destroy if ai_flags set to AF_UNSPEC and only part of query done

### ISSUE THREAD

**Issue by FrancisHe** [c-ares/c-ares#662]
I set my own timeout outside c-ares, if timeout ocurrs, `ares_cancel`/`ares_destroy` will be called. I found that `ares_addrinfo_callback` hasn't been invoked. After i use tcpdump capture the network packets, i fount that the A record reply have received, but the AAAA record havn't.
The c-ares version is `cares-1_23_0`, and use TCP (`ARES_FLAG_USEVC` is set).

**Comment by FrancisHe** [comment]
https://github.com/FrancisHe/lightnet/blob/c3a16e07279476b85c12acf643b510e68aa13f05/dns/dns_test.cpp#L109C22-L109C22

Here is the code, set timeout to 100ms (or other value), uncomment the line `resolver->SetServers("8.8.8.8,8.8.4.4");` to use local dns server. The line `resolver.reset();` will call ares_destroy.

Build the code using `lightnet/build.sh` with option `--debug`, you will find `AresResolver::Query::OnGetAddrInfoCallback` not being invoked according to the debug output message.

**Comment by bradh352** [comment]
I should be able to look into this tomorrow.

**Comment by bradh352** [comment]
Adding a test case in c-ares I'm not able to see the behavior you describe.  The callback is definitely called, however, since there is a partial result, it is returning that partial result rather than ARES_ECANCELLED which I'm not sure if that's intentional or not.

```
[ RUN      ] AddressFamiliesAI/MockChannelTestAI.PartialQueryCancel/0
Configured IPv4 mock server with TCP socket 3 on port 57588 and UDP socket 4 on port 56671
Configured library with servers:127.0.0.1:56671
ares_cancel will be called after 100ms
received UDP request REQ QRY RD  Q:{'example.com' IN A} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 56671
ProcessRequest(62502, 'example.com', A)
sending reply RSP QRY AA NOERROR Q:{'example.com' IN A} A:{'example.com' IN A TTL=256 1.2.3.4} on port 56671
received UDP request REQ QRY RD  Q:{'example.com' IN AAAA} ADD:{'' MAXUDP=1280 OPT RCODE2=0 } on port 56671
ProcessRequest(62054, 'example.com', AAAA)
Issuing ares_cancel()
AddrInfoCallback({ARES_SUCCESS {addr=[1.2.3.4]}})
select() failed, errno 9
/Users/bhouse/svn/c-ares-bradh352/test/ares-test-mock-ai.cc:470: Failure
Expected equality of these values:
  ARES_ECANCELLED
    Which is: 24
  result.status_
    Which is: 0
```

You can see the code for the test case in my private branch: https://github.com/bradh352/c-ares/tree/cancel

**Comment by bradh352** [comment]
See PR #663, I'm guessing your code may be depending on the result code, and I think ARES_ECANCELLED is more appropriate.  Anyhow, the test case confirms the behavior works as expected.

**Comment by FrancisHe** [comment]
> See PR #663, I'm guessing your code may be depending on the result code, and I think ARES_ECANCELLED is more appropriate. Anyhow, the test case confirms the behavior works as expected.

Yes, the result is actually what you guess. I add some debug log confirmed that ares_addrinfo_callback returns ARES_SUCCESS when the channel is destroying.
