### ISSUE TITLE
Wrong function signature for ares__iface_ips_enumerate in ares__iface_ips.c

### ISSUE THREAD

**Issue by rainerjung** [c-ares/c-ares#668]
In file ares__iface_ips.c line 512 the definition of ares__iface_ips_enumerate does not match the declaration in line 62 and also not the other definitions of it. The second argument has to be removed, so instead of 

```
static ares_status_t ares__iface_ips_enumerate(ares__iface_ips_t     *ips,
                                               ares__iface_ip_flags_t flags,
                                               const char            *name)
{
  (void)ips;
  (void)flags;
  return ARES_ENOTIMP;
}
```

is should be

```
static ares_status_t ares__iface_ips_enumerate(ares__iface_ips_t     *ips,
                                               const char            *name)
{
  (void)ips;
  return ARES_ENOTIMP;
}

```

Compilation error happens on Solaris 10 with gcc:

ares__iface_ips.c:512:22: error: conflicting types for 'ares__iface_ips_enumerate'
  512 | static ares_status_t ares__iface_ips_enumerate(ares__iface_ips_t     *ips,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~
ares__iface_ips.c:62:22: note: previous declaration of 'ares__iface_ips_enumerate' was here
   62 | static ares_status_t ares__iface_ips_enumerate(ares__iface_ips_t *ips,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bradh352** [comment]
Thanks for the report, this should now be resolved with d05878f
