### ISSUE TITLE
5K domains in one query, there are some timeout expiration issues

### ISSUE THREAD

**Issue by 0xdddddddd** [c-ares/c-ares#681]
My development environment is Windows 

I specify the relevant parameters when initializing cares

ctx->ares_opts->timeout = 500;
ctx->ares_opts->tries = 5;
ctx->ares_opts->tcp_port = 53;
ctx->ares_opts->udp_port = 53;
ctx->ares_opts->socket_send_buffer_size = (100 * 1024 * 1024);
ctx->ares_opts->socket_receive_buffer_size = (100 * 1024 * 1024);
ctx->ares_opts->lookups = "fb";
ctx->ares_opts->sock_state_cb_data = ctx;
ctx->ares_opts->sock_state_cb = ik_resolver_state_cb;
ctx->ares_opts->udp_max_queries = 1;
ctx->ares_opts->maxtimeout = ctx->ares_opts->tries * ctx->ares_opts->timeout + 2000;

res_init_options((ares_channel_t**)&ctx->ares_channel, ctx->ares_opts,
						  ARES_OPT_EDNSPSZ | ARES_OPT_SERVERS |
						  ARES_OPT_FLAGS | ARES_OPT_NOROTATE |
						  ARES_OPT_TIMEOUTMS | ARES_OPT_MAXTIMEOUTMS | ARES_OPT_TIMEOUTMS | ARES_OPT_TIMEOUTMS | ARES_OPT_TRIES
						  ARES_OPT_TRIES | ARES_OPT_SOCK_STATE_CB | ARES_OPT_LOOK_CB | ARES_OPT_SOCK_STATE_CB
						  ARES_OPT_LOOKUPS | ARES_OPT_UDP_PORT | ARES_OPT_UDP_PORT | ARES_OPT_TCP_PORT_PORT
						  ARES_OPT_TCP_PORT | ARES_OPT_UDP_MAX_QUERIES | ARES_OPT_SOCK_STATE_CB
						  ARES_OPT_SOCK_SNDBUF | ARES_OPT_SOCK_RCVBUF

Calls via ares_getaddrinfo

Using libuv poll combined with c-ares

I set the "ares_opts->sock_state_cb" callback

When one of the readable or writable arguments is not 0, I enable the 
uv_poll_init_socket
uv_poll_start
Otherwise, I close the poll with uv_close when both variables are zero.

When the poll receives a response.
I call ares_process_fd

**Comment by bradh352** [comment]
With udp_max_queries=1, you'd open 5000-10000 file descriptors, one per request (depending on if you use AF_UNSPEC vs AF_INET or AF_INET6).  I have no idea how libuv handles large numbers of file descriptors on Windows. 

What testing have you done?
 * Have you tried another OS, like Linux?
 * Have you tried setting udp_max_queries to a higher value (or not setting it at all)
 * Have you tried increasing the timeouts?
 * Have you verified the Windows `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters` `MaxUserPorts` value has been increased from the defaults?  If not, you're likely getting socket creation failures.

**Comment by 0xdddddddd** [comment]
> With udp_max_queries=1, you'd open 5000-10000 file descriptors, one per request (depending on if you use AF_UNSPEC vs AF_INET or AF_INET6). I have no idea how libuv handles large numbers of file descriptors on Windows.
> 
> What testing have you done?
> 
> * Have you tried another OS, like Linux?
> * Have you tried setting udp_max_queries to a higher value (or not setting it at all)
> * Have you tried increasing the timeouts?
> * Have you verified the Windows `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters` `MaxUserPorts` value has been increased from the defaults?  If not, you're likely getting socket creation failures.

It's not a matter of the port being full or the socket creation failing.

I am trying to use
netsh int ipv4 show dynamicportrange protocol=tcp
netsh int ipv4 set dynamicportrange protocol=tcp start=1025 num=64511
netsh int ipv4 show dynamicportrange protocol=udp
netsh int ipv4 set dynamicportrange protocol=udp start=1025 num=64511
Changed the dynamic port range on my current system so that it can be maximized.

But the problem still exists.

I'm trying to reduce the parameters, right now I'm only setting the basic parameters.

	if (ctx->ares_opts) {
		ctx->ares_opts->timeout = CARES_TIMEOUT_PER_ATTEMPT;
		ctx->ares_opts->sock_state_cb_data = ctx;
		ctx->ares_opts->sock_state_cb = ik_resolver_state_cb;
	}

	if (ares_init_options((ares_channel_t**)&ctx->ares_channel, ctx->ares_opts, ARES_OPT_TIMEOUTMS |
						  ARES_OPT_SOCK_STATE_CB

	) ! = ARES_SUCCESS) {
		return -1;
	}

The situation is still partially lost for timeout situations. Socket creation failures I think should be impossible

**Comment by bradh352** [comment]
And you're sure your upstream DNS server isn't rate limiting your requests?  Have you used wireshark or similar to see how many requests hit the wire and how many responses come back?

**Comment by 0xdddddddd** [comment]
> And you're sure your upstream DNS server isn't rate limiting your requests? Have you used wireshark or similar to see how many requests hit the wire and how many responses come back?

Whether or not there are limitations on the upstream servers is irrelevant to the topic of my question, the

The problem I pointed out is the topic of the "timeout" timeout expiration.

Even if the upstream dns servers are not responding, then the timeout should still be in effect.

Tomorrow I'm willing to write as small a demo as possible using libuv+c-ares to reproduce the problem.

**Comment by bradh352** [comment]
Maybe I don't know what you are saying the issue is then.  What is "timeout" timeout expiration, what does that mean?  Can you better explain what you are seeing vs what you are expecting to see?

**Comment by 0xdddddddd** [comment]
> Maybe I don't know what you are saying the issue is then. What is "timeout" timeout expiration, what does that mean? Can you better explain what you are seeing vs what you are expecting to see?

for example:
ares_opts ARES_OPT_TIMEOUTMS=2000MS

Theoretically, if the DNS upstream server does not respond, ares must also enable the timeout to enter ares_opts->sock_state_cb callback normally.

Now the problem I have is that the timeout event is not working.

**Comment by bradh352** [comment]
There's no guarantee that when one query times out it will call sock_state_cb if there are other queries when the timeout expires, its only on socket state changes that the callback will be called.

Also, remember that the timeout specified is the *minimum* timeout *per server*, *per attempt*.  If you have 5 servers, and 5 attempts (per server!), and a 2000ms timeout, the *minimum* time it will take if all servers are non-responsive is 5*5*2000, but likely more as there are additional penalties added for subsequent attempts to the same server that has already been tried.

**Comment by 0xdddddddd** [comment]
> There's no guarantee that when one query times out it will call sock_state_cb if there are other queries when the timeout expires, its only on socket state changes that the callback will be called.
> 
> Also, remember that the timeout specified is the _minimum_ timeout _per server_, _per attempt_. If you have 5 servers, and 5 attempts (per server!), and a 2000ms timeout, the _minimum_ time it will take if all servers are non-responsive is 5*5*2000, but likely more as there are additional penalties added for subsequent attempts to the same server that has already been tried. I'm talking about the callback registered to `ares_getaddrinfo()` in receiving the timeout condition.

I think what you said is not correct. I also understand the timeout accumulation mechanism introduced in the official documents.

I'll write a very small example to illustrate the problem.

**Comment by 0xdddddddd** [comment]
@bradh352 

[main.zip](https://github.com/c-ares/c-ares/files/13868601/main.zip)

This is a minimal example with only 190 lines of code.

Compiling it requires gcc + libuv + c-ares

**Comment by 0xdddddddd** [comment]
> Well, you don't have any timers set in libuv to allow c-ares to handle timeouts. I've never used libuv, but I added timeout handling code to your test case (I didn't see a way to pass an argument to the callback, but I didn't look very hard so I used the global) and it completes. However, not all queries are successful, a good portion timeout due to flooding of the nameserver and rate limiting. Also, you made some assumptions I added asserts for to enforce (like ares_socket_t being at most 65535, but nothing guarantees that).
> 
> [main-2.zip](https://github.com/c-ares/c-ares/files/13874740/main-2.zip)

I originally thought that c-ares can handle timeouts by itself, but I misunderstood. Those fds that have not received a select response can only wait forever, so we need to make a timer to manually stop some fds that have timed out.
