### ISSUE TITLE
c-ares-1.12.0.tar.gz doesn't include msvc_ver.inc

### ISSUE THREAD

**Issue by brucestephens** [c-ares/c-ares#69]
The file's in the repository and seems to be required by `Makefile.msvc`.

**Comment by bagder** [comment]
Thanks for reporting, fixed now for next release!

**Comment by daviddrysdale** [comment]
@bagder, how are the release tarballs generated?  I'm thinking it might be worth adding extra steps in the Travis/AppVeyor builds to create the tarballs, then move into a subdirectory and try a clean build.  (Maybe doing `make distcheck` might cover this, I'm not sure.)

**Comment by bagder** [comment]
The release tarballs as well as the [daily snapshots](https://libssh2.org/snapshots/) are made with the `maketgz` script in the source tree root. It is basically a wrapper script around `make dist`, so a `make distcheck` should be a decent check that it works. But I doubt it would have found this particular problem...

**Comment by daviddrysdale** [comment]
Yeah, it wouldn't have found this as it's Windows-specific.  However...it did discover that the `test/` code isn't buildable from the tarballs!
