### ISSUE TITLE
Inconsistent wording

### ISSUE THREAD

**Issue by gvanem** [c-ares/c-ares#692]
In this example `adig -s 4.4.4.4 -t a localhost`, I get this *response* after 12 sec:
`;; Got answer: Timeout while contacting DNS servers`

Well, there's no answer so the `;; Got answer:` should be dropped for `Locally generated errors` IMHO.
How about:
```diff
--- a/src/tools/adig.c 2024-01-17 02:03:28
+++ b/src/tools/adig.c 2024-01-17 02:44:53
@@ -743,7 +743,8 @@
   (void)arg;
   (void)timeouts;

-  printf(";; Got answer:");
+  /* We got a "Server status" */
+  if (status >= ARES_SUCCESS && status <= ARES_EREFUSED)
+     printf(";; Got answer:");
+  else
+     printf(";;");

   if (status != ARES_SUCCESS) {
     printf(" %s", ares_strerror(status));
   }
```
Giving: `;; Timeout while contacting DNS servers`

Comparable to `dig @4.4.4.4 -t a localhost`: `;; connection timed out; no servers could be reached`

I fail to a macro/function to differentiate `Server error codes` and `Locally generated error codes` as
`ares.h` calls these. Maybe there should be one?

**Comment by bradh352** [comment]
I committed your change, thanks. I'll open another ticket on the internal error codes vs server error codes.  Really I've been reusing existing codes when I should have been adding some new ones for some of the new features.
