### ISSUE TITLE
threadsafety has become mandatory in 1.26.0

### ISSUE THREAD

**Issue by dimbleby** [c-ares/c-ares#699]
I guess this is an accident.

`ares_init_options()` fails if `ares__channel_threading_init()` fails, which fails if `ares_threadsafety()` returns false

**Comment by bradh352** [comment]
Hrm, yeah, looks like that regression is an oversight, I'll get that fixed.  Obviously I'd recommend building with threading, especially since new features in 1.26.0 depend on it (the eventthread).

**Comment by dimbleby** [comment]
you may recall I'm the one with the rust wrapper: so I get my thread-safety from the compiler and have no need to pay the extra cost

(I also have an event-loop integration built on top of that already - https://github.com/dimbleby/c-ares-resolver/ - and don't have plans to expose the new built-in event thread separately)

**Comment by bradh352** [comment]
Once #613 gets implemented, you may want to reconsider that as it will require the eventthread to be in use to use that feature.

**Comment by dimbleby** [comment]
unless and until I get users telling me they want them, I mostly don't expect to bring the new crop of funky c-ares features into the rust wrapper - and then those users will likely be invited to submit merge requests themselves!

I'm really just keeping it ticking over, making as few changes as I can get away with.  

(Backwards compatibility is also a challenge: it is desirable for at least some of my users that the rust crate continues to work with the old c-ares versions packaged by various distros.  The more new stuff I support, the more complex that becomes)

**Comment by bradh352** [comment]
heh, c-ares won't go too crazy in features.  there's only so much you do with a dns resolver :)

but I get your point.

Honestly, I'm just doing things that should have been done 10-20 years ago with the project, we're still not even feature parity with the native system resolver on Linux, MacOS, and Windows when it comes to some things.  Namely missing DNS Cookies (for security), mDNS support, automatic re-read of system config on changes, DoH.
