### ISSUE TITLE
Why ares_gethostbyname query only AF_INET6 if family parameter set to AF_UNSPEC?

### ISSUE THREAD

**Issue by weastur** [c-ares/c-ares#70]
By default POSIX getaddrinfo return both(either IPv4 and IPv6) if family set to AF_UNSPEC.

**Comment by bagder** [comment]
Because it hasn't been implemented. We'll appreciate patches and help to make it do the right thing!

**Comment by dimbleby** [comment]
Seems not so easy since `c-ares` has chosen to return the answers to `ares_gethostbyname` in a `hostent` - which can hold a list of IPv4 addresses, or a list of IPv6 addresses, but not a mix.

So some interface change would be needed.

**Comment by bagder** [comment]
Right, a c-ares version of getaddrinfo() would be preferable I think.

**Comment by ChristianAmmer** [comment]
Should the title not be renamed to explicitly asking for `ares_getaddrinfo`?

**Comment by hennna** [comment]
My understanding of AF_UNSPEC is that first AF_INET6 is queried and then AF_INET. However, when calling ares_gethostbyname(... "localhost", ... AF_UNPEC, ...), I get the IPv4 address 127.0.0.1 even though my system supports IPv6. Is this behavior expected?

**Comment by bagder** [comment]
Many systems have `127.0.0.1 localhost` in /etc/hosts, meaning that c-ares won't resolve to an IPv6 address on those. ip6-localhost or similar is then commonly used for the IPv6 version.

**Comment by bradh352** [comment]
ares_getaddrinfo now exists, closing
