### ISSUE TITLE
Comment issues.

### ISSUE THREAD

**Issue by dzalyalov88** [c-ares/c-ares#722]
The following methods have incorrect (not doxygen-style) comments:
1. ares_dns_record.h:399
Should be:
/*! Parse Additional from later RFCs (no name compression) as RAW */

2. ares_dns_record.h:472
Should be:
\param[out]    out_len Length of binary form address

3. ares__buf.h:180
Should be:
\param[in] len      Length of data to hexdump

4. ares__buf.h:539
Should be: 
\param[out] name           Pointer passed by reference to be filled in with

5. ares__htable.h:89
Should be: 
 *  \param[in] htable initialized hashtable

6. ares__htable_asvp.h:74
Should be: 
 *  \param[out] num      Count of returned keys
 
7. ares__llist.h:205
Should be: 
 * \param[in] new_parent new list

8. ares__llist.h:214
Should be: 
 * \param[in] new_parent new list

**Comment by bradh352** [comment]
Thanks! fixed in 8cfe116
