### ISSUE TITLE
Potential memory leak in  ares_init.c  - init_by_defaults()

### ISSUE THREAD

**Issue by lthuressonhs** [c-ares/c-ares#724]
There is a potential memory leak when init_by_defaults() function returns with error.
Fixed it with this patch

--- src/lib/ares_init.c.org     2024-02-23 08:23:02.000000000 +0100
+++ src/lib/ares_init.c 2024-03-12 16:10:13.107757585 +0100
@@ -262,12 +262,10 @@
 
 error:
   if (rc) {
-    if (channel->domains && channel->domains[0]) {
-      ares_free(channel->domains[0]);
-    }
     if (channel->domains) {
-      ares_free(channel->domains);
+      ares__strsplit_free(channel->domains, channel->ndomains);
       channel->domains = NULL;
+      channel->ndomains = 0;
     }

**Comment by lthuressonhs** [comment]
That formatting in the previous comment didn't turn out well... 
I hope you can see the problem anyway.

**Comment by bradh352** [comment]
Fixed in 06a20d7

**Comment by lthuressonhs** [comment]
That was fast.
Thanks!
/Leif
Leif Thuresson
+46 73 363 00 46  [https://static.fortra.com/email-signatures/fta-triangle-green-9x8.png]  fortra.com<https://www.fortra.com/>

________________________________
