### ISSUE TITLE
ares-test-live Error

### ISSUE THREAD

**Issue by navinagaraj** [c-ares/c-ares#726]
Facing the issue while testing a " ./arestest " in latest version 1.27.0

**Error Log:**     [c-ares-1.27.0-error-log.txt](https://github.com/c-ares/c-ares/files/14603063/c-ares-1.27.0-error-log.txt)

**Comment by bradh352** [comment]
That is looking up localhost via /etc/hosts ... so if your /etc/hosts doesn't have a definition for localhost for both ipv4 and ipv6 you'll get that failure.

**Comment by navinagaraj** [comment]
Thank you, @bradh352, for your quick responses!

**Comment by navinagaraj** [comment]
Please note that in our test suite utilizing Google Test and Google Mock, I have identified two disabled tests: **LibraryInit.DISABLED_InvalidParam** and **LibraryTest.DISABLED_ParseAReplyVariantCnameLast**. It's expected that these tests remain disabled until further notice.

**Comment by bradh352** [comment]
what do you mean by your last comment, not sure what you're getting at

**Comment by navinagaraj** [comment]
While running the arestest test suite, it appears that two test cases are disabled. Is there any requirement for additional packages to enable them?

```
# ./arestest
[==========] Running 1050 tests from 54 test suites.
.
.
[ DISABLED ] LibraryInit.DISABLED_InvalidParam
.
.
.
[ DISABLED ] LibraryTest.DISABLED_ParseAReplyVariantCnameLast

[==========] 1050 tests from 54 test suites ran. (174716 ms total)
[  PASSED  ] 1050 tests.

  YOU HAVE 2 DISABLED TESTS
```

**Comment by bradh352** [comment]
whoever wrote those tests many years ago marked them as disabled.  I just removed them completely to prevent confusion in 7d455ba

**Comment by navinagaraj** [comment]
Thanks  **@bradh352** .
