### ISSUE TITLE
ares_parse_txt_reply_ext does not parse multiple TXT values after 1.20.1 version

### ISSUE THREAD

**Issue by ornotnull** [c-ares/c-ares#738]
ares_parse_txt_reply_ext joins values like ares_parse_txt_reply

**Comment by bradh352** [comment]
There was a behavior difference here, it joins single *long* txt records automatically.  A single TXT record must be split on 256byte boundaries in the raw DNS packet, those logically get joined in the new DNS parser as they are continuations not independent records.

Multiple TXT records however are separated and not joined with eachother.

This is for conformance to RFC 7208.

**Comment by ornotnull** [comment]
RFC7208 is just about SPF

TXT type RR is more generic, defined by rfc1035:
TXT-DATA    One or more <character-string>s.
could be used for any custom purpose, not only SPF

ares_parse_txt_reply_ext of 1.20.1 allows to read the strings separately
and now this feature is just lost

**Comment by bradh352** [comment]
What is the use case that needs this? The spf rfc, while true it's about
spf, it sets a precedent that other rfcs have to abide by due to the
specific wording since you don't know if the txt record is used for spf
when parsing the message.

If you can point to contradicting rfcs that makes use of the txt record
segmentation for some specific purpose we can evaluate how to handle that,
but without a legitimate usecase there's no reason for the prior behavior
to have existed.

**Comment by wildegnux** [comment]
The use case for this is for example getting AS data from routeviews (https://www.routeviews.org/bkup.index.html) as they publish AS, prefix and prefix length as separate character-strings:
```
❯ dig TXT 100.147.250.142.asn.routeviews.org
;; ANSWER SECTION:
100.147.250.142.asn.routeviews.org. 21600 IN TXT "15169" "142.250.147.0" "24"
```
I see no wording in RFC 7208 that suggests DNS implementations should flatten sets of characters strings. In section 3.3 it says:
```
As defined in [[RFC1035](https://datatracker.ietf.org/doc/html/rfc1035)], Sections [3.3](https://datatracker.ietf.org/doc/html/rfc7208#section-3.3) and [3.3.14](https://datatracker.ietf.org/doc/html/rfc7208#section-3.3.14), a single text DNS
   record can be composed of more than one string.  If a published
   record contains multiple character-strings, then the record MUST be
   treated as if those strings are concatenated together without adding
   spaces.
``` 
I.e. implementers of SPF (not DNS resolvers) should treat multiple character-strings as concatenated without separators. This is has been a solved problem for the last ~20 years. SPF implementers already do this. Further, RFC 7208 mentions this in the context of multiple character-strings having strings longer than 255 octets:
```
   TXT records containing multiple strings are useful in constructing
   records that would exceed the 255-octet maximum length of a
   character-string within a single TXT record.
```
And the functionality of that use case is unchanged with this later versions of c-ares, as a 300 character record will still be represented by an octet with the value 255, followed by 255 characters of the content, an octet with the value 45 and then 45 characters of content. The only thing this new implementation does is break anything that relies on the separation of records shorter than 255 characters. Like anything that tries fetching from routeviews AS data.

**Comment by bradh352** [comment]
Now that you have provided a use-case, I can reopen this issue and evaluate what needs to happen to address this.

**Comment by malaporte** [comment]
I have a similar issue ... we use this old-ass service discovery thing called Eureka (from Netflix but I don't think they maintain it anymore). Anyway, they use a TXT record to populate a list of value used to resolve per-AZ hosts:

```
dig TXT txt.us-east-1.develop.cloud.coveo.com

; <<>> DiG 9.10.6 <<>> TXT txt.us-east-1.develop.cloud.coveo.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14868
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;txt.us-east-1.develop.cloud.coveo.com. IN TXT

;; ANSWER SECTION:
txt.us-east-1.develop.cloud.coveo.com. 60 IN TXT "us-east-1a.develop.cloud.coveo.com" "us-east-1c.develop.cloud.coveo.com"

;; Query time: 195 msec
;; SERVER: 10.254.0.4#53(10.254.0.4)
;; WHEN: Tue Jun 25 11:20:16 CEST 2024
;; MSG SIZE  rcvd: 148
```

After a bunch of automated dependency updates, it stopped resolved properly, which after some digging led me here :) The value returned by `dns.resolveTxt` is now a concatenation of the two values you see above.

I'm no DNS expert to say whether whatever they do is a good thing or not, but sharing as FYI.

**Comment by bradh352** [comment]
PR #801 should restore the expected behavior now

**Comment by ornotnull** [comment]
@bradh352, thank you!
