### ISSUE TITLE
Deadlock in ares_queue_wait_empty

### ISSUE THREAD

**Issue by johnthacker** [c-ares/c-ares#742]
https://github.com/c-ares/c-ares/blob/fd81f36d3e8135a9c49018849fa16dc52c63b089/src/lib/ares__threads.c#L571-L589

There's nothing to cancel or timeout or server the pending requests and break out of the loop in the `tms == 0` case. If the timeout is short enough that it expires while, e.g., waiting to obtain the mutex, then while the status is set to `ARES_ETIMEOUT`, the mutex isn't released (unlike the other branches which call `ares__thread_cond_timedwait`, which releases the mutex while waiting), and so the event thread when calling `ares_process_fd` cannot obtain the channel lock, `channel->all_queries` never decreases and the while loop never exits.

I believe the intention is to simply return `ARES_ETIMEOUT` and let the caller decide to perhaps call `ares_cancel`, though I'm not sure.

**Comment by bradh352** [comment]
you're right, it looks like when timeout_ms > 0 its missing logic to break out of the loop when a timeout condition is actually hit and will only actually break out when the query count is zero.

**Comment by johnthacker** [comment]
I added a `break` statement after line 583 in a local fork and that seems to work for me (releases the mutex, returns `ARES_ETIMEOUT`, then it's the caller's job to call `ares_cancel` presumably.) Happy to submit a PR.

**Comment by bradh352** [comment]
proper line was 587, just committed that and backported to the relevant branches, thanks for the report!

**Comment by Vizonex** [comment]
I have been having a similar problem with [Cyares](https://github.com/Vizonex/cyares) where cancelling tasks triggers deadlocks. I have no way to fix it currently fix it but I believe this function to be the main culprit or maybe by pycares ties using a daemon to cleanup channels.

**Comment by Vizonex** [comment]
I could make a PR myself if that helps solve anything however.
