### ISSUE TITLE
ARES_OPT_EVENT_THREAD and running queries in parallel

### ISSUE THREAD

**Issue by Asmod4n** [c-ares/c-ares#751]
Hello, it seams like you can't run queries in parallel when ARES_OPT_EVENT_THREAD is used.
each call to ares_getaddrinfo gets run in the order they were issued, making it seam to be no faster than calling getaddrinfo instead.

How can one tell ares to wait to run its event loop?
I usally issue 2-4 queries at once and then call ares_process_fd while using ARES_OPT_SOCK_STATE_CB, its then finished in the order the servers have answered and not in the order the queries were issued.

**Comment by bradh352** [comment]
Can you clarify how you have come to this conclusion?  The event thread is meant to allow parallelization.  Infact, it does just as you said you do externally, it uses sock_state_cb and ares_process_fd internally.  The event thread is bolt-on and not some deep invasive change to c-ares, its just meant to just replace the complexities of needing your own event loop and therefore wouldn't have any behavior differences than your own event loop (with the exception it is guaranteed to be in a separate thread, some users run their own event loop only when needed in their main application thread).  

The only thing I can think of is if you are somehow doing something "bad" in your code that causes the c-ares channel lock to be held.  For instance any ares callbacks for things like ares_getaddrinfo() are holding a channel lock for the duration of the callback and therefore cannot process any additional responses until your code has returned from the callback.  You need to make sure any processing in the callback is as minimal as possible to return control... this is the limiting factor in how many requests c-ares can process in parallel.

**Comment by Asmod4n** [comment]
Is ares_process_fd called after every usage of ares_getaddrinfo then? that would be the issue then, i would need a way to defer the calling of that.
I've tried to look for that myself but i'm not fimilar with the codebase and couldn't find the answer myself.

**Comment by Asmod4n** [comment]
To elaborate a bit: lets say you request 4 lookups from 4 different dns servers, one of those 4 servers answer in 700 ms, but the other 3 only take 10 ms.
when doing batching with ARES_OPT_SOCK_STATE_CB and issue all 4 requests at once its all done in 700 ms, and the three that only take 10 are done first.

It looks like the threadding approach would wait for the 700 ms reply and then get the 10 ms answers back one after another if one happens to be unlucky and request the answer from the slow server first.

**Comment by Asmod4n** [comment]
I was mistaken, it actually runs in parallel.

**Comment by bradh352** [comment]
ares_process_fd() is called whenever select/poll/epoll/kqueue/iocp states the socket state has changed for something being monitored (as requested by a sock_state_cb).  Or when a timeout needs to be processed as per the time returned by ares_timeout().  ares_getaddrinfo() doesn't directly call ares_process_fd(), however it can create new sockets and also perform send() requests on the sockets (which it does regardless of using the event thread or not).
