### ISSUE TITLE
Bug: Issue with corrupted DNS records when converted back to a buffer in callback (ares_send)

### ISSUE THREAD

**Issue by eriklax** [c-ares/c-ares#757]
When using the API of ``ares_send`` the internal process of converting a `ares_dns_record_t` back to a buffer using ``ares_dns_write`` may occasionally corrupt the record. I've located the issue to the ``ares_dns_write_rr`` function. The problem occurres when `allow_compress` is true.

As an example, the following command ``./bin/adig -t MX fip.it`` should return

```
fip.it.		5709	IN	MX	10 libra2.fip.it.
fip.it.		5709	IN	MX	10 libra1.fip.it.
```

but returns since https://github.com/c-ares/c-ares/commit/e862d1faccbe6c34d96ca2bf63d819861159938f it returns trhis

```
fip.it.		5703	IN	MX	10 fip.it.
fip.it.		5703	IN	MX	10 fip.it.
```

Forefully disable `allow_compress` fixes this.

https://github.com/c-ares/c-ares/blob/fd620e0308888d7db4c9a1a4dd21a5e27284c40d/src/lib/ares_dns_write.c#L858-L861

**Comment by bradh352** [comment]
thanks for the report, a fix has been committed for this issue

**Comment by eriklax** [comment]
Thanks, would this justify a patch release for 1.28 or how far out is 1.29?

**Comment by bradh352** [comment]
yes it definitely would.  I'll work with @bagder about getting a new release out the door.  Its about time for 1.29 anyhow.
