### ISSUE TITLE
Windows: `NotifyIpInterfaceChange()` does not notify on manual dns config changes

### ISSUE THREAD

**Issue by bradh352** [c-ares/c-ares#761]
If a system administrator were to manually update the dns configuration, `NotifyIpInterfaceChange()` nor `NotifyUnicastIpAddressChange()` will trigger the event callback.  I would think `NotifyIpInterfaceChange()` would be called with `MibParameterNotification` since an interface parameter changed, but its not.

Perhaps this is a bug in Windows?  There is no means to get a notification otherwise, we'd literally have to just query `GetAdapterAddresses()` to enumerate all the DNS servers every few seconds (in a different thread as who knows how long that request might take), which seems wasteful.

See PR #759 for the implementation of change detection.

Opened a ticket with Microsoft:
https://learn.microsoft.com/en-us/answers/questions/1692011/notifyipinterfacechange-function-(netioapi-h)-does?comment=question#newest-question-comment
Someone replied saying to use RegNotifyChangeKeyValue() to monitor HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\Interfaces and HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces

**Comment by sykhro** [comment]
Using `RegNotifyChangeKeyValue()` broke our builds. we are using c-ares on Xbox, which implements a subset of Win32 lacking this and other functions (the entirety of `winreg.h` I fear, see `WINAPI_PARTITION_GAMES`).

Would you accept a PR which makes this check conditional?

**Comment by bradh352** [comment]
> Using `RegNotifyChangeKeyValue()` broke our builds. We are using c-ares on Xbox, which implements a subset of Win32 lacking this and other functions (the entirety of `winreg.h` I fear, see `WINAPI_PARTITION_GAMES`).
> 
> Would you accept a PR which makes this check conditional?
> 
> _(none of this is covered by NDA, such information is publicly available in the Windows docs)_

Sure. send a PR.  The goal of c-ares is to be as portable as possible.  Not sure how to build for xbox, but if possible we should also add a CI/CD target to auto-build to make sure we don't regress in the future.

**Comment by sykhro** [comment]
> > Using `RegNotifyChangeKeyValue()` broke our builds. We are using c-ares on Xbox, which implements a subset of Win32 lacking this and other functions (the entirety of `winreg.h` I fear, see `WINAPI_PARTITION_GAMES`).
> > Would you accept a PR which makes this check conditional?
> > _(none of this is covered by NDA, such information is publicly available in the Windows docs)_
> 
> Sure. send a PR. The goal of c-ares is to be as portable as possible. Not sure how to build for xbox, but if possible we should also add a CI/CD target to auto-build to make sure we don't regress in the future.

A full build isn't possible as the required tooling is not publicly available.
There is a public version called "Desktop GDK"/"GRDK" but it defeats the purpose as it includes the desktop APIs.

It all boils down to a macro dance in `winapifamily.h`. 
I wonder if it would be feasible to `#undef WINAPI_PARTITION_DESKTOP` or perform some similar gymnastic to trick `Windows.h` into thinking it's not compiling for desktop.
