### ISSUE TITLE
Build failure on macOS with 1.29.0

### ISSUE THREAD

**Issue by carlocab** [c-ares/c-ares#763]
We're attempting to update Homebrew's build of c-ares at Homebrew/homebrew-core#172703, but we're seeing this build failure on macOS:
```
  /tmp/c-ares-20240524-4454-o9b7t3/c-ares-1.29.0/src/lib/ares_sysconfig_mac.c:54:12: fatal error: 'thirdparty/apple/dnsinfo.h' file not found
  #  include "thirdparty/apple/dnsinfo.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This is occurring on all our macOS builds (macOS 12, 13, and 14 on both Intel and Apple Silicon).

We configure our build with
```
cmake -S . -B build \
	-DCARES_STATIC=ON \
	-DCARES_SHARED=ON \
	-DCMAKE_INSTALL_RPATH=@loader_path/../lib \
	-DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/c-ares/1.29.0 \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_FIND_FRAMEWORK=LAST \
	-DCMAKE_VERBOSE_MAKEFILE=ON \
	-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=/opt/homebrew/Library/Homebrew/cmake/trap_fetchcontent_provider.cmake \
	-Wno-dev \
	-DBUILD_TESTING=OFF \
	-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
```
(The exact `CMAKE_INSTALL_PREFIX` and `CMAKE_OSX_SYSROOT` varies between Intel and Apple Silicon builds and between macOS versions, of course.)

Complete build logs are available at https://github.com/Homebrew/homebrew-core/actions/runs/9221750588?pr=172703.

For example, the build log for macOS 14-arm64 is at https://github.com/Homebrew/homebrew-core/actions/runs/9221750588/job/25375456932?pr=172703, and the error starts at https://github.com/Homebrew/homebrew-core/actions/runs/9221750588/job/25375456932?pr=172703#step:3:711.

**Comment by bradh352** [comment]
Looks like the file didn't make it into the official tarball due to a missing reference.  I've committed a fix for the next package build we do.  It is, however, in the github-generated package: https://github.com/c-ares/c-ares/archive/refs/tags/cares-1_29_0.tar.gz
but obviously that package isn't signed.
It is also available directly in the repo:
https://github.com/c-ares/c-ares/blob/main/src/lib/thirdparty/apple/dnsinfo.h

**Comment by carlocab** [comment]
Thanks for the quick response! We can manually add the file for now and then remove the workaround for the next release.
