### ISSUE TITLE
1.29.0 android armv7 compile error

### ISSUE THREAD

**Issue by halx99** [c-ares/c-ares#767]
```txt
home/runner/work/1kiss/1kiss/buildsrc/cares/src/lib/ares_event_configchg.c:103:15: warning: cast from 'const unsigned char *' to 'const struct inotify_event *' increases required alignment from 1 to 4 [-Wcast-align]
      event = (const struct inotify_event *)ptr;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/1kiss/1kiss/buildsrc/cares/src/lib/ares_event_configchg.c:140:19: error: implicit declaration of function 'inotify_init1' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  c->inotify_fd = inotify_init1(IN_NONBLOCK | IN_CLOEXEC);
                  ^
/home/runner/work/1kiss/1kiss/buildsrc/cares/src/lib/ares_event_configchg.c:140:19: note: did you mean 'inotify_init'?
/usr/local/lib/android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/inotify.h:56:5: note: 'inotify_init' declared here
int inotify_init(void);
    ^
1 warning and 1 error generated.
```

see: https://github.com/simdsoft/1kiss/actions/runs/9227098524/job/25388317529#step:4:11529

**Comment by bradh352** [comment]
that particular error should be resolved in d1722e6
looks like we need an android ci system of our own

**Comment by halx99** [comment]
> looks like we need an android ci system of our own

Yes, that's better

**Comment by halx99** [comment]
Not sure does `inotify_init` works

![image](https://github.com/c-ares/c-ares/assets/6977319/9b076362-3b21-468b-bc0f-4024bddc4d99)

**Comment by halx99** [comment]
> Not sure does `inotify_init` works
> 
> ![image](https://private-user-images.githubusercontent.com/6977319/333810137-9b076362-3b21-468b-bc0f-4024bddc4d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTExMDQsIm5iZiI6MTcxNjY1MDgwNCwicGF0aCI6Ii82OTc3MzE5LzMzMzgxMDEzNy05YjA3NjM2Mi0zYjIxLTQ2OGItYmMwZi00MDI0YmRkYzRkOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMTUyNjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkzNWQzMTkwNzIzZDllMDI4ZTExODUyYzEyMGE0M2I0YTg1MWUzMjE4NTBjODllOWJkZGRjNWE2MGU0MThhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8lX0feX91QO3onGgUA3Yz6QRiEu74njmU9Lmo5MyN9g)

IF yes, then the code could be:
![image](https://github.com/c-ares/c-ares/assets/6977319/54d7eebb-f1ed-4ebe-add1-1e771931d3ba)

**Comment by bradh352** [comment]
Yeah, but there are no /etc/resolv.conf or /etc/nsswitch.conf to monitor on Android, so making it a noop is the proper move.  Not honestly sure how to handle automatic config reloading on Android.  Likely it would need some sort of Java implementation.

**Comment by halx99** [comment]
Fair enough
