### ISSUE TITLE
thirdparty/apple/dnsinfo.h is not in the release tarballs

### ISSUE THREAD

**Issue by jblazquez** [c-ares/c-ares#771]
[This file](https://github.com/c-ares/c-ares/blob/main/src/lib/thirdparty/apple/dnsinfo.h) is not in [this tarball](https://github.com/c-ares/c-ares/releases/download/cares-1_29_0/c-ares-1.29.0.tar.gz), so compilation of `ares_sysconfig_mac.c` fails.

**Comment by dfandrich** [comment]
Duplicate of #763.
