### ISSUE TITLE
Documentation misses buildconf command

### ISSUE THREAD

**Issue by GuillaumeRossolini** [c-ares/c-ares#78]
Hi,

When downloading the cares-1_12_0 release from GitHub, the INSTALL file says that building from source should start with the following command (pretty standard):
`./configure --help`

However, this results in an error:
`-bash: ./configure: No such file or directory`

One way to fix this is to run the following command first, which should probably be mentioned in the INSTALL file:
`./buildconf`

**Comment by bagder** [comment]
Probably because you're not only building "from source", you build directly from git even. Then there's a `GIT-INFO` file describing the additional details.

**Comment by GuillaumeRossolini** [comment]
I am not sure what you mean. I downloaded the latest archive from the releases tab here on GitHub. Is this not the recommended way to do it?

**Comment by bagder** [comment]
"releases" on github are just the files in the repo at the time the tag was set. A "proper" c-ares release is more than so and contains a number of generated files/contents and is also signed.

**Comment by GuillaumeRossolini** [comment]
Oh, my bad then. Some projects do it your way, others do their actual release here.

**Comment by bagder** [comment]
Yes. And if github would allow me, I would disable the github releases in all projects I do releases for...

**Comment by GuillaumeRossolini** [comment]
May I suggest you remind people of the recommended download page then, here on GitHub's releases page or in the release notes? This would avoid confusion, though I may very well be an isolated case.
