### ISSUE TITLE
WATT-32 support is broken

### ISSUE THREAD

**Issue by bradh352** [c-ares/c-ares#780]
Moving this discussion from comments:

>>> @gvanem
>>> So all this code needs Winsock2, no? So why not check for
>>> #ifdef USE_WINSOCK or #if (USE_WINSOCK == 2).
>>> Currently this code breaks with USE_WATT32.

>> @bradh352
>> This wasn't an intentional thing, just something more out of ignorance. I honestly don't know anything about WATT32. If you could give me some information on basic building instructions I can get this stuff cleaned up and also add a CI/CD workflow to prevent issues like this from cropping up again.

> @gvanem
> But I've no idea about CI for C-ares, but I have Appveyour [CI jobs](https://ci.appveyor.com/project/gvanem/watt-32) for Watt-32.
> So I guess building C-ares with -DWATT32 and Windows would need to fork Watt-32 (as a submodule) or use some artifacts from the above CIs (but Watt-32 does not currently contain any artifacts).

@bradh352 
c-ares already uses AppVeyor, all of our Windows builds use it except for OpenWatcom.   So we can probably use some examples from your code, looks like your actual `appveyor.yml` is here: https://github.com/gvanem/Watt-32/blob/master/appveyor.yml

1. What is the target OS you're most concerned with?
 - Win32 or DOS?
2. Which build system or makefile do you use within c-ares to try to build with WATT32 support?
 - I do see `-DWATT32` as an available option for `Makefile.msvc`, that obviously targets Win32.
 - I see `Makefile.watcom` can take a `use_watt32` argument, that also targets Win32. 
 - There's also an old `Makefile.dj` for DJGPP that targets DOS but I'm pretty sure that makefile is broken after a code reorg a few years back.
3. Should we use the official WATT-32 packages in CI, or actually build WATT-32 from Git and link to that?

**Comment by gvanem** [comment]
> What is the target OS you're most concerned with?
> Win32 or DOS?

Win32. I've not tested DOS (i.e. djgpp) and C-ares in some time. 

> 2. Which build system or makefile do you use within c-ares to try to build with WATT32 support?

I use a home-brewed [GNU-makefile](https://github.com/user-attachments/files/15753852/Makefile.Windows.txt) for all the combinations: Winsock2/Watt-32, MSVC/clang-cl, x86/x64 etc.

> I see Makefile.watcom can take a use_watt32 argument, that also targets Win32.

I seldom use Watcom. It's basically a dead product IMHO.

> There's also an old Makefile.dj for DJGPP that targets DOS but I'm pretty sure that makefile is broken after a code 
> reorg a few years back.

That's a trivial fix.

> 3. Should we use the official WATT-32 packages in CI, or actually build WATT-32 from Git and link to that?

If by *official WATT-32 packages* you mean some artifacts from the Watt-32 CI-job(s), I'm all for it.
But I'm not sure how to create some  artifact ZIP-file that could be used in a C-ares CI-job.

**Comment by bradh352** [comment]
> > 3. Should we use the official WATT-32 packages in CI, or actually build WATT-32 from Git and link to that?
> 
> If by _official WATT-32 packages_ you mean some artifacts from the Watt-32 CI-job(s), I'm all for it. But I'm not sure how to create some artifact ZIP-file that could be used in a C-ares CI-job.

I was meaning should I use the binary package on https://www.watt-32.net/ :
https://www.watt-32.net/watt32b.zip

**Comment by gvanem** [comment]
> I was meaning should I use the binary package on

Preferably not. These are not really up-to-date. But I'll make some new ZIPs.

**Comment by bradh352** [comment]
@gvanem this look right to you? https://github.com/c-ares/c-ares/actions/runs/9451657160/job/26033115523

I have no idea how to get the test cases going though since I don't know how to get Watt-32 set up in general, then even less so how to get it to work in a CI environment.

**Comment by gvanem** [comment]
@bradh352 I shimmed through the changes. This is good work since I'm clueless WRT to Github Workflows.

So I guess now linking the C-Ares/Watt-32 tools should be possible? But running them requires a silent install of 
WinPcap/NPcap; that's tricky in CI. But I can verify that the C-Ares/Watt-32 tools works here.

**Comment by gvanem** [comment]
> I have no idea how to get the test cases going though since I don't know how to get Watt-32 set up in general, 

Per the above, it needs a WinPcap or NPcap driver to be installed for live DNS requests/responses.

**Comment by bradh352** [comment]
> > I have no idea how to get the test cases going though since I don't know how to get Watt-32 set up in general,
> 
> Per the above, it needs a WinPcap or NPcap driver to be installed for live DNS requests/responses.

If I did go down the rabbit hole of trying to actually run the tests and was able to get WinPcap or NPcap installed, is there some configuration that needs to be performed, or does it just magically work and use the same ip address as the NIC has in the system already, etc etc?
