### ISSUE TITLE
Building v1.12 from source writes incorrect version number in libcares.pc

### ISSUE THREAD

**Issue by GuillaumeRossolini** [c-ares/c-ares#79]
This was first reported here:
https://github.com/nghttp2/nghttp2/issues/771

When building v1.12 from source, the `/usr/local/lib/pkgconfig/libcares.pc` file then contains the following:
```
#***************************************************************************
# Project        ___       __ _ _ __ ___  ___
#               / __|____ / _` | '__/ _ \/ __|
#              | (_|_____| (_| | | |  __/\__ \
#               \___|     \__,_|_|  \___||___/
#
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: c-ares
URL: http://daniel.haxx.se/projects/c-ares/
Description: asynchronous DNS lookup library
Version: -
Requires:
Requires.private:
Cflags: -I${includedir}
Libs: -L${libdir} -lcares
Libs.private:
```

I am not sure about the semantics of this file but it was the cause for nghttp2 not building from source:
```
checking for LIBCARES... no
configure: Requested 'libcares >= 1.7.5' but version of c-ares is -
```
(see the aforementioned issue for details)

When I manually changed the version number in `/usr/local/lib/pkgconfig/libcares.pc`, I could then build nghttp2 from source.

**Comment by bagder** [comment]
This happens because the version number is put in the configure script by the `maketgz` script that we use to do releases, and you probably built from git and not from a release archive.

**Comment by GuillaumeRossolini** [comment]
Actually, I downloaded the latest archive from the releases tab here on GitHub. Is this not the recommended way to do it?

**Comment by GuillaumeRossolini** [comment]
Like I said in issue #78:
My bad, I should have used the actual release from https://c-ares.haxx.se/
