### ISSUE TITLE
Broken Link in INSTALL.md

### ISSUE THREAD

**Issue by sarah-oloumi** [c-ares/c-ares#793]
The link for GIT-INFO is broken in [this section](https://github.com/c-ares/c-ares/blob/main/INSTALL.md#autotools-build): 
`If you have checked out the sources from the git repository, read the [GIT-INFO](https://github.com/c-ares/c-ares/blob/main/GIT_INFO) on how to proceed.`

I think the `_` should be a `-`.

I saw this on 1.27 and main -- did not check other ones but its probably broken everywhere if main is broken.

**Comment by bradh352** [comment]
Thanks! Fixed in f37cb2f
