### ISSUE TITLE
error C1041: cannot open program database when compiling

### ISSUE THREAD

**Issue by robionekenobi** [c-ares/c-ares#796]
Hi,

when compiling, we get the following error

10:10:34:025	3>------ Rebuild All started: Project: ahost, Configuration: Debug x64 ------
10:10:34:031	4>------ Rebuild All started: Project: adig, Configuration: Debug x64 ------
10:10:34:165	4>Building Custom Rule G:/Src/git/c-ares/src/tools/CMakeLists.txt
10:10:34:193	3>Building Custom Rule G:/Src/git/c-ares/src/tools/CMakeLists.txt
10:10:34:270	4>adig.c
10:10:34:303	3>ahost.c
10:10:34:342	3>ares_getopt.c
10:10:34:342	3>ares_strcasecmp.c
10:10:34:342	3>Generating Code...
10:10:34:342	3>G:\Src\git\c-ares\src\tools\ahost.c(1,1): error C1041: cannot open program database 'Z:\DevStudio\Work\c-ares\bin\Debug\vc143.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
10:10:34:342	3>G:\Src\git\c-ares\src\tools\ares_getopt.c(1,1): error C1041: cannot open program database 'Z:\DevStudio\Work\c-ares\bin\Debug\vc143.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
10:10:34:342	3>G:\Src\git\c-ares\src\lib\ares_strcasecmp.c(1,1): error C1041: cannot open program database 'Z:\DevStudio\Work\c-ares\bin\Debug\vc143.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
10:10:34:342	3>Done building project "ahost.vcxproj" -- FAILED.
10:10:34:530	4>ares_getopt.c
10:10:34:592	4>ares_strcasecmp.c
10:10:34:752	4>Generating Code...
10:10:34:950	4>adig.vcxproj -> Z:\DevStudio\Work\c-ares\bin\Debug\adig.exe

One way to avoid this is to add the /FS flag

I tried to add this in cmake\EnambleWarnings.cmake, and this worked fine

if (MSVC)
	# Don't automatically set /W3
	CMAKE_POLICY (SET CMP0092 NEW)

	# Visual Studio uses a completely different nomenclature for warnings than gcc/mingw/clang, so none of the
	# "-W[name]" warnings will work.

	# W4 would be better but it produces unnecessary warnings like:
	# *  warning C4706: assignment within conditional expression
	#     Triggered when doing "while(1)"
	# * warning C4115: 'timeval' : named type definition in parentheses
	# * warning C4201: nonstandard extension used : nameless struct/union
	#     Triggered by system includes (commctrl.h, shtypes.h, Shlobj.h)
	set(_flags
		# Enable warnings
		/FS # Force Synchronous PDB Write
		/W4 # Baseline reasonable warnings

Thanks
Robert

**Comment by bradh352** [comment]
I think 7d6de79 addresses this, but in a different way since /FS isn't a warning option

**Comment by gvanem** [comment]
Looks like the Makefiles for both `src/lib` and `src/tools` are done in parallel accessing the same `vc143.pdb` file.
Why? Adding `-FS` slows things down in my experience and seldom have the need for it. 

Why not force CMake to use `cl -MP` for  `src/lib` and `src/tools` in series? But I'm not so into the details of CMake.

**Comment by robionekenobi** [comment]
Hi,

Unfortunately it didn't work this change, as this Flag must be set in 'Additional Options' in VS2022

I also tried setting max number of parallel project build

> 1 parallel -> ========== Rebuild completed at 07:55 and took 19.444 seconds ==========
> 32 parallel -> 07:57:00:819	========== Rebuild completed at 07:57 and took 19.000 seconds ==========

Can you re-open this case or do I need to create a new one ?

Robert

**Comment by bradh352** [comment]
I don't know anything about Visual Studio at all honestly, so I don't know what needs to happen to address your issue.

**Comment by bradh352** [comment]
googling suggests the issue is that it is using shared intermediate directories, not sure how to correct that in cmake.  That said, I saw another possible solution which was to use /Z7 instead of /Zi to put the debug info into the object file instead of having it separate.  Not sure if that's a reasonable solution.

**Comment by bradh352** [comment]
according to this https://gitlab.kitware.com/cmake/cmake/-/issues/20222  /FS is already added by default in cmake when using visual studio : https://github.com/Kitware/CMake/blob/master/Modules/Platform/Windows-MSVC.cmake#L384

Which would be why manually adding /FS didn't do anything.

**Comment by bradh352** [comment]
so upon further review, I think its because the same source file is getting linked into multiple executables.  `ares_strcasecmp.c` and `ares_getopt.c` are the two.  I've never been a fan of the `ares_strcasecmp.c` as I'm not convinced that we even need that, just windows uses `stricmp()` instead of `strcasecmp()` to accomplish the same thing.  

Regarding them both using `ares_getopt.c`, not sure how to resolve that.  Honestly the compiler should be using different object names so it shouldn't matter.

I might at least get rid of ares_strcasecmp.c in its entirety.

**Comment by bradh352** [comment]
My evaluation was wrong, see #870 which should resolve this.
