### ISSUE TITLE
What is the proper way to read default values out of a channel from ares_save_options()?

### ISSUE THREAD

**Issue by sarah-oloumi** [c-ares/c-ares#799]
It looks like there were many changes in this commit: https://github.com/c-ares/c-ares/commit/c8bd83a4caec48dcb47037840a51dcd0abd3f902 

Starting from this point forward, what is the best way to read default values of a channel?

**Comment by bradh352** [comment]
There is no means to read default values.

**Comment by sarah-oloumi** [comment]
@bradh352 Would like to confirm that this was possible to do in v1.19.0 and prior to the commit above... correct?

**Comment by sarah-oloumi** [comment]
@bradh352, I have a few follow-up questions regarding the default values:
1. Could you clarify the source of these default values? I understand that some are aligned with `resolv.conf` as detailed here: https://man7.org/linux/man-pages/man5/resolv.conf.5.html, but there seem to be discrepancies for others. Where are these additional values derived from?
2. Regarding c-ares, does it impose any limitations on values similar to those found in resolv.conf, or are there differences in how values are capped? I was looking at `ares_sysconfig_files.c` but was not able to see anything being capped
3. Lastly, how do you verify these default values? Are there specific unit tests in place to ensure their accuracy?


Thanks in advance!

**Comment by bradh352** [comment]
> @bradh352 Would like to confirm that this was possible to do in v1.19.0 and prior to the commit above... correct?

the ares_save_options isn't able to return default and system-read values due to abi restrictions and the way the structure is defined.  It gets extended from release to release which means it can only support the options passed in during ares_init_options as those are what are known to be available to the ABI level of the implementation.

**Comment by bradh352** [comment]
> @bradh352, I have a few follow-up questions regarding the default values:
> 
> 1. Could you clarify the source of these default values? I understand that some are aligned with `resolv.conf` as detailed here: https://man7.org/linux/man-pages/man5/resolv.conf.5.html, but there seem to be discrepancies for others. Where are these additional values derived from?
> 2. Regarding c-ares, does it impose any limitations on values similar to those found in resolv.conf, or are there differences in how values are capped? I was looking at `ares_sysconfig_files.c` but was not able to see anything being capped
> 3. Lastly, how do you verify these default values? Are there specific unit tests in place to ensure their accuracy?
> 
> Thanks in advance!

Default values defined by c-ares are in ares_init.c:init_by_defaults(), system configuration is read in ares_sysconfig_files.c, ares_sysconfig_mac.c, ares_sysconfig_win.c, and ares_sysconfig.c.

Testing is coverage-based which you can see in our coveralls reports https://coveralls.io/github/c-ares/c-ares?branch=main

**Comment by bradh352** [comment]
I should also mention that at some point in the not too distant future the way c-ares gets initialized and configuration set/read will be changed to be a more modern with various setters/getters.
