### ISSUE TITLE
Memory allocation / free differences (v.1.28)

### ISSUE THREAD

**Issue by 0megae** [c-ares/c-ares#823]
Problem description: in the ares_hosts_file.c the function ares__hosts_entry_to_hostent() allocates the h_addr_list elements individually, whereas in the ares_free_hostent.c the ares_free_hostent() only frees the first element, stating there is only one malloc for them. This causes a memory leak.

**Comment by bradh352** [comment]
thanks for the report, should be fixed here shortly. Waiting for the CI builds to complete successfully. I'll cherry-pick it into the various branches we're still maintaining too.
