### ISSUE TITLE
TCP_FASTOPEN_CONNECT build failure on CentOS 7 (or older kernels)

### ISSUE THREAD

**Issue by eriklax** [c-ares/c-ares#850]
I full understand that CentOS 7 is EOL and you don't want to optimize for it. However it seems to be an easy fix to look for TCP_FASTOPEN_CONNECT instead of (or in addtion to) MSG_FASTOPEN.

CentOS 7 is using kernel version 3.10. TCP_FASTOPEN_CONNECT was added in [4.11](https://kernelnewbies.org/Linux_4.11) ([commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=19f6d3f3c8422d65b5e3d2162e30ef07c6e21ea2))

```
#if defined(__linux__) && defined(MSG_FASTOPEN)
#  define TFO_SUPPORTED      1
#  define TFO_SKIP_CONNECT   0
#  define TFO_USE_SENDTO     0
#  define TFO_USE_CONNECTX   0
#  define TFO_CLIENT_SOCKOPT TCP_FASTOPEN_CONNECT
```

**Comment by bradh352** [comment]
Yeah, we can make that change.  When I was implementing I thought I was going to use MSG_FASTOPEN but in testing it wasn't actually working so I switched to TCP_FASTOPEN_CONNECT, I guess I missed that ifdef.

**Comment by edsiper** [comment]
already hit by this one, so I cannot upgrade.

**Comment by bradh352** [comment]
Its already in main and backported to the 1.33 branch, so you can either pull the fix from there or wait on the next release.  Releases have been on a pretty quick cadence lately.  We also added a CI build specific to CentOS 7, even though its EOL to prevent regressions in the future with the old release.
