### ISSUE TITLE
1.33.0 does not build on old CentOS 7 system that does not support TCP_FASTOPEN_CONNECT

### ISSUE THREAD

**Issue by cd606** [c-ares/c-ares#854]
Hello, the version 1.33.0 fails to build on old CentOS 7 system that does not support TCP_FASTOPEN_CONNECT (kernel version is 3.10.0-1160.66.1.el7.x86_64). Is it possible to get this working for these older systems? Thanks.

**Comment by bradh352** [comment]
duplicate of #850 which is already fixed
