### ISSUE TITLE
adig: support way to specify default record type (rc file?)

### ISSUE THREAD

**Issue by tacerus** [c-ares/c-ares#855]
Hi,

on networks with IPv6 it is preferable to retrieve IPv6 information with tools without having to explicitly specify it. It hence would be great for my `adig` calls to return AAAA records by default.
I understand this might not be preferable for all users.
In case of `dig`, a `~/.digrc` file can be utilized to set default arguments, such as `-t AAAA`.

It would be great if a way to change the default record type, for example by supporting a `dig`-style rc file to specify default arguments, could be considered for `adig`.

But of course, I would also be open to have AAAA be the built-in default. ;-)

**Comment by bradh352** [comment]
adig in general should probably be more like dig in a lot of ways, such as command line processing in general just for compatibility testing.  We've made strides with the output format in recent versions.  I'd love someone to pick this up and run with it, but my resources are a bit limited as i've been trying to implement a bunch of RFCs into the core library that should have been done long ago.

**Comment by tacerus** [comment]
Thanks for the input.
I drafted some very basic implementation: https://github.com/c-ares/c-ares/pull/856.
