### ISSUE TITLE
SIG RR Record for `.` fails in cache lookups.

### ISSUE THREAD

**Issue by nodech** [c-ares/c-ares#858]
General name requests for the SOA work, but response for the `.` fail.

It specifically happens in:

```
 ares_dns_record_query_get ares_dns_record.c:342
 ares__qcache_calc_key ares_qcache.c:86
 ares_qcache_fetch ares_qcache.c:401
```

 which instead of `.` in `*name` - we have empty string,

If I comment the ares_qcache_fetch it works fine.

Tested with:
```
./bin/adig -t SOA .
```

**Comment by bradh352** [comment]
thanks for the report.  I fixed the issue and added a test case for it.  Working on backporting to prior releases now...
