### ISSUE TITLE
Feature: Support additional records section in response

### ISSUE THREAD

**Issue by alessionossa** [c-ares/c-ares#859]
The records in the additional records section are disregarded. There are a few lines already that are related to the additional records section, such as `DNS_HEADER_ARCOUNT`, but it is generally not parsed.

The specifications of this sections are in https://www.ietf.org/rfc/rfc1035.txt.

**Comment by bradh352** [comment]
Your request is already supported.

ares_dns_parse() will parse all records, and additional section records can be retrieved with ares_dns_record_rr_get(..., ARES_SECTION_ADDITIONAL, ...)

https://c-ares.org/docs/ares_dns_parse.html
https://c-ares.org/docs/ares_dns_rr.html
