### ISSUE TITLE
Link to RFC1035 is pointing to RFC7873

### ISSUE THREAD

**Issue by kmehltretter82** [c-ares/c-ares#861]
In README.md, the link to RFC1035 is pointing to RFC7873.

This looks like a mistake, but maybe it is intentional ?

The same issue exists in the c-ares homepage in section Features.

**Comment by bradh352** [comment]
whoops, definitely not intentional.  I'll get that corrected. Thanks! :)

**Comment by kmehltretter82** [comment]
Ok great thank you! I opened the link, quickly tried to find something about TXT records, and was confused :) 

Anyway, very nice to have this RFC list!
