### ISSUE TITLE
Can use the pattern per ares_channel per eventloop?

### ISSUE THREAD

**Issue by pa1gebro** [c-ares/c-ares#878]
I have create an application for multi-thread client, using c-ares. And I am using the pattern that per ares_channel per eventloop, the eventloop, which is a single thread, and in application there are more than one eventloop. But every query is work in a single thread context. But occasionally, the appliction could core dump with the ARES_ECONNREFUSED error.

I am confues if this pattern work well in my application.

**Comment by bradh352** [comment]
You could use a channel per event loop, but that would be fairly inefficient as it can't take advantage of things like the query cache, and in the future won't be able to take advantage of shared TLS sessions and whatnot.

Infact, these days I would recommend not using your own event loop with c-ares at all.  C-ares can spawn its own event loop  thread (ARES_OPT_EVENT_THREAD) and do its own processing and just call your callbacks when needed.  This has the advantage of all the caching and sharing while also automatically reloading the system configuration when changes are detected (that isn't supported unless you use c-ares's event thread).

You might want to check out the examples here:
https://c-ares.org/docs.html#examples

It has an example for usage of the event thread, or if you really want to use your own event loop, how to use sock_state_cb.

You might also want to look at https://c-ares.org/features/ which discusses the event thread and system configuration change stuff.

**Comment by bradh352** [comment]
Also, you may need to make sure you're running a recent version of c-ares ... ARES_OPT_EVENT_THREAD wasn't added until 1.26.0 ... Obviously the most recent version is always recommended.

**Comment by pa1gebro** [comment]
thx for ur reply, I have upgrade my c-ares from conan center to 1.33.0 and use the global extra thread mode. Up to now , the application work well .
