### ISSUE TITLE
Windows: arestest and mixing CRTs

### ISSUE THREAD

**Issue by gvanem** [c-ares/c-ares#89]
Several `test/*.cc` files have problems when `cares.dll` and `arestest.exe` was linked to separate CRTs.
E.g. compiling with `/MTd`, and passing a `FILE*` to/from C-ares and the application, triggers DbgReport like these:
```
caresd!_CrtDbgReportW(int report_type = 0n2, wchar_t * file_name = 0x6875b168 "minkernel\crts\ucrt\src\appcrt\lowio\read.cpp", int line_number = 0n378, wchar_t * module_name = 0x00000000 "", wchar_t * format = 0x6873fbf0 "%ls")+0x34
caresd!_read(int fh = 0n3, void * buffer = 0x04842b58, unsigned int buffer_size = 0x1000)+0x144
caresd!common_refill_and_read_nolock<char>(class __crt_stdio_stream stream = class__crt_stdio_stream)+0x155
caresd!__acrt_stdio_refill_and_read_narrow_nolock(struct _iobuf * stream = 0x04826500)+0x1a
caresd!_fgetc_nolock(struct _iobuf * public_stream = 0x04826500)+0xca
caresd!_getc_nolock(struct _iobuf * stream = 0x04826500)+0xe
caresd!__crt_char_traits<char>::getc_nolock<_iobuf *>(struct _iobuf ** <args_0> = 0x00faef80)+0x10
caresd!common_fgets<char>(char * string = 0x04841c88 "???", int count = 0n4, class __crt_stdio_stream stream = class __crt_stdio_stream)+0x223
caresd!fgets(char * string = 0x04841c88 "???", int count = 0n4, struct _iobuf * stream = 0x04826500)+0x22
caresd!ares__read_line(struct _iobuf * fp = 0x04826500, char ** buf = 0x00faf23c, unsigned int * bufsize = 0x00faf248)+0x8e
arestest!ares::test::LibraryTest_ReadLine_Test::TestBody(void)+0xb9
```

A case from `LibraryTest.ReadLine`:
```
  FILE *fp = fopen(temp.filename(), "r");
  ...
  EXPECT_EQ(ARES_SUCCESS, ares__read_line(fp, &buf, &bufsize));
```

In this case, one cannot pass this `fp` across CRT boundaries.
But what options do we have? A new `ares_open_file()` function?

And in another case, mixing memory blocks across CRTs triggers similar reports.

**Comment by bradh352** [comment]
Are there any instances in the public api where this is a concern?  I'm not seeing anything at first glance that mixes file pointers or malloc/free.  If not, I don't believe this is something that should be addressed.

**Comment by gvanem** [comment]
You're replying to an almost 1 year PR. I don't remember. 
But there are issues with e.g. mixing a `_DEBUG` built caresd.dll with `CURLDEBUG` in libcurl. So just don't do that.

**Comment by bradh352** [comment]
alright, closing this then.
