### ISSUE TITLE
Packaging: Different set of manpages between git tag and release archive for 1.34.1

### ISSUE THREAD

**Issue by diizzyy** [c-ares/c-ares#899]
Installing by pulling the repo from git (using tag v1.34.1) includes following additional files compared to release archive:

man/man3/ares_dns_rr_del_opt_byid.3.gz
man/man3/ares_set_socket_functions_ex.3.gz

Tested with CMake build

**Comment by bradh352** [comment]
thanks, i'll add those for a future release.

**Comment by bradh352** [comment]
this was committed to git in 1462d24
