### ISSUE TITLE
Host Resolution Failure on Android 7 and Below After C-Ares Upgrade from 1.19.0 to 1.28.1

### ISSUE THREAD

**Issue by gowthamanpalanisamy-tomtom** [c-ares/c-ares#907]
One of our services uses curl 8.10.0 along with C-Ares 1.19.0 for establishing connections and resolving domain names. After upgrading the C-Ares library to 1.28.1, we’re encountering a "host unable to resolve" error on Android 7 and earlier versions, while it works as expected on Android 8 and above. This behaviour is unusual, and we suspect there might be backward compatibility issues with C-Ares versions following 1.19.0 (though the exact version causing the issue is unclear).

Could anyone provide insights into the cause of this issue?

**Comment by bradh352** [comment]
Please try a70637c

**Comment by gowthamanpalanisamy-tomtom** [comment]
Hi @bradh352 Thanks a lot for the quick response. I’m using autotools (./configure) to configure C-Ares. I’ll try out [this commit](https://github.com/c-ares/c-ares/commit/a70637c67ba2657adb54b077f4f8434f00ecbf83) and get back to you.

**Comment by gowthamanpalanisamy-tomtom** [comment]
Hi @bradh352, I tested with [commit a70637c67ba2657adb54b077f4f8434f00ecbf83](https://github.com/c-ares/c-ares/commit/a70637c67ba2657adb54b077f4f8434f00ecbf83), and it resolves the DNS resolution issues on Android 6. It appears that these changes haven’t been included in an official release yet. Could you let us know when the next c-ares release is expected?

**Comment by bradh352** [comment]
That's good to know it fixes your issue.  There's no specific ETA on the next release, we've been doing release recently about every 30 days or so unless there is a significant issue affecting a large portion of users, then we do bugfix releases earlier.
