### ISSUE TITLE
Unclear behavior when using c-ares in gRPC

### ISSUE THREAD

**Issue by o-hainz** [c-ares/c-ares#909]
Hello,
We are using `vcpkg` to build `gRPC` (and this is using `c-ares`):
[https://github.com/microsoft/vcpkg](https://github.com/microsoft/vcpkg).
We  are working with MS Visual Studio 2022 on Microsoft Window.
With the `vcpkg` version [2024.09.30](https://github.com/microsoft/vcpkg/releases/tag/2024.09.30) everything works fine.
With the update to version [2024.10.21](https://github.com/microsoft/vcpkg/releases/tag/2024.10.21) our application stops working. The build still works, but during the execution we run in issues and we cannot create a `gRPC` connection/channel (when the first call should be done).
We saw in the list of the updated ports that `c-ares` was updated from version `1.33.1` to version `1.34.1`.
After this we manipulated the `c-ares` version in the `vcpkg` from `1.34.1` back to `1.33.1` our application works again. 
Then we try to use the newer `c-ares` version `1.34.2`, but here the error still occurs.

Our application stops here in this file `grpc\src\v1.60.0-cff025ca16.clean\src\core\lib\gprpp\crash.cc` in the line `abort();`:

```cpp
namespace grpc_core {

void Crash(absl::string_view message, SourceLocation location) {
  gpr_log(location.file(), location.line(), GPR_LOG_SEVERITY_ERROR, "%s",
          std::string(message).c_str());
  abort();
}
```
Here also the values of the parameters in the function crash:

 - `message` = `ASSERTION FAILED: *from_len <= recv_from_source_addr_len_`
 - `location.file()` = `grpc\src\v1.60.0-cff025ca16.clean\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_ev_driver_windows.cc`
 - `location.line()` = 311

Our call stack looks like this:

```txt
grpc_core::Crash(absl::lts_20240722::string_view message, grpc_core::SourceLocation location) Line 33	C++
gpr_assertion_failed(const char * filename, int line, const char * message) Line 53	C++
grpc_core::`anonymous namespace'::GrpcPolledFdWindows::RecvFrom(grpc_core::`anonymous-namespace'::WSAErrorContext * wsa_error_ctx, void * data, unsigned int data_len, int __formal, sockaddr * from, int * from_len) Line 311	C++
grpc_core::`anonymous namespace'::GrpcPolledFdFactoryWindows::RecvFrom(unsigned int as, void * data, unsigned int data_len, int flags, sockaddr * from, int * from_len, void * user_data) Line 792	C++
...External Code...
on_readable(void * arg, absl::lts_20240722::Status error) Line 368	C++
exec_ctx_run(grpc_closure * closure) Line 45	C++
grpc_core::ExecCtx::Flush() Line 84	C++
pollset_work(grpc_pollset * pollset, grpc_pollset_worker * * worker_hdl, grpc_core::Timestamp deadline) Line 133	C++
grpc_pollset_work(grpc_pollset * pollset, grpc_pollset_worker * * worker, grpc_core::Timestamp deadline) Line 48	C++
cq_pluck(grpc_completion_queue * cq, void * tag, gpr_timespec deadline, void * reserved) Line 1283	C++
grpc_completion_queue_pluck(grpc_completion_queue * cq, void * tag, gpr_timespec deadline, void * reserved) Line 1309	C++
grpc::CompletionQueue::Pluck(grpc::internal::CompletionQueueTag * tag) Line 322	C++
grpc::internal::BlockingUnaryCallImpl<google::protobuf::MessageLite,google::protobuf::MessageLite>::BlockingUnaryCallImpl<google::protobuf::MessageLite,google::protobuf::MessageLite>(grpc::ChannelInterface * channel, const grpc::internal::RpcMethod & method, grpc::ClientContext * context, const google::protobuf::MessageLite & request, google::protobuf::MessageLite * result) Line 88	C++
grpc::internal::BlockingUnaryCall<event_store::client::persistent_subscriptions::ListReq,event_store::client::persistent_subscriptions::ListResp,google::protobuf::MessageLite,google::protobuf::MessageLite>(grpc::ChannelInterface * channel, const grpc::internal::RpcMethod & method, grpc::ClientContext * context, const event_store::client::persistent_subscriptions::ListReq & request, event_store::client::persistent_subscriptions::ListResp * result) Line 49	C++
```

Let me know how we can help to fix our issue.

**Comment by bradh352** [comment]
This is a gRPC internal issue they must resolve. They have an inverted assertion unfortunately that is just invalid. Please see https://github.com/grpc/grpc/issues/37969

**Comment by o-hainz** [comment]
Thank you a lot for your quick feedback and referencing to the `gRPC` issue.
