### ISSUE TITLE
Regarding DNS query resolution

### ISSUE THREAD

**Issue by Gaurav0411GitHub** [c-ares/c-ares#912]
We are using envoy 1.29.1, We have observed that DNS resolution in Envoy is working correctly when the order of queries is CNAME first, followed by an A record query. However, on the other hand, if the order appears to be reversed, with the A query preceding the CNAME. we are not getting dns server address.

We are getting below logs
[2024-11-06 10:49:05.345][73544][debug][forward_proxy] [source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:260] host='iosw-ecm.itn.ftgroup:80' TTL check: now=87371891452624 last_used=87131862726512 TTL 300000
[2024-11-06 10:49:05.345][73544][debug][forward_proxy] [source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:309] starting main thread resolve for host='iosw-ecm.itn.ftgroup:80' dns='iosw-ecm.itn.ftgroup' port='80' timeout='5000'
[2024-11-06 10:49:05.345][73544][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:365] dns resolution for iosw-ecm.itn.ftgroup started
[2024-11-06 10:49:05.352][73544][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:154] dns resolution without records for iosw-ecm.itn.ftgroup
[2024-11-06 10:49:05.352][73544][debug][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:283] dns resolution for iosw-ecm.itn.ftgroup completed with status 0
[2024-11-06 10:49:05.352][73544][debug][forward_proxy] [source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:330] main thread resolve complete for host 'iosw-ecm.itn.ftgroup:80': []
[2024-11-06 10:49:05.352][73544][debug][forward_proxy] [source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:434] DNS refresh rate reset for host 'iosw-ecm.itn.ftgroup:80', refresh rate 60000 ms

In envoy 1.29.1, c-ares 1.19.1 is used. Please clarify below queries
1. Is standard allows to send CNAME after A-Query?
2. Is this a bug on c-ares 1.19.1 which is resolved in any other version? 
3. When we are receiving CNAME after A-Query, In this case, I need to understand how the DNS server Ips are picked here, Is it based on /etc/resolv.conf file?    
4. Is there a feasibility to configure the DNS IP address only for envoy?

**Comment by bradh352** [comment]
I'm not sure I understand what you're saying is occurring.  What do you mean by: "order of the queries is CNAME first followed by an A record"?  Do you mean the order of the records in the response?  c-ares is a stub DNS resolver so the upstream server is responsible for recursing if it receives a CNAME from the authoritative server. 

If you really think there is a bug in c-ares, please upgrade to our current release and re-test.  A lot of the internal logic and parsers have been replaced so any behavior from 1.19 isn't really relevant to modern releases of c-ares (other than desired behavior enforced by our test system).

DNS servers, by default, are read from the system configuration.  On most Unix-like systems, yes, that is /etc/resolv.conf.  However c-ares does provide API calls to configure a different set of servers, I couldn't tell you what Envoy does, you'd need to reach out to them.

**Comment by Gaurav0411GitHub** [comment]
Thanks for your response
![image](https://github.com/user-attachments/assets/fe56899c-0039-492c-b148-c98e7861812a)
This case of first A-Record and Then CNAME is not working. Is this handling done in c-ares

**Comment by bradh352** [comment]
Looks like a single packet with both CNAME and A records in the response, which is valid.  I can't say if this is a c-ares issue or an Envoy issue in reading the response.  I'm not sure what APIs they use to integrate with c-ares.  But I do know that as far as c-ares is concerned, the parsers for that stuff were completely rewritten in v1.21 so it is unlikely if there was an issue in 1.19 that it still exists today.

**Comment by Gaurav0411GitHub** [comment]
Yes, I am talking about single response having CNAME and A-Record.
if CNAME and then A-record is coming, this is working fine.
But if A-record and then CNAME is coming, this is not working. So I am discussing only about  this packet. Is this order of A-record and then CNAME handling is done in 1.19.1?

**Comment by bradh352** [comment]
Well, its possible there's an issue as someone in the old parser wrote a comment: 

https://github.com/c-ares/c-ares/blob/6360e96b5cf8e5980c887ce58ef727e53d77243a/src/lib/ares__parse_into_addrinfo.c#L152C1-L155C1

which would definitely impact the sanity check here:

https://github.com/c-ares/c-ares/blob/6360e96b5cf8e5980c887ce58ef727e53d77243a/src/lib/ares__parse_into_addrinfo.c#L111C1-L113C1

None of that logic still exists in modern versions of c-ares.

**Comment by Gaurav0411GitHub** [comment]
So it's an issue c-ares that is not solved in any version of c-ares

**Comment by bradh352** [comment]
In theory, it is solved in c-ares 1.21 or higher.  Like I said, the code I identified that might explain your issue no longer exists in modern versions of c-ares.

**Comment by bradh352** [comment]
actually it looks like some of that logic was kept until c-ares 1.26.0 even with the new parser... so 1.26.0 or higher wouldn't have that behavior.

**Comment by Gaurav0411GitHub** [comment]
Could You please help in understanding what/where you have done changes in 1.26.0 of higher version to handle this kind of behaviour

**Comment by bradh352** [comment]
A majority of c-ares has been rewritten since 1.19.1.  The most relevant PRs to your particular issue are #581 and #685
