### ISSUE TITLE
TXT query error if empty TXT record exists

### ISSUE THREAD

**Issue by vlasovsoft1979** [c-ares/c-ares#921]
Hi!

Currently I have the following test configuration on my test DNS server:

```
~$ nslookup -port=10000 -type=txt domain.com 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#10000

Non-authoritative answer:
domain.com      text = "some text example"
domain.com      text = ""

Authoritative answers can be found from:

```

c-ares versions prior to 1.32.0 produce correct results. But starting from 1.32.0 and including the current version 1.34.3 c-ares returns "DNS lookup failed: DNS server claims query was misformatted"

This happens not only on my test DNS server, but also on real customer's domain.

I've attached a minimal C++ example, but you should replace the "domain.com" with real domain with empty "TXT" record.
[cares_txt_bug.cpp.zip](https://github.com/user-attachments/files/17745976/cares_txt_bug.cpp.zip)

**Comment by bradh352** [comment]
can you try PR #922 to see if that fixes it ?

**Comment by bradh352** [comment]
if that doesn't fix it, I'll need a packet capture of the response sent so I can add it as a test case and correct it.

**Comment by vlasovsoft1979** [comment]
> can you try PR #922 to see if that fixes it ?

This PR helped, thanks!

**Comment by bradh352** [comment]
ok, merged into main and backported into the affected branches
