### ISSUE TITLE
c-ares DNS over UDP fails on truncated packets

### ISSUE THREAD

**Issue by adspx5** [c-ares/c-ares#923]
I'm using grpc/c-ares 1.31 or 1.32
RecvFrom() blows on GPR_ASSERT(*from_len <= recv_from_source_addr_len_);

It looks like it happens in case of truncated UDP packets (FQDN I'm testing with is long.. like my_very_long_department_name._my_very_very_long_company_name.com)

Is there a way to fix this issue or avoid this assert?

Thank you!

![42141_grpc_blows3](https://github.com/user-attachments/assets/a5c4d5b1-8d4b-40b3-9071-eb5edb884f5f)

**Comment by bradh352** [comment]
Your evaluation is incorrect, the error is in retrieving the source address of the packet, nothing to do with the data in the packet.  Please see https://github.com/grpc/grpc/issues/37969

This is not a c-ares issue.
