### ISSUE TITLE
Compatibility with CMake < 3.10 will be removed

### ISSUE THREAD

**Issue by BartolomeyKant** [c-ares/c-ares#926]
I've got a message after my local cmake update to version 3.31

```
CMake Deprecation Warning at c-ares/CMakeLists.txt:3 (CMAKE_MINIMUM_REQUIRED):
Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

**Comment by bradh352** [comment]
Looks like we need to change `CMAKE_MINIMUM_REQUIRED (VERSION 3.5.0)` to `CMAKE_MINIMUM_REQUIRED (VERSION 3.5.0...3.10.0)` as per https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html:
> Changed in version 3.31: Compatibility with versions of CMake older than 3.10 is deprecated. Calls to [cmake_minimum_required(VERSION)](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#command:cmake_minimum_required) or [cmake_policy(VERSION)](https://cmake.org/cmake/help/latest/command/cmake_policy.html#version) that do not specify at least 3.10 as their policy version (optionally via ...<max>) will produce a deprecation warning in CMake 3.31 and above.
