### ISSUE TITLE
Localhost IPv6 resolving bug

### ISSUE THREAD

**Issue by syberrus** [c-ares/c-ares#946]
resolving with ares_getaddrinfo() for "localhost" with AF_INET6 returns successful result with ai->nodes set to NULL. (it must not be NULL when status is success)

bug appeared in 1.22 where ares__addrinfo_localhost() no more called from file_lookup() because it was successfully processed by ares__hosts_search_host() and ares__hosts_entry_to_addrinfo() however they didn't add entry to ai->nodes.

at least with my /etc/hosts

127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by syberrus** [comment]
Summary: when IPv6 localhost is disabled in /etc/hosts, c-ares return success with nullptr in ai->nodes which leads to SIGSEGV in user space code as it is a restricted behaviour by docs.

c-ares should either add a node by hand (as prior to 1.22), or return ARES_ENOTFOUND (i prefer the latter because according to /etc/hosts IPv6 alias is disable on such server).

**Comment by bradh352** [comment]
What OS are you on?  And you said you're definitely using AF_INET6 and not AF_UNSPEC for the address family on the query, right?

**Comment by syberrus** [comment]
Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
Yes, call ares_getaddrinfo() with AF_INET6, having deleted "::1 localhost" in your /etc/hosts (there must be no alias for IPv6 localhost) and you'll see the bug

**Comment by bradh352** [comment]
what version of c-ares are you running?

**Comment by bradh352** [comment]
I added some containerized tests and I think I am able to reproduce the issue: https://github.com/c-ares/c-ares/compare/main...bradh352:c-ares:localhost

**Comment by syberrus** [comment]
> what version of c-ares are you running?

Any version starting from 1.22 (i checked all of them). Before 1.22 (1.21 and earlier) it returns ::1 regardless of /etc/hosts contents

**Comment by bradh352** [comment]
please try PR #947, I think it should resolve your issue

**Comment by syberrus** [comment]
yup it helps. Thanks!
